## A fuller template for the Payments team: a literal name, an AI summary, a
## severity merge strategy, and a custom field bound through an expression.

resource "incident_incident_template" "payments" {
  name = "Payments incidents"

  ## Expressions the template's bindings can reference. Here we navigate from the
  ## incident to its "team" custom field so the binding below can reuse it.
  expressions = [
    {
      label          = "Team"
      reference      = "team"
      root_reference = "incident"
      operations = [
        {
          operation_type = "navigate"
          navigate = {
            reference = "incident.custom_field[\"team\"]"
          }
        },
      ]
    },
  ]

  template = {
    ## A literal incident name.
    name = {
      autogenerated = false
      value = {
        literal = "Payments incident"
      }
    }

    ## The incident summary, written by AI.
    summary = {
      autogenerated = true
    }

    ## Take the highest severity when several alerts contribute to one incident.
    ## Add a `binding` here to also set a fixed starting severity.
    severity = {
      merge_strategy = "max"
    }

    ## Start incidents from this template in triage.
    start_in_triage = {
      value = {
        literal = "true"
      }
    }

    ## Set a custom field from the "Team" expression above.
    custom_fields = [
      {
        custom_field_id = data.incident_custom_field.affected_team.id
        merge_strategy  = "first-wins"
        binding = {
          value = {
            reference = "expressions[\"team\"]"
          }
        }
      },
    ]
  }
}

data "incident_custom_field" "affected_team" {
  name = "Affected team"
}
