## The simplest useful template: a fixed incident name, with the summary left to
## AI. Everything else falls back to the organisation's defaults.

resource "incident_incident_template" "minimal" {
  name = "Support escalations"

  ## Required, even when the template binds nothing through an expression.
  expressions = []

  template = {
    ## A literal incident name.
    name = {
      autogenerated = false
      value = {
        literal = "Support escalation"
      }
    }

    ## Let AI write the summary from the incident's context.
    summary = {
      autogenerated = true
    }
  }
}
