## Let AI generate both the name and the summary, and start incidents from this
## template in triage so a human confirms them before they go fully active.

resource "incident_incident_template" "ai_generated" {
  name = "AI-drafted incidents"

  template = {
    ## autogenerated = true tells the AI to write the value; the value binding is
    ## left out because there's nothing to bind.
    name = {
      autogenerated = true
    }

    summary = {
      autogenerated = true
    }

    start_in_triage = {
      value = {
        literal = "true"
      }
    }
  }
}
