package models

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/incident-io/terraform-provider-incident/internal/client"
	"github.com/samber/lo"
)

// TestAlertRouteV2RoundTrip is a light round-trip of the v2 mapping. Its main
// job (beyond confirming v2 fields survive) is to assert that the v3-only
// fields on the shared merged model come back null in v2 mode, so v2 state
// keeps its shape and IsV3Mode stays false.
func TestAlertRouteV2RoundTrip(t *testing.T) {
	api := client.AlertRouteV2{
		Id:        "01ABC",
		Name:      "route",
		Enabled:   true,
		IsPrivate: false,
		Version:   2,
		AlertSources: []client.AlertRouteAlertSourceV2{
			{AlertSourceId: "01SRC", ConditionGroups: []client.ConditionGroupV2{}},
		},
		ChannelConfig:   []client.AlertRouteChannelConfigV2{},
		ConditionGroups: []client.ConditionGroupV2{},
		Expressions:     []client.ExpressionV2{},
		EscalationConfig: client.AlertRouteEscalationConfigV2{
			AutoCancelEscalations: true,
			EscalationTargets:     []client.AlertRouteEscalationTargetV2{},
		},
		IncidentConfig: client.AlertRouteIncidentConfigV2{
			AutoDeclineEnabled:      false,
			AutoRelateGroupedAlerts: true,
			DeferTimeSeconds:        0,
			Enabled:                 true,
			GroupingKeys:            []client.GroupingKeyV2{{Reference: "alert.title"}},
			GroupingWindowSeconds:   300,
		},
		IncidentTemplate: client.AlertRouteIncidentTemplateV2{
			Name: client.AlertRouteAutoGeneratedTemplateBindingV2{Autogenerated: true},
		},
	}

	model := AlertRouteResourceModel{}.FromAPIV2(api)

	// Mode: no grouping_config, so this is a v2-mode model.
	if model.IsV3Mode() {
		t.Error("expected IsV3Mode to be false for a v2 route")
	}

	// v2 fields survive.
	if got := model.Name.ValueString(); got != "route" {
		t.Errorf("name: got %q", got)
	}
	if got := model.IncidentConfig.GroupingWindowSeconds.ValueInt64(); got != 300 {
		t.Errorf("grouping_window_seconds: got %d", got)
	}
	if !model.IncidentConfig.AutoRelateGroupedAlerts.ValueBool() {
		t.Error("auto_relate_grouped_alerts should be true")
	}
	if got := len(model.IncidentConfig.GroupingKeys); got != 1 {
		t.Errorf("grouping_keys: got %d", got)
	}
	if !model.EscalationConfig.AutoCancelEscalations.ValueBool() {
		t.Error("auto_cancel_escalations should be true")
	}
	if model.IncidentTemplate == nil || !model.IncidentTemplate.Name.Autogenerated.ValueBool() {
		t.Error("incident_template.name should be autogenerated")
	}

	// v3-only fields must be null/nil in v2 mode.
	if !model.EscalationConfig.WhenAlertJoinsGroup.IsNull() {
		t.Error("escalation_config.when_alert_joins_group should be null in v2 mode")
	}
	if model.IncidentConfig.Template != nil {
		t.Error("incident_config.template should be nil in v2 mode")
	}
	if model.GroupingConfig != nil {
		t.Error("grouping_config should be nil in v2 mode")
	}
	if model.MessageConfig != nil {
		t.Error("message_config should be nil in v2 mode")
	}

	// Round-trip back to a payload and confirm key v2 fields are carried.
	payload := model.ToCreatePayloadV2()
	if payload.IncidentConfig.GroupingWindowSeconds != 300 {
		t.Errorf("payload grouping_window_seconds: got %d", payload.IncidentConfig.GroupingWindowSeconds)
	}
	if !payload.EscalationConfig.AutoCancelEscalations {
		t.Error("payload auto_cancel_escalations should be true")
	}
}

// TestAlertRouteV2EscalationPathTargetIgnoresDuplicateUsers covers ONC-12476: for
// an escalation-path target the API echoes the same binding back in `users` too
// (legacy frontend compatibility, pending ONC-5335). Because escalation_targets
// is a set, surfacing that duplicate as a configured `users` value leaves the
// read-back element unable to correlate with the planned element (users = null),
// which Terraform reports as "Provider produced inconsistent result after apply".
// FromAPIV2 must therefore drop the duplicated users and keep only escalation_paths.
func TestAlertRouteV2EscalationPathTargetIgnoresDuplicateUsers(t *testing.T) {
	pathBinding := &client.EngineParamBindingV2{
		ArrayValue: &[]client.EngineParamBindingValueV2{
			{Literal: lo.ToPtr("01FAKEFAKEFAKEFAKEFAKEFAKE")},
		},
	}

	api := client.AlertRouteV2{
		Id:              "01ABC",
		Name:            "route",
		Version:         2,
		AlertSources:    []client.AlertRouteAlertSourceV2{},
		ChannelConfig:   []client.AlertRouteChannelConfigV2{},
		ConditionGroups: []client.ConditionGroupV2{},
		Expressions:     []client.ExpressionV2{},
		EscalationConfig: client.AlertRouteEscalationConfigV2{
			EscalationTargets: []client.AlertRouteEscalationTargetV2{
				// Escalation-path target: the API duplicates the binding into users.
				{EscalationPaths: pathBinding, Users: pathBinding},
			},
		},
		IncidentConfig:   client.AlertRouteIncidentConfigV2{GroupingKeys: []client.GroupingKeyV2{}},
		IncidentTemplate: client.AlertRouteIncidentTemplateV2{},
	}

	model := AlertRouteResourceModel{}.FromAPIV2(api)

	if got := len(model.EscalationConfig.EscalationTargets); got != 1 {
		t.Fatalf("escalation_targets: got %d, want 1", got)
	}
	target := model.EscalationConfig.EscalationTargets[0]
	if target.EscalationPaths == nil {
		t.Error("escalation_paths should be set")
	}
	if target.Users != nil {
		t.Error("users should be nil for an escalation-path target (API duplicate must be dropped)")
	}
}

// TestAlertRouteV2ReconcilesConditionOperation covers ONC-12602 end-to-end: the
// planned `one_of` survives a `contains_one_of` read-back, and an import with no
// plan keeps the API value.
func TestAlertRouteV2ReconcilesConditionOperation(t *testing.T) {
	api := client.AlertRouteV2{
		Id:            "01ABC",
		Name:          "route",
		Version:       2,
		AlertSources:  []client.AlertRouteAlertSourceV2{},
		ChannelConfig: []client.AlertRouteChannelConfigV2{},
		ConditionGroups: []client.ConditionGroupV2{
			{
				Conditions: []client.ConditionV2{
					{
						Subject:   client.ConditionSubjectV2{Reference: "alert.attributes.01GH"},
						Operation: client.ConditionOperationV2{Value: "contains_one_of"},
					},
				},
			},
		},
		Expressions: []client.ExpressionV2{},
		EscalationConfig: client.AlertRouteEscalationConfigV2{
			EscalationTargets: []client.AlertRouteEscalationTargetV2{},
		},
		IncidentConfig:   client.AlertRouteIncidentConfigV2{GroupingKeys: []client.GroupingKeyV2{}},
		IncidentTemplate: client.AlertRouteIncidentTemplateV2{},
	}

	plan := &AlertRouteResourceModel{
		ConditionGroups: IncidentEngineConditionGroups{
			{
				Conditions: IncidentEngineConditions{
					{
						Subject:   types.StringValue("alert.attributes.01GH"),
						Operation: types.StringValue("one_of"),
					},
				},
			},
		},
	}

	withPlan := AlertRouteResourceModel{}.FromAPIV2WithPlan(api, plan)
	if got := withPlan.ConditionGroups[0].Conditions[0].Operation.ValueString(); got != "one_of" {
		t.Errorf("with plan: operation should be reconciled to %q, got %q", "one_of", got)
	}

	noPlan := AlertRouteResourceModel{}.FromAPIV2(api)
	if got := noPlan.ConditionGroups[0].Conditions[0].Operation.ValueString(); got != "contains_one_of" {
		t.Errorf("no plan: operation should stay verbatim %q, got %q", "contains_one_of", got)
	}
}

// TestReconcileAlertSourceOperationsCorrelatesByID asserts alert source conditions
// still reconcile when the API returns the sources in a different order to the
// plan, and that we do not reconcile against the wrong source.
func TestReconcileAlertSourceOperationsCorrelatesByID(t *testing.T) {
	source := func(id, operation string) AlertRouteAlertSourceModel {
		return AlertRouteAlertSourceModel{
			AlertSourceID: types.StringValue(id),
			ConditionGroups: IncidentEngineConditionGroups{
				{Conditions: IncidentEngineConditions{
					{
						Subject:   types.StringValue("alert.attributes.01GH"),
						Operation: types.StringValue(operation),
					},
				}},
			},
		}
	}
	operationOf := func(s AlertRouteAlertSourceModel) string {
		return s.ConditionGroups[0].Conditions[0].Operation.ValueString()
	}

	applied := []AlertRouteAlertSourceModel{
		source("01SOURCEA", "contains_one_of"),
		source("01SOURCEB", "contains_one_of"),
	}
	// Same sources in the opposite order, and only source B planned `one_of`.
	plan := []AlertRouteAlertSourceModel{
		source("01SOURCEB", "one_of"),
		source("01SOURCEA", "contains_one_of"),
	}

	reconcileAlertSourceOperations(applied, plan)

	if got := operationOf(applied[0]); got != "contains_one_of" {
		t.Errorf("source A planned contains_one_of, should be left alone, got %q", got)
	}
	if got := operationOf(applied[1]); got != "one_of" {
		t.Errorf("source B planned one_of, should be reconciled, got %q", got)
	}

	// An unplanned source is left alone, and a nil plan must not panic.
	unplanned := []AlertRouteAlertSourceModel{source("01SOURCEC", "contains_one_of")}
	reconcileAlertSourceOperations(unplanned, plan)
	if got := operationOf(unplanned[0]); got != "contains_one_of" {
		t.Errorf("unplanned source should be left alone, got %q", got)
	}
	reconcileAlertSourceOperations(unplanned, nil)
}

// TestAlertRouteV2UserTargetKeepsUsers confirms the sibling case: a genuine user
// target (escalation_paths absent) still maps users through.
func TestAlertRouteV2UserTargetKeepsUsers(t *testing.T) {
	userBinding := &client.EngineParamBindingV2{
		ArrayValue: &[]client.EngineParamBindingValueV2{
			{Literal: lo.ToPtr("01USER")},
		},
	}

	api := client.AlertRouteV2{
		Id:              "01ABC",
		Name:            "route",
		Version:         2,
		AlertSources:    []client.AlertRouteAlertSourceV2{},
		ChannelConfig:   []client.AlertRouteChannelConfigV2{},
		ConditionGroups: []client.ConditionGroupV2{},
		Expressions:     []client.ExpressionV2{},
		EscalationConfig: client.AlertRouteEscalationConfigV2{
			EscalationTargets: []client.AlertRouteEscalationTargetV2{
				{Users: userBinding},
			},
		},
		IncidentConfig:   client.AlertRouteIncidentConfigV2{GroupingKeys: []client.GroupingKeyV2{}},
		IncidentTemplate: client.AlertRouteIncidentTemplateV2{},
	}

	model := AlertRouteResourceModel{}.FromAPIV2(api)

	target := model.EscalationConfig.EscalationTargets[0]
	if target.Users == nil {
		t.Error("users should be set for a user target")
	}
	if target.EscalationPaths != nil {
		t.Error("escalation_paths should be nil for a user target")
	}
}
