package models

import (
	"context"
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/samber/lo"

	"github.com/incident-io/terraform-provider-incident/internal/client"
)

// This file holds the v3 alert routes mapping for the AlertRouteResourceModel.
//
// The single incident_alert_route resource supports both the v2 and v3 alert
// routes APIs. The presence of the top-level grouping_config block switches it
// into v3 mode (see AlertRouteResourceModel.IsV3Mode). In v3 the API:
//   - moves grouping out of incident_config into a dedicated grouping_config;
//   - collapses channel_config and the top-level message_template into
//     message_config;
//   - adds an optional when_alert_joins_group block to escalation_config;
//   - nests the incident template under incident_config.template; and
//   - drops the incident template workspace binding.
//
// The shared structs (AlertRouteResourceModel, AlertRouteEscalationConfigModel,
// AlertRouteIncidentConfigModel) are defined in alert_route_v1_model.go; the v3
// mapping below reads/writes the v3-only fields on those structs.

type AlertRouteWhenAlertJoinsGroupModel struct {
	Mode               types.String `tfsdk:"mode"`
	GracePeriodSeconds types.Int64  `tfsdk:"grace_period_seconds"`
}

func WhenAlertJoinsGroupAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"mode":                 types.StringType,
		"grace_period_seconds": types.Int64Type,
	}
}

// whenAlertJoinsGroupFromAPI converts the API's optional when_alert_joins_group
// to a types.Object (null when absent). Modelled as an object, rather than a
// nested struct, so the Computed attribute can carry an unknown value.
func whenAlertJoinsGroupFromAPI(in *client.AlertRouteWhenAlertJoinsGroupV3) types.Object {
	if in == nil {
		return types.ObjectNull(WhenAlertJoinsGroupAttrTypes())
	}

	gracePeriodSeconds := types.Int64Null()
	if in.GracePeriodSeconds != nil {
		gracePeriodSeconds = types.Int64Value(int64(*in.GracePeriodSeconds))
	}

	obj, _ := types.ObjectValue(WhenAlertJoinsGroupAttrTypes(), map[string]attr.Value{
		"mode":                 types.StringValue(string(in.Mode)),
		"grace_period_seconds": gracePeriodSeconds,
	})
	return obj
}

func whenAlertJoinsGroupToPayload(ctx context.Context, obj types.Object) *client.AlertRouteWhenAlertJoinsGroupPayloadV3 {
	if obj.IsNull() || obj.IsUnknown() {
		return nil
	}

	var m AlertRouteWhenAlertJoinsGroupModel
	obj.As(ctx, &m, basetypes.ObjectAsOptions{})

	payload := &client.AlertRouteWhenAlertJoinsGroupPayloadV3{
		Mode: client.AlertRouteWhenAlertJoinsGroupPayloadV3Mode(m.Mode.ValueString()),
	}
	// The grace period only applies when re-escalating on each new alert; the API
	// rejects it for on_priority_increase. ValidateConfig surfaces a misconfigured
	// HCL value at plan time, but guard here too so a value that slips through
	// (e.g. unknown at validation) is never sent to the API.
	if m.Mode.ValueString() == string(client.AlertRouteWhenAlertJoinsGroupPayloadV3ModeOnEachNewAlert) &&
		!m.GracePeriodSeconds.IsNull() && !m.GracePeriodSeconds.IsUnknown() {
		payload.GracePeriodSeconds = lo32(m.GracePeriodSeconds.ValueInt64())
	}
	return payload
}

type AlertRouteV3GroupingConfigModel struct {
	Default *AlertRouteV3GroupingSettingsModel `tfsdk:"default"`
}

type AlertRouteV3GroupingSettingsModel struct {
	Enabled       types.Bool              `tfsdk:"enabled"`
	GroupingKeys  []AlertRouteGroupingKey `tfsdk:"grouping_keys"`
	WindowSeconds types.Int64             `tfsdk:"window_seconds"`
	WindowType    types.String            `tfsdk:"window_type"`
}

type AlertRouteV3MessageConfigModel struct {
	Destinations []AlertRouteChannelConfigModel `tfsdk:"destinations"`
	// Template is the v3 message template. Note the v3 API renamed this field
	// from message_template to template (the v2 top-level message_template is a
	// separate, deprecated attribute).
	Template *IncidentEngineParamBinding `tfsdk:"template"`
}

// AlertRouteV3IncidentTemplateModel mirrors the v2 incident template but drops
// the workspace binding, which the v3 API no longer accepts.
type AlertRouteV3IncidentTemplateModel struct {
	CustomFields  []AlertRouteCustomFieldModel         `tfsdk:"custom_fields"`
	IncidentMode  *IncidentEngineParamBinding          `tfsdk:"incident_mode"`
	IncidentType  *IncidentEngineParamBinding          `tfsdk:"incident_type"`
	Name          *AlertRouteAutoGeneratedParamBinding `tfsdk:"name"`
	Severity      types.Object                         `tfsdk:"severity"`
	StartInTriage *IncidentEngineParamBinding          `tfsdk:"start_in_triage"`
	Summary       *AlertRouteAutoGeneratedParamBinding `tfsdk:"summary"`
}

// convertEngineType bridges between the structurally-identical v2 and v3
// incident-engine API types. The shared engine model logic in engine.go is
// written against the v2 client types; rather than duplicate the recursive
// condition/expression/param-binding conversion code for v3, we round-trip
// through JSON, which is safe because both versions share the same JSON field
// names (the only difference is a response-only `label` field on v2 param
// binding values, which the model never reads).
func convertEngineType[Out any](in any) Out {
	var out Out
	raw, err := json.Marshal(in)
	if err == nil {
		_ = json.Unmarshal(raw, &out)
	}
	return out
}

func conditionGroupsFromV3(groups []client.ConditionGroupV3) IncidentEngineConditionGroups {
	return IncidentEngineConditionGroups{}.FromAPI(convertEngineType[[]client.ConditionGroupV2](groups))
}

func conditionGroupsToV3Payload(groups IncidentEngineConditionGroups) []client.ConditionGroupPayloadV3 {
	return convertEngineType[[]client.ConditionGroupPayloadV3](groups.ToPayload())
}

func paramBindingFromV3(pb client.EngineParamBindingV3) IncidentEngineParamBinding {
	return IncidentEngineParamBinding{}.FromAPI(convertEngineType[client.EngineParamBindingV2](pb))
}

func paramBindingToV3Payload(binding IncidentEngineParamBinding) client.EngineParamBindingPayloadV3 {
	return convertEngineType[client.EngineParamBindingPayloadV3](binding.ToPayload())
}

func expressionsFromV3(expressions []client.ExpressionV3) IncidentEngineExpressions {
	return IncidentEngineExpressions{}.FromAPI(convertEngineType[[]client.ExpressionV2](expressions))
}

func expressionsToV3Payload(expressions IncidentEngineExpressions) []client.ExpressionPayloadV3 {
	return convertEngineType[[]client.ExpressionPayloadV3](expressions.ToPayload())
}

// severityFromAPIV3 reuses the v2 severity reconciliation logic by converting
// the v3 severity binding (structurally identical) to its v2 form.
func severityFromAPIV3(severity *client.AlertRouteSeverityBindingV3) types.Object {
	if severity == nil {
		return SeverityObjectNull()
	}

	return SeverityFromAPI(convertEngineType[*client.AlertRouteSeverityBindingV2](severity))
}

func severityToPayloadV3(ctx context.Context, severityObj types.Object) *client.AlertRouteSeverityBindingPayloadV3 {
	v2 := SeverityToPayload(ctx, severityObj)
	if v2 == nil {
		return nil
	}

	return convertEngineType[*client.AlertRouteSeverityBindingPayloadV3](v2)
}

func createAutoGeneratedBindingV3(binding *IncidentEngineParamBinding, autogenerated types.Bool) client.AlertRouteAutoGeneratedTemplateBindingPayloadV3 {
	return convertEngineType[client.AlertRouteAutoGeneratedTemplateBindingPayloadV3](createAutoGeneratedBinding(binding, autogenerated))
}

func (AlertRouteResourceModel) FromAPIV3(apiModel client.AlertRouteV3) AlertRouteResourceModel {
	return AlertRouteResourceModel{}.FromAPIV3WithPlan(apiModel, nil)
}

func (AlertRouteResourceModel) FromAPIV3WithPlan(apiModel client.AlertRouteV3, plan *AlertRouteResourceModel) AlertRouteResourceModel {
	result := AlertRouteResourceModel{}

	result.ID = types.StringValue(apiModel.Id)
	result.Name = types.StringValue(apiModel.Name)
	result.Enabled = types.BoolValue(apiModel.Enabled)
	result.IsPrivate = types.BoolValue(apiModel.IsPrivate)

	result.OwningTeamIDs = types.SetNull(types.StringType)
	if apiModel.OwningTeamIds != nil {
		teamIDValues := []attr.Value{}
		for _, teamID := range *apiModel.OwningTeamIds {
			teamIDValues = append(teamIDValues, types.StringValue(teamID))
		}

		result.OwningTeamIDs, _ = types.SetValue(types.StringType, teamIDValues)
	}

	result.AlertSources = []AlertRouteAlertSourceModel{}
	for _, alertSource := range apiModel.AlertSources {
		model := AlertRouteAlertSourceModel{
			AlertSourceID:   types.StringValue(alertSource.AlertSourceId),
			ConditionGroups: conditionGroupsFromV3(alertSource.ConditionGroups),
		}

		result.AlertSources = append(result.AlertSources, model)
	}

	result.ConditionGroups = conditionGroupsFromV3(apiModel.ConditionGroups)

	result.Expressions = IncidentEngineExpressions{}
	if len(apiModel.Expressions) > 0 {
		result.Expressions = expressionsFromV3(apiModel.Expressions)
	}

	// Escalation config. when_alert_joins_group is optional (the API only returns
	// it when grouping is enabled); auto_cancel_escalations and escalation_targets
	// are always present.
	result.EscalationConfig = &AlertRouteEscalationConfigModel{
		AutoCancelEscalations: types.BoolValue(apiModel.EscalationConfig.AutoCancelEscalations),
		EscalationTargets:     []AlertRouteEscalationTargetModel{},
		WhenAlertJoinsGroup:   whenAlertJoinsGroupFromAPI(apiModel.EscalationConfig.WhenAlertJoinsGroup),
	}
	for _, target := range apiModel.EscalationConfig.EscalationTargets {
		model := AlertRouteEscalationTargetModel{}

		// A target is either an escalation-path binding or a user binding, never
		// both (enforced server-side). For escalation-path targets the API echoes
		// the same binding back in `users` too, for legacy frontend compatibility
		// (pending ONC-5335). We must not surface that duplicate as a configured
		// `users` value: escalation_targets is a set, so a read-back element with a
		// non-null `users` fails to correlate with the planned element
		// (users = null), producing "Provider produced inconsistent result after
		// apply". Prefer escalation_paths and only fall back to users when absent.
		switch {
		case target.EscalationPaths != nil:
			binding := paramBindingFromV3(*target.EscalationPaths)
			model.EscalationPaths = &binding
		case target.Users != nil:
			binding := paramBindingFromV3(*target.Users)
			model.Users = &binding
		}

		result.EscalationConfig.EscalationTargets = append(result.EscalationConfig.EscalationTargets, model)
	}

	// Grouping config. The detail fields (grouping_keys, window_seconds,
	// window_type) are optional in the API and only returned when grouping is
	// enabled. Mirror the API: use the returned value, otherwise leave the field
	// null. We deliberately do NOT fall back to prior plan/state when grouping is
	// disabled, so disabling it (including out-of-band) clears these rather than
	// leaving stale values that conflict with ValidateConfig.
	var planGrouping *AlertRouteV3GroupingSettingsModel
	if plan != nil && plan.GroupingConfig != nil {
		planGrouping = plan.GroupingConfig.Default
	}
	groupingDefault := &AlertRouteV3GroupingSettingsModel{
		Enabled:       types.BoolValue(apiModel.GroupingConfig.Default.Enabled),
		WindowSeconds: types.Int64Null(),
		WindowType:    types.StringNull(),
	}
	if apiModel.GroupingConfig.Default.WindowSeconds != nil {
		groupingDefault.WindowSeconds = types.Int64Value(int64(*apiModel.GroupingConfig.Default.WindowSeconds))
	}
	if apiModel.GroupingConfig.Default.WindowType != nil {
		groupingDefault.WindowType = types.StringValue(string(*apiModel.GroupingConfig.Default.WindowType))
	}
	switch {
	case apiModel.GroupingConfig.Default.GroupingKeys != nil:
		groupingDefault.GroupingKeys = []AlertRouteGroupingKey{}
		for _, gk := range *apiModel.GroupingConfig.Default.GroupingKeys {
			groupingDefault.GroupingKeys = append(groupingDefault.GroupingKeys, AlertRouteGroupingKey{
				Reference: types.StringValue(gk.Reference),
			})
		}
	case apiModel.GroupingConfig.Default.Enabled && planGrouping != nil:
		// The API omits an empty grouping_keys (omitempty) even when grouping is
		// enabled, so mirror the planned null-vs-empty shape to avoid a diff.
		// When grouping is disabled we leave it null (no stale values).
		groupingDefault.GroupingKeys = planGrouping.GroupingKeys
	}
	result.GroupingConfig = &AlertRouteV3GroupingConfigModel{Default: groupingDefault}

	// Message config. Leave Destinations nil (rather than an empty slice) when the
	// API returns none, so an omitted optional `destinations` stays null and
	// doesn't produce drift (reconciled against the plan below).
	result.MessageConfig = &AlertRouteV3MessageConfigModel{}
	for _, destination := range apiModel.MessageConfig.Destinations {
		model := AlertRouteChannelConfigModel{
			ConditionGroups: conditionGroupsFromV3(destination.ConditionGroups),
		}

		if destination.SlackTargets != nil {
			binding := paramBindingFromV3(destination.SlackTargets.Binding)
			model.SlackTargets = &AlertRouteChannelTargetModel{
				ChannelVisibility: types.StringValue(destination.SlackTargets.ChannelVisibility),
				Binding:           &binding,
			}
		}

		if destination.MsTeamsTargets != nil {
			binding := paramBindingFromV3(destination.MsTeamsTargets.Binding)
			model.MsTeamsTargets = &AlertRouteChannelTargetModel{
				ChannelVisibility: types.StringValue(destination.MsTeamsTargets.ChannelVisibility),
				Binding:           &binding,
			}
		}

		result.MessageConfig.Destinations = append(result.MessageConfig.Destinations, model)
	}

	if apiModel.MessageConfig.Template != nil {
		binding := paramBindingFromV3(*apiModel.MessageConfig.Template)
		result.MessageConfig.Template = &binding
	}

	// Mirror the planned shape of the optional `destinations` set. The API
	// returns no destinations both when the user omitted the attribute (null)
	// and when they set it to an explicit empty list ([]). To avoid perpetual
	// diffs on refresh, only normalise to a non-nil empty slice when the plan
	// carried a non-nil (explicit, possibly empty) destinations slice;
	// otherwise leave it nil so an omitted optional stays null.
	if len(result.MessageConfig.Destinations) == 0 &&
		plan != nil && plan.MessageConfig != nil && plan.MessageConfig.Destinations != nil {
		result.MessageConfig.Destinations = []AlertRouteChannelConfigModel{}
	}

	// Incident config. auto_decline_enabled and condition_groups are optional in
	// the API and only populated when incident creation is enabled. Mirror the
	// API: use the returned value, otherwise leave it null. As with grouping, we
	// don't fall back to prior plan/state, so disabling incident creation clears
	// auto_decline_enabled rather than retaining a stale value. The v2-only
	// fields (grouping_keys, grouping_window_seconds, defer_time_seconds,
	// auto_relate_grouped_alerts) stay null in v3 mode.
	var incidentConditionGroups []client.ConditionGroupV3
	if apiModel.IncidentConfig.ConditionGroups != nil {
		incidentConditionGroups = *apiModel.IncidentConfig.ConditionGroups
	}
	result.IncidentConfig = &AlertRouteIncidentConfigModel{
		AutoDeclineEnabled:      types.BoolNull(),
		AutoRelateGroupedAlerts: types.BoolNull(),
		ConditionGroups:         conditionGroupsFromV3(incidentConditionGroups),
		DeferTimeSeconds:        types.Int64Null(),
		Enabled:                 types.BoolValue(apiModel.IncidentConfig.Enabled),
		GroupingWindowSeconds:   types.Int64Null(),
	}
	if apiModel.IncidentConfig.AutoDeclineEnabled != nil {
		result.IncidentConfig.AutoDeclineEnabled = types.BoolValue(*apiModel.IncidentConfig.AutoDeclineEnabled)
	}

	var planTemplate *AlertRouteV3IncidentTemplateModel
	if plan != nil && plan.IncidentConfig != nil {
		planTemplate = plan.IncidentConfig.Template
	}

	// The API only returns a template when incident creation is enabled. Mirror
	// it: populate the template from the response when present, otherwise leave
	// it null. We don't fall back to the prior plan/state, so disabling incident
	// creation (including out-of-band) clears the template rather than leaving a
	// stale one in state.
	if apiModel.IncidentConfig.Template != nil {
		result.IncidentConfig.Template = incidentTemplateFromAPIV3(apiModel.IncidentConfig.Template, planTemplate)
	}

	return result
}

func incidentTemplateFromAPIV3(apiTemplate *client.AlertRouteIncidentTemplateV3, plan *AlertRouteV3IncidentTemplateModel) *AlertRouteV3IncidentTemplateModel {
	template := &AlertRouteV3IncidentTemplateModel{}

	emptyListType := types.ObjectType{
		AttrTypes: ParamBindingValueAttrTypes(),
	}

	// Name (auto-generatable, plan-aware).
	var planNameBinding *AlertRouteAutoGeneratedParamBinding
	if plan != nil {
		planNameBinding = plan.Name
	}

	nameBinding := AlertRouteAutoGeneratedParamBinding{
		Autogenerated: types.BoolValue(apiTemplate.Name.Autogenerated),
		ArrayValue:    types.ListNull(emptyListType),
	}
	if apiTemplate.Name.Binding != nil {
		paramBinding := paramBindingFromV3(*apiTemplate.Name.Binding)
		nameBinding = AlertRouteAutoGeneratedParamBinding{}.FromParamBindingWithPlan(paramBinding, nameBinding.Autogenerated, planNameBinding)
	} else if planNameBinding != nil {
		nameBinding = AlertRouteAutoGeneratedParamBinding{}.FromParamBindingWithPlan(IncidentEngineParamBinding{}, nameBinding.Autogenerated, planNameBinding)
	}
	template.Name = &nameBinding

	// Summary (auto-generatable, plan-aware).
	var planSummaryBinding *AlertRouteAutoGeneratedParamBinding
	if plan != nil {
		planSummaryBinding = plan.Summary
	}

	summaryBinding := AlertRouteAutoGeneratedParamBinding{
		Autogenerated: types.BoolValue(false),
		ArrayValue:    types.ListNull(emptyListType),
	}
	if apiTemplate.Summary != nil {
		summaryBinding.Autogenerated = types.BoolValue(apiTemplate.Summary.Autogenerated)

		if apiTemplate.Summary.Binding != nil {
			paramBinding := paramBindingFromV3(*apiTemplate.Summary.Binding)
			summaryBinding = AlertRouteAutoGeneratedParamBinding{}.FromParamBindingWithPlan(paramBinding, summaryBinding.Autogenerated, planSummaryBinding)
		} else if planSummaryBinding != nil {
			summaryBinding = AlertRouteAutoGeneratedParamBinding{}.FromParamBindingWithPlan(IncidentEngineParamBinding{}, summaryBinding.Autogenerated, planSummaryBinding)
		}
	} else if planSummaryBinding != nil {
		summaryBinding = AlertRouteAutoGeneratedParamBinding{}.FromParamBindingWithPlan(IncidentEngineParamBinding{}, summaryBinding.Autogenerated, planSummaryBinding)
	}
	template.Summary = &summaryBinding

	template.Severity = severityFromAPIV3(apiTemplate.Severity)

	if apiTemplate.IncidentMode != nil && apiTemplate.IncidentMode.Binding != nil {
		binding := paramBindingFromV3(*apiTemplate.IncidentMode.Binding)
		template.IncidentMode = &binding
	}

	if apiTemplate.IncidentType != nil && apiTemplate.IncidentType.Binding != nil {
		binding := paramBindingFromV3(*apiTemplate.IncidentType.Binding)
		template.IncidentType = &binding
	}

	if apiTemplate.StartInTriage != nil && apiTemplate.StartInTriage.Binding != nil {
		binding := paramBindingFromV3(*apiTemplate.StartInTriage.Binding)
		template.StartInTriage = &binding
	}

	// Custom fields: only populate when the API returns them or the plan has
	// them, otherwise leave nil to preserve null state in Terraform.
	if apiTemplate.CustomFields != nil && len(*apiTemplate.CustomFields) > 0 {
		template.CustomFields = []AlertRouteCustomFieldModel{}
		for _, cf := range *apiTemplate.CustomFields {
			model := AlertRouteCustomFieldModel{
				CustomFieldID: types.StringValue(cf.CustomFieldId),
				MergeStrategy: types.StringValue(string(cf.MergeStrategy)),
			}

			binding := paramBindingFromV3(cf.Binding)
			if binding.Value != nil && binding.Value.Reference.IsNull() {
				binding.Value.Reference = types.StringNull()
			}
			model.Binding = &binding

			template.CustomFields = append(template.CustomFields, model)
		}
	} else if plan != nil && len(plan.CustomFields) > 0 {
		template.CustomFields = []AlertRouteCustomFieldModel{}
		for _, cf := range plan.CustomFields {
			model := AlertRouteCustomFieldModel{
				CustomFieldID: cf.CustomFieldID,
				MergeStrategy: cf.MergeStrategy,
			}
			if cf.Binding != nil {
				bindingCopy := *cf.Binding
				model.Binding = &bindingCopy
			}
			template.CustomFields = append(template.CustomFields, model)
		}
	}

	// Mirror the planned shape of the optional `custom_fields` set: the API
	// returns none both when the attribute is omitted (null) and when it's an
	// explicit empty list ([]). Only normalise to a non-nil empty slice when the
	// plan carried a non-nil (explicit, possibly empty) slice; otherwise leave it
	// nil so an omitted optional stays null and doesn't produce drift.
	if len(template.CustomFields) == 0 && plan != nil && plan.CustomFields != nil {
		template.CustomFields = []AlertRouteCustomFieldModel{}
	}

	return template
}

func (m AlertRouteResourceModel) ToCreatePayloadV3() client.AlertRoutesCreatePayloadV3 {
	var owningTeamIDs *[]string
	if !m.OwningTeamIDs.IsNull() {
		teamIDs := []string{}
		for _, elem := range m.OwningTeamIDs.Elements() {
			if str, ok := elem.(types.String); ok {
				teamIDs = append(teamIDs, str.ValueString())
			}
		}

		owningTeamIDs = &teamIDs
	}

	payload := client.AlertRoutesCreatePayloadV3{
		Name:            m.Name.ValueString(),
		Enabled:         m.Enabled.ValueBool(),
		IsPrivate:       m.IsPrivate.ValueBool(),
		AlertSources:    []client.AlertRouteAlertSourcePayloadV3{},
		ConditionGroups: []client.ConditionGroupPayloadV3{},
		Expressions:     []client.ExpressionPayloadV3{},
		EscalationConfig: client.AlertRouteEscalationConfigPayloadV3{
			AutoCancelEscalations: false,
			EscalationTargets:     []client.AlertRouteEscalationTargetPayloadV3{},
		},
		IncidentConfig: client.AlertRouteIncidentConfigPayloadV3{
			AutoDeclineEnabled: lo.ToPtr(false),
			ConditionGroups:    &[]client.ConditionGroupPayloadV3{},
		},
		GroupingConfig: client.AlertGroupingConfigV3{
			Default: client.GroupingSettingsV3{
				GroupingKeys: &[]client.GroupingKeyV3{},
			},
		},
		MessageConfig: client.AlertMessageConfigPayloadV3{
			Destinations: []client.AlertMessageDestinationPayloadV3{},
		},
		OwningTeamIds: owningTeamIDs,
	}

	alertSources := []client.AlertRouteAlertSourcePayloadV3{}
	for _, src := range m.AlertSources {
		alertSources = append(alertSources, client.AlertRouteAlertSourcePayloadV3{
			AlertSourceId:   src.AlertSourceID.ValueString(),
			ConditionGroups: conditionGroupsToV3Payload(src.ConditionGroups),
		})
	}
	payload.AlertSources = alertSources

	payload.ConditionGroups = conditionGroupsToV3Payload(m.ConditionGroups)

	if len(m.Expressions) > 0 {
		payload.Expressions = expressionsToV3Payload(m.Expressions)
	}

	if m.EscalationConfig != nil {
		payload.EscalationConfig = client.AlertRouteEscalationConfigPayloadV3{
			AutoCancelEscalations: m.EscalationConfig.AutoCancelEscalations.ValueBool(),
			EscalationTargets:     []client.AlertRouteEscalationTargetPayloadV3{},
		}

		for _, target := range m.EscalationConfig.EscalationTargets {
			escalationTarget := client.AlertRouteEscalationTargetPayloadV3{}
			if target.Users != nil {
				userBinding := paramBindingToV3Payload(*target.Users)
				escalationTarget.Users = &userBinding
			}
			if target.EscalationPaths != nil {
				pathBinding := paramBindingToV3Payload(*target.EscalationPaths)
				escalationTarget.EscalationPaths = &pathBinding
			}
			payload.EscalationConfig.EscalationTargets = append(payload.EscalationConfig.EscalationTargets, escalationTarget)
		}

		// when_alert_joins_group is optional; whenAlertJoinsGroupToPayload returns
		// nil when unset.
		payload.EscalationConfig.WhenAlertJoinsGroup = whenAlertJoinsGroupToPayload(context.Background(), m.EscalationConfig.WhenAlertJoinsGroup)
	}

	if m.GroupingConfig != nil && m.GroupingConfig.Default != nil {
		groupingDefault := client.GroupingSettingsV3{
			Enabled: m.GroupingConfig.Default.Enabled.ValueBool(),
		}
		// The detail fields are only valid when grouping is enabled; the API
		// rejects them otherwise.
		if m.GroupingConfig.Default.Enabled.ValueBool() {
			groupKeys := []client.GroupingKeyV3{}
			for _, gk := range m.GroupingConfig.Default.GroupingKeys {
				groupKeys = append(groupKeys, client.GroupingKeyV3{
					Reference: gk.Reference.ValueString(),
				})
			}
			groupingDefault.GroupingKeys = &groupKeys
			if !m.GroupingConfig.Default.WindowSeconds.IsNull() {
				groupingDefault.WindowSeconds = lo32(m.GroupingConfig.Default.WindowSeconds.ValueInt64())
			}
			if !m.GroupingConfig.Default.WindowType.IsNull() {
				groupingDefault.WindowType = lo.ToPtr(client.GroupingSettingsV3WindowType(m.GroupingConfig.Default.WindowType.ValueString()))
			}
		}
		payload.GroupingConfig = client.AlertGroupingConfigV3{Default: groupingDefault}
	}

	if m.MessageConfig != nil {
		destinations := []client.AlertMessageDestinationPayloadV3{}
		for _, destination := range m.MessageConfig.Destinations {
			payloadDestination := client.AlertMessageDestinationPayloadV3{
				ConditionGroups: conditionGroupsToV3Payload(destination.ConditionGroups),
			}

			if destination.SlackTargets != nil && destination.SlackTargets.Binding != nil {
				payloadDestination.SlackTargets = &client.AlertRouteChannelTargetPayloadV3{
					ChannelVisibility: client.AlertRouteChannelTargetPayloadV3ChannelVisibility(destination.SlackTargets.ChannelVisibility.ValueString()),
					Binding:           paramBindingToV3Payload(*destination.SlackTargets.Binding),
				}
			}

			if destination.MsTeamsTargets != nil && destination.MsTeamsTargets.Binding != nil {
				payloadDestination.MsTeamsTargets = &client.AlertRouteChannelTargetPayloadV3{
					ChannelVisibility: client.AlertRouteChannelTargetPayloadV3ChannelVisibility(destination.MsTeamsTargets.ChannelVisibility.ValueString()),
					Binding:           paramBindingToV3Payload(*destination.MsTeamsTargets.Binding),
				}
			}

			destinations = append(destinations, payloadDestination)
		}

		payload.MessageConfig = client.AlertMessageConfigPayloadV3{
			Destinations: destinations,
		}

		if m.MessageConfig.Template != nil {
			templateBinding := paramBindingToV3Payload(*m.MessageConfig.Template)
			payload.MessageConfig.Template = &templateBinding
		}
	}

	if m.IncidentConfig != nil {
		payload.IncidentConfig = client.AlertRouteIncidentConfigPayloadV3{
			Enabled: m.IncidentConfig.Enabled.ValueBool(),
		}
		// auto_decline_enabled, condition_groups and template only apply when
		// incident creation is enabled; the API drops them otherwise, so we omit
		// them rather than send a value that won't round-trip.
		if m.IncidentConfig.Enabled.ValueBool() {
			payload.IncidentConfig.AutoDeclineEnabled = lo.ToPtr(m.IncidentConfig.AutoDeclineEnabled.ValueBool())
			payload.IncidentConfig.ConditionGroups = lo.ToPtr(conditionGroupsToV3Payload(m.IncidentConfig.ConditionGroups))
			if m.IncidentConfig.Template != nil {
				payload.IncidentConfig.Template = m.IncidentConfig.Template.ToPayload()
			}
		}
	}

	return payload
}

func (t AlertRouteV3IncidentTemplateModel) ToPayload() *client.AlertRouteIncidentTemplatePayloadV3 {
	template := &client.AlertRouteIncidentTemplatePayloadV3{}

	if t.Name != nil {
		nameParamBinding := t.Name.ToParamBinding()
		template.Name = createAutoGeneratedBindingV3(&nameParamBinding, t.Name.Autogenerated)
	}

	if t.Summary != nil {
		summaryParamBinding := t.Summary.ToParamBinding()
		summaryPayload := createAutoGeneratedBindingV3(&summaryParamBinding, t.Summary.Autogenerated)
		template.Summary = &summaryPayload
	} else {
		emptyBinding := createAutoGeneratedBindingV3(nil, types.BoolValue(false))
		template.Summary = &emptyBinding
	}

	if t.IncidentMode != nil {
		binding := paramBindingToV3Payload(*t.IncidentMode)
		template.IncidentMode = &client.AlertRouteTemplateBindingPayloadV3{Binding: &binding}
	}

	if t.IncidentType != nil {
		binding := paramBindingToV3Payload(*t.IncidentType)
		template.IncidentType = &client.AlertRouteTemplateBindingPayloadV3{Binding: &binding}
	}

	if t.StartInTriage != nil {
		binding := paramBindingToV3Payload(*t.StartInTriage)
		template.StartInTriage = &client.AlertRouteTemplateBindingPayloadV3{Binding: &binding}
	}

	template.Severity = severityToPayloadV3(context.Background(), t.Severity)

	customFields := []client.AlertRouteCustomFieldBindingPayloadV3{}
	for _, cf := range t.CustomFields {
		if cf.Binding == nil {
			continue
		}

		customFields = append(customFields, client.AlertRouteCustomFieldBindingPayloadV3{
			CustomFieldId: cf.CustomFieldID.ValueString(),
			Binding:       paramBindingToV3Payload(*cf.Binding),
			MergeStrategy: client.AlertRouteCustomFieldBindingPayloadV3MergeStrategy(cf.MergeStrategy.ValueString()),
		})
	}
	template.CustomFields = &customFields

	return template
}

func (m AlertRouteResourceModel) ToUpdatePayloadV3() client.AlertRoutesUpdatePayloadV3 {
	createPayload := m.ToCreatePayloadV3()

	return client.AlertRoutesUpdatePayloadV3{
		Name:             createPayload.Name,
		Enabled:          createPayload.Enabled,
		IsPrivate:        createPayload.IsPrivate,
		AlertSources:     createPayload.AlertSources,
		ConditionGroups:  createPayload.ConditionGroups,
		Expressions:      createPayload.Expressions,
		EscalationConfig: createPayload.EscalationConfig,
		IncidentConfig:   createPayload.IncidentConfig,
		GroupingConfig:   createPayload.GroupingConfig,
		MessageConfig:    createPayload.MessageConfig,
		OwningTeamIds:    createPayload.OwningTeamIds,
	}
}

// lo32 returns a pointer to the int32 representation of the given int64.
func lo32(v int64) *int32 {
	out := int32(v)
	return &out
}
