package models

import (
	"context"
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/samber/lo"

	"github.com/incident-io/terraform-provider-incident/internal/client"
)

// TestAlertRouteV3RoundTrip exercises the FromAPIV3 -> ToCreatePayloadV3 path,
// including the JSON-bridged v3<->v2 engine type conversion, to confirm the
// restructured v3 fields (grouping_config, message_config,
// when_alert_joins_group, incident_config.template) survive a round trip.
func TestAlertRouteV3RoundTrip(t *testing.T) {
	api := client.AlertRouteV3{
		Id:        "01ABC",
		Name:      "route",
		Enabled:   true,
		IsPrivate: false,
		Version:   3,
		AlertSources: []client.AlertRouteAlertSourceV3{
			{
				AlertSourceId: "01SRC",
				ConditionGroups: []client.ConditionGroupV3{
					{
						Conditions: []client.ConditionV3{
							{
								Subject:       client.ConditionSubjectV3{Reference: "alert.title"},
								Operation:     client.ConditionOperationV3{Value: "is_set"},
								ParamBindings: []client.EngineParamBindingV3{},
							},
						},
					},
				},
			},
		},
		ConditionGroups: []client.ConditionGroupV3{},
		Expressions:     []client.ExpressionV3{},
		GroupingConfig: client.AlertGroupingConfigV3{
			Default: client.GroupingSettingsV3{
				Enabled:       true,
				GroupingKeys:  &[]client.GroupingKeyV3{{Reference: "alert.title"}},
				WindowSeconds: lo.ToPtr(int32(1800)),
				WindowType:    lo.ToPtr(client.Fixed),
			},
		},
		MessageConfig: client.AlertMessageConfigV3{
			Destinations: []client.AlertMessageDestinationV3{
				{
					ConditionGroups: []client.ConditionGroupV3{},
					SlackTargets: &client.AlertRouteChannelTargetV3{
						ChannelVisibility:  "public",
						GroupAlertsSummary: lo.ToPtr(true),
						Binding: client.EngineParamBindingV3{
							Value: &client.EngineParamBindingValueV3{Literal: lo.ToPtr("C123")},
						},
					},
				},
			},
		},
		EscalationConfig: client.AlertRouteEscalationConfigV3{
			AutoCancelEscalations: true,
			EscalationTargets:     []client.AlertRouteEscalationTargetV3{},
			WhenAlertJoinsGroup: &client.AlertRouteWhenAlertJoinsGroupV3{
				Mode:               client.AlertRouteWhenAlertJoinsGroupV3ModeOnEachNewAlert,
				GracePeriodSeconds: lo.ToPtr(int32(60)),
			},
		},
		IncidentConfig: client.AlertRouteIncidentConfigV3{
			AutoDeclineEnabled: lo.ToPtr(false),
			Enabled:            true,
			ConditionGroups:    &[]client.ConditionGroupV3{},
			Template: &client.AlertRouteIncidentTemplateV3{
				Name: client.AlertRouteAutoGeneratedTemplateBindingV3{
					Autogenerated: true,
					Binding: &client.EngineParamBindingV3{
						Value: &client.EngineParamBindingValueV3{Literal: lo.ToPtr("title")},
					},
				},
				Summary: &client.AlertRouteAutoGeneratedTemplateBindingV3{
					Autogenerated: true,
					Binding: &client.EngineParamBindingV3{
						Value: &client.EngineParamBindingValueV3{Literal: lo.ToPtr("summary")},
					},
				},
				Severity: &client.AlertRouteSeverityBindingV3{
					MergeStrategy: client.AlertRouteSeverityBindingV3MergeStrategyFirstWins,
				},
				CustomFields: &[]client.AlertRouteCustomFieldBindingV3{
					{
						CustomFieldId: "01CF",
						MergeStrategy: client.AlertRouteCustomFieldBindingV3MergeStrategyFirstWins,
						Binding: client.EngineParamBindingV3{
							Value: &client.EngineParamBindingValueV3{Literal: lo.ToPtr("Test incident")},
						},
					},
				},
			},
		},
	}

	model := AlertRouteResourceModel{}.FromAPIV3(api)

	// Mode detection: grouping_config is set, so this is a v3-mode model.
	if !model.IsV3Mode() {
		t.Error("expected IsV3Mode to be true")
	}

	// Top-level.
	if got := model.Name.ValueString(); got != "route" {
		t.Errorf("name: got %q", got)
	}

	// Grouping config.
	if model.GroupingConfig == nil || model.GroupingConfig.Default == nil {
		t.Fatal("grouping_config.default is nil")
	}
	if !model.GroupingConfig.Default.Enabled.ValueBool() {
		t.Error("grouping enabled should be true")
	}
	if got := model.GroupingConfig.Default.WindowType.ValueString(); got != "fixed" {
		t.Errorf("window_type: got %q", got)
	}
	if got := len(model.GroupingConfig.Default.GroupingKeys); got != 1 {
		t.Errorf("grouping_keys: got %d", got)
	}

	// Message config.
	if model.MessageConfig == nil || len(model.MessageConfig.Destinations) != 1 {
		t.Fatalf("message_config destinations: %+v", model.MessageConfig)
	}
	if model.MessageConfig.Destinations[0].SlackTargets == nil {
		t.Fatal("slack_targets is nil")
	}
	if !model.MessageConfig.Destinations[0].SlackTargets.GroupAlertsSummary.ValueBool() {
		t.Error("slack_targets.group_alerts_summary should be true")
	}

	// Escalation config.
	if !model.EscalationConfig.AutoCancelEscalations.ValueBool() {
		t.Error("auto_cancel_escalations should be true")
	}

	// when_alert_joins_group (modelled as a types.Object).
	if model.EscalationConfig.WhenAlertJoinsGroup.IsNull() {
		t.Fatal("when_alert_joins_group is null")
	}
	var joinsGroup AlertRouteWhenAlertJoinsGroupModel
	model.EscalationConfig.WhenAlertJoinsGroup.As(context.Background(), &joinsGroup, basetypes.ObjectAsOptions{})
	if got := joinsGroup.Mode.ValueString(); got != "on_each_new_alert" {
		t.Errorf("mode: got %q", got)
	}
	if got := joinsGroup.GracePeriodSeconds.ValueInt64(); got != 60 {
		t.Errorf("grace_period_seconds: got %d", got)
	}

	// Incident template (nested under incident_config).
	if model.IncidentConfig == nil || model.IncidentConfig.Template == nil {
		t.Fatal("incident_config.template is nil")
	}
	if !model.IncidentConfig.Template.Name.Autogenerated.ValueBool() {
		t.Error("template name should be autogenerated")
	}
	if got := len(model.IncidentConfig.Template.CustomFields); got != 1 {
		t.Errorf("custom_fields: got %d", got)
	}

	// Now convert back to a payload and check the engine-bridged fields survive.
	payload := model.ToCreatePayloadV3()

	if got := payload.GroupingConfig.Default.WindowType; got == nil || *got != client.Fixed {
		t.Errorf("payload window_type: got %v", got)
	}
	if len(payload.MessageConfig.Destinations) != 1 {
		t.Fatalf("payload destinations: %+v", payload.MessageConfig.Destinations)
	}
	slack := payload.MessageConfig.Destinations[0].SlackTargets
	if slack == nil || slack.Binding.Value == nil || lo.FromPtr(slack.Binding.Value.Literal) != "C123" {
		t.Errorf("payload slack binding literal mismatch: %+v", slack)
	}
	if !lo.FromPtr(slack.GroupAlertsSummary) {
		t.Errorf("payload slack group_alerts_summary should be true: %+v", slack)
	}
	if !payload.EscalationConfig.AutoCancelEscalations {
		t.Error("payload auto_cancel_escalations should be true")
	}
	if payload.EscalationConfig.WhenAlertJoinsGroup == nil {
		t.Fatal("payload when_alert_joins_group is nil")
	}
	if got := lo.FromPtr(payload.EscalationConfig.WhenAlertJoinsGroup.GracePeriodSeconds); got != 60 {
		t.Errorf("payload grace_period_seconds: got %d", got)
	}
	if payload.IncidentConfig.Template == nil {
		t.Fatal("payload incident template is nil")
	}
	if got := len(*payload.IncidentConfig.Template.CustomFields); got != 1 {
		t.Errorf("payload custom_fields: got %d", got)
	}
	cf := (*payload.IncidentConfig.Template.CustomFields)[0]
	if cf.Binding.Value == nil || lo.FromPtr(cf.Binding.Value.Literal) != "Test incident" {
		t.Errorf("payload custom field binding mismatch: %+v", cf.Binding)
	}
}

// TestAlertRouteV3MessageConfigDestinationsNullVsEmpty checks that
// FromAPIV3WithPlan mirrors the planned null-vs-empty shape of the optional
// message_config.destinations set. The API returns no destinations both when
// the attribute is omitted and when it's set to an explicit empty list, so the
// result must follow the plan to avoid perpetual diffs on refresh.
func TestAlertRouteV3MessageConfigDestinationsNullVsEmpty(t *testing.T) {
	// An apiModel that returns no destinations.
	api := client.AlertRouteV3{
		Id:              "01ABC",
		Name:            "route",
		ConditionGroups: []client.ConditionGroupV3{},
		Expressions:     []client.ExpressionV3{},
		GroupingConfig: client.AlertGroupingConfigV3{
			Default: client.GroupingSettingsV3{},
		},
		MessageConfig: client.AlertMessageConfigV3{
			Destinations: []client.AlertMessageDestinationV3{},
		},
		EscalationConfig: client.AlertRouteEscalationConfigV3{
			EscalationTargets: []client.AlertRouteEscalationTargetV3{},
		},
		IncidentConfig: client.AlertRouteIncidentConfigV3{},
	}

	// Plan with an explicit, non-nil empty destinations slice.
	planEmpty := &AlertRouteResourceModel{
		MessageConfig: &AlertRouteV3MessageConfigModel{
			Destinations: []AlertRouteV3ChannelConfigModel{},
		},
	}

	resultEmpty := AlertRouteResourceModel{}.FromAPIV3WithPlan(api, planEmpty)
	if resultEmpty.MessageConfig == nil {
		t.Fatal("message_config is nil")
	}
	if resultEmpty.MessageConfig.Destinations == nil {
		t.Error("destinations should be non-nil empty when plan set explicit empty slice")
	}
	if got := len(resultEmpty.MessageConfig.Destinations); got != 0 {
		t.Errorf("destinations: got %d, want 0", got)
	}

	// With no plan, the omitted optional should stay null (nil).
	resultNil := AlertRouteResourceModel{}.FromAPIV3WithPlan(api, nil)
	if resultNil.MessageConfig == nil {
		t.Fatal("message_config is nil")
	}
	if resultNil.MessageConfig.Destinations != nil {
		t.Errorf("destinations should be nil when plan is nil, got %+v", resultNil.MessageConfig.Destinations)
	}
}

// TestAlertRouteV3EscalationPathTargetIgnoresDuplicateUsers covers ONC-12476 for
// the v3 mapping: an escalation-path target has its binding echoed back in `users`
// too (legacy compat, pending ONC-5335). escalation_targets is a set, so surfacing
// that duplicate leaves the read-back element unable to correlate with the planned
// element (users = null). FromAPIV3 must keep only escalation_paths.
func TestAlertRouteV3EscalationPathTargetIgnoresDuplicateUsers(t *testing.T) {
	pathBinding := &client.EngineParamBindingV3{
		ArrayValue: &[]client.EngineParamBindingValueV3{
			{Literal: lo.ToPtr("01FAKEFAKEFAKEFAKEFAKEFAKE")},
		},
	}

	api := client.AlertRouteV3{
		Id:              "01ABC",
		Name:            "route",
		ConditionGroups: []client.ConditionGroupV3{},
		Expressions:     []client.ExpressionV3{},
		GroupingConfig: client.AlertGroupingConfigV3{
			Default: client.GroupingSettingsV3{Enabled: false},
		},
		MessageConfig: client.AlertMessageConfigV3{
			Destinations: []client.AlertMessageDestinationV3{},
		},
		EscalationConfig: client.AlertRouteEscalationConfigV3{
			EscalationTargets: []client.AlertRouteEscalationTargetV3{
				{EscalationPaths: pathBinding, Users: pathBinding},
			},
		},
		IncidentConfig: client.AlertRouteIncidentConfigV3{Enabled: false},
	}

	model := AlertRouteResourceModel{}.FromAPIV3(api)

	if got := len(model.EscalationConfig.EscalationTargets); got != 1 {
		t.Fatalf("escalation_targets: got %d, want 1", got)
	}
	target := model.EscalationConfig.EscalationTargets[0]
	if target.EscalationPaths == nil {
		t.Error("escalation_paths should be set")
	}
	if target.Users != nil {
		t.Error("users should be nil for an escalation-path target (API duplicate must be dropped)")
	}
}

// TestAlertRouteV3ImportLeavesConditionalFieldsNull simulates an import/read of a
// route with grouping and incident creation disabled: the API omits the
// conditional detail fields and there is no prior plan/state. Those fields are
// optional in the schema, so FromAPIV3 must leave them null rather than writing
// a zero value, which would break ImportStateVerify and cause plan churn.
func TestAlertRouteV3ImportLeavesConditionalFieldsNull(t *testing.T) {
	api := client.AlertRouteV3{
		Id:              "01ABC",
		Name:            "route",
		ConditionGroups: []client.ConditionGroupV3{},
		Expressions:     []client.ExpressionV3{},
		GroupingConfig: client.AlertGroupingConfigV3{
			Default: client.GroupingSettingsV3{Enabled: false},
		},
		MessageConfig: client.AlertMessageConfigV3{
			Destinations: []client.AlertMessageDestinationV3{},
		},
		EscalationConfig: client.AlertRouteEscalationConfigV3{
			EscalationTargets: []client.AlertRouteEscalationTargetV3{},
		},
		IncidentConfig: client.AlertRouteIncidentConfigV3{Enabled: false},
	}

	// FromAPIV3 passes a nil plan, exactly as the import path does.
	model := AlertRouteResourceModel{}.FromAPIV3(api)

	if model.GroupingConfig == nil || model.GroupingConfig.Default == nil {
		t.Fatal("grouping_config.default is nil")
	}
	if !model.GroupingConfig.Default.WindowSeconds.IsNull() {
		t.Errorf("window_seconds: expected null, got %v", model.GroupingConfig.Default.WindowSeconds)
	}
	if !model.GroupingConfig.Default.WindowType.IsNull() {
		t.Errorf("window_type: expected null, got %v", model.GroupingConfig.Default.WindowType)
	}
	if model.GroupingConfig.Default.GroupingKeys != nil {
		t.Errorf("grouping_keys: expected nil, got %+v", model.GroupingConfig.Default.GroupingKeys)
	}
	if model.IncidentConfig == nil {
		t.Fatal("incident_config is nil")
	}
	if !model.IncidentConfig.AutoDeclineEnabled.IsNull() {
		t.Errorf("auto_decline_enabled: expected null, got %v", model.IncidentConfig.AutoDeclineEnabled)
	}
	// v2-only incident fields must stay null in v3 mode.
	if !model.IncidentConfig.DeferTimeSeconds.IsNull() {
		t.Errorf("defer_time_seconds: expected null, got %v", model.IncidentConfig.DeferTimeSeconds)
	}
	if !model.IncidentConfig.GroupingWindowSeconds.IsNull() {
		t.Errorf("grouping_window_seconds: expected null, got %v", model.IncidentConfig.GroupingWindowSeconds)
	}
	if model.IncidentConfig.GroupingKeys != nil {
		t.Errorf("incident grouping_keys: expected nil, got %+v", model.IncidentConfig.GroupingKeys)
	}
}

// TestAlertRouteV3CustomFieldsNullVsEmpty checks that the optional
// incident_config.template.custom_fields set mirrors the planned null-vs-empty
// shape when the API returns no custom fields (which it does both when the
// attribute is omitted and when it's an explicit empty list).
func TestAlertRouteV3CustomFieldsNullVsEmpty(t *testing.T) {
	api := client.AlertRouteV3{
		Id:              "01ABC",
		Name:            "route",
		ConditionGroups: []client.ConditionGroupV3{},
		Expressions:     []client.ExpressionV3{},
		GroupingConfig: client.AlertGroupingConfigV3{
			Default: client.GroupingSettingsV3{Enabled: false},
		},
		MessageConfig: client.AlertMessageConfigV3{
			Destinations: []client.AlertMessageDestinationV3{},
		},
		EscalationConfig: client.AlertRouteEscalationConfigV3{
			EscalationTargets: []client.AlertRouteEscalationTargetV3{},
		},
		IncidentConfig: client.AlertRouteIncidentConfigV3{
			Enabled: true,
			Template: &client.AlertRouteIncidentTemplateV3{
				// The API returns no custom fields.
				Name: client.AlertRouteAutoGeneratedTemplateBindingV3{Autogenerated: true},
			},
		},
	}

	// Omitted in config (nil plan): custom_fields stays null.
	got := AlertRouteResourceModel{}.FromAPIV3(api)
	if got.IncidentConfig.Template == nil {
		t.Fatal("template is nil")
	}
	if got.IncidentConfig.Template.CustomFields != nil {
		t.Errorf("custom_fields: expected nil, got %+v", got.IncidentConfig.Template.CustomFields)
	}

	// Explicit empty in plan: custom_fields normalised to a non-nil empty slice.
	plan := &AlertRouteResourceModel{
		IncidentConfig: &AlertRouteIncidentConfigModel{
			Template: &AlertRouteV3IncidentTemplateModel{
				CustomFields: []AlertRouteCustomFieldModel{},
			},
		},
	}
	gotEmpty := AlertRouteResourceModel{}.FromAPIV3WithPlan(api, plan)
	if gotEmpty.IncidentConfig.Template == nil {
		t.Fatal("template is nil")
	}
	if gotEmpty.IncidentConfig.Template.CustomFields == nil {
		t.Error("custom_fields: expected non-nil empty slice, got nil")
	}
	if len(gotEmpty.IncidentConfig.Template.CustomFields) != 0 {
		t.Errorf("custom_fields: expected length 0, got %d", len(gotEmpty.IncidentConfig.Template.CustomFields))
	}
}

// TestAlertRouteV3ReconcilesConditionOperation is
// TestAlertRouteV2ReconcilesConditionOperation for the v3 mapping.
func TestAlertRouteV3ReconcilesConditionOperation(t *testing.T) {
	api := client.AlertRouteV3{
		Id:   "01ABC",
		Name: "route",
		ConditionGroups: []client.ConditionGroupV3{
			{
				Conditions: []client.ConditionV3{
					{
						Subject:       client.ConditionSubjectV3{Reference: "alert.attributes.01GH"},
						Operation:     client.ConditionOperationV3{Value: "contains_one_of"},
						ParamBindings: []client.EngineParamBindingV3{},
					},
				},
			},
		},
		Expressions: []client.ExpressionV3{},
		GroupingConfig: client.AlertGroupingConfigV3{
			Default: client.GroupingSettingsV3{Enabled: false},
		},
		MessageConfig: client.AlertMessageConfigV3{
			Destinations: []client.AlertMessageDestinationV3{},
		},
		EscalationConfig: client.AlertRouteEscalationConfigV3{
			EscalationTargets: []client.AlertRouteEscalationTargetV3{},
		},
		IncidentConfig: client.AlertRouteIncidentConfigV3{Enabled: false},
	}

	plan := &AlertRouteResourceModel{
		GroupingConfig: &AlertRouteV3GroupingConfigModel{
			Default: &AlertRouteV3GroupingSettingsModel{},
		},
		ConditionGroups: IncidentEngineConditionGroups{
			{
				Conditions: IncidentEngineConditions{
					{
						Subject:   types.StringValue("alert.attributes.01GH"),
						Operation: types.StringValue("one_of"),
					},
				},
			},
		},
	}

	withPlan := AlertRouteResourceModel{}.FromAPIV3WithPlan(api, plan)
	if got := withPlan.ConditionGroups[0].Conditions[0].Operation.ValueString(); got != "one_of" {
		t.Errorf("with plan: operation should be reconciled to %q, got %q", "one_of", got)
	}

	noPlan := AlertRouteResourceModel{}.FromAPIV3(api)
	if got := noPlan.ConditionGroups[0].Conditions[0].Operation.ValueString(); got != "contains_one_of" {
		t.Errorf("no plan: operation should stay verbatim %q, got %q", "contains_one_of", got)
	}
}

// TestAlertRouteV3ReconcilesEveryConditionGroupLocation guards the wiring rather
// than the reconciliation itself: a condition group missed in FromAPIV3WithPlan
// still fails apply, and every other test here only covers the top-level one.
func TestAlertRouteV3ReconcilesEveryConditionGroupLocation(t *testing.T) {
	const subject = "alert.attributes.01GH"

	apiGroups := func() []client.ConditionGroupV3 {
		return []client.ConditionGroupV3{
			{Conditions: []client.ConditionV3{
				{
					Subject:       client.ConditionSubjectV3{Reference: subject},
					Operation:     client.ConditionOperationV3{Value: "contains_one_of"},
					ParamBindings: []client.EngineParamBindingV3{},
				},
			}},
		}
	}
	planGroups := func() IncidentEngineConditionGroups {
		return IncidentEngineConditionGroups{
			{Conditions: IncidentEngineConditions{
				{Subject: types.StringValue(subject), Operation: types.StringValue("one_of")},
			}},
		}
	}

	api := client.AlertRouteV3{
		Id:              "01ABC",
		Name:            "route",
		ConditionGroups: apiGroups(),
		AlertSources: []client.AlertRouteAlertSourceV3{
			{AlertSourceId: "01SOURCE", ConditionGroups: apiGroups()},
		},
		Expressions: []client.ExpressionV3{
			{
				Reference: "expr",
				Label:     "expr",
				Operations: []client.ExpressionOperationV3{
					{
						OperationType: "filter",
						Filter:        &client.ExpressionFilterOptsV3{ConditionGroups: apiGroups()},
					},
				},
			},
		},
		GroupingConfig: client.AlertGroupingConfigV3{
			Default: client.GroupingSettingsV3{Enabled: false},
		},
		MessageConfig: client.AlertMessageConfigV3{
			Destinations: []client.AlertMessageDestinationV3{
				{ConditionGroups: apiGroups()},
			},
		},
		EscalationConfig: client.AlertRouteEscalationConfigV3{
			EscalationTargets: []client.AlertRouteEscalationTargetV3{},
		},
		IncidentConfig: client.AlertRouteIncidentConfigV3{
			Enabled:         true,
			ConditionGroups: lo.ToPtr(apiGroups()),
		},
	}

	plan := &AlertRouteResourceModel{
		GroupingConfig: &AlertRouteV3GroupingConfigModel{
			Default: &AlertRouteV3GroupingSettingsModel{},
		},
		ConditionGroups: planGroups(),
		AlertSources: []AlertRouteAlertSourceModel{
			{AlertSourceID: types.StringValue("01SOURCE"), ConditionGroups: planGroups()},
		},
		Expressions: IncidentEngineExpressions{
			{
				Reference: types.StringValue("expr"),
				Operations: IncidentEngineExpressionOperations{
					{
						OperationType: types.StringValue("filter"),
						Filter:        &IncidentEngineExpressionFilterOpts{ConditionGroups: planGroups()},
					},
				},
			},
		},
		MessageConfig: &AlertRouteV3MessageConfigModel{
			Destinations: []AlertRouteV3ChannelConfigModel{
				{ConditionGroups: planGroups()},
			},
		},
		IncidentConfig: &AlertRouteIncidentConfigModel{ConditionGroups: planGroups()},
	}

	result := AlertRouteResourceModel{}.FromAPIV3WithPlan(api, plan)

	locations := map[string]IncidentEngineConditionGroups{
		"condition_groups":              result.ConditionGroups,
		"alert_sources":                 result.AlertSources[0].ConditionGroups,
		"message_config.destinations":   result.MessageConfig.Destinations[0].ConditionGroups,
		"incident_config":               result.IncidentConfig.ConditionGroups,
		"expressions.operations.filter": result.Expressions[0].Operations[0].Filter.ConditionGroups,
	}
	for location, groups := range locations {
		if got := groups[0].Conditions[0].Operation.ValueString(); got != "one_of" {
			t.Errorf("%s: operation should be reconciled to %q, got %q", location, "one_of", got)
		}
	}
}

// TestWhenAlertJoinsGroupFromAPIGracePeriodByMode covers the mapping of
// grace_period_seconds out of the API. The grace period is only a real,
// configurable field when mode is on_each_new_alert. For on_priority_increase
// the API still echoes back a (zero) grace_period_seconds, but the config/plan
// always holds null there (ValidateConfig rejects setting it). If we copied the
// server's 0 into state, apply would fail with "Provider produced inconsistent
// result after apply: was null, but now cty.NumberIntVal(0)".
func TestWhenAlertJoinsGroupFromAPIGracePeriodByMode(t *testing.T) {
	tests := []struct {
		name           string
		mode           client.AlertRouteWhenAlertJoinsGroupV3Mode
		apiGrace       *int32
		wantGraceNull  bool
		wantGraceValue int64
	}{
		{
			name:           "on_each_new_alert carries the grace period",
			mode:           client.AlertRouteWhenAlertJoinsGroupV3ModeOnEachNewAlert,
			apiGrace:       lo.ToPtr(int32(60)),
			wantGraceNull:  false,
			wantGraceValue: 60,
		},
		{
			name:          "on_priority_increase ignores a server-sent zero",
			mode:          client.AlertRouteWhenAlertJoinsGroupV3ModeOnPriorityIncrease,
			apiGrace:      lo.ToPtr(int32(0)),
			wantGraceNull: true,
		},
		{
			name:          "on_priority_increase with nil grace stays null",
			mode:          client.AlertRouteWhenAlertJoinsGroupV3ModeOnPriorityIncrease,
			apiGrace:      nil,
			wantGraceNull: true,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			obj := whenAlertJoinsGroupFromAPI(&client.AlertRouteWhenAlertJoinsGroupV3{
				Mode:               tc.mode,
				GracePeriodSeconds: tc.apiGrace,
			})

			var m AlertRouteWhenAlertJoinsGroupModel
			obj.As(context.Background(), &m, basetypes.ObjectAsOptions{})

			if got := m.Mode.ValueString(); got != string(tc.mode) {
				t.Errorf("mode: got %q, want %q", got, tc.mode)
			}
			if tc.wantGraceNull {
				if !m.GracePeriodSeconds.IsNull() {
					t.Errorf("grace_period_seconds: expected null, got %d", m.GracePeriodSeconds.ValueInt64())
				}
				return
			}
			if m.GracePeriodSeconds.IsNull() {
				t.Fatal("grace_period_seconds: expected a value, got null")
			}
			if got := m.GracePeriodSeconds.ValueInt64(); got != tc.wantGraceValue {
				t.Errorf("grace_period_seconds: got %d, want %d", got, tc.wantGraceValue)
			}
		})
	}
}

// TestAlertRouteV3TemplateOmittedStaysNull covers issue #486: with incident
// creation enabled but `incident_config.template` omitted from the config, the
// API still returns a fully-populated default template. Writing that into state
// tripped "produced an unexpected new value: .incident_config.template: was
// null, but now cty.ObjectVal(...)" on apply.
func TestAlertRouteV3TemplateOmittedStaysNull(t *testing.T) {
	api := client.AlertRouteV3{
		Id:              "01ABC",
		Name:            "route",
		ConditionGroups: []client.ConditionGroupV3{},
		Expressions:     []client.ExpressionV3{},
		GroupingConfig: client.AlertGroupingConfigV3{
			Default: client.GroupingSettingsV3{Enabled: false},
		},
		MessageConfig: client.AlertMessageConfigV3{
			Destinations: []client.AlertMessageDestinationV3{},
		},
		EscalationConfig: client.AlertRouteEscalationConfigV3{
			EscalationTargets: []client.AlertRouteEscalationTargetV3{},
		},
		// What the API returns for enabled = true when we sent no template:
		// every binding present but empty, severity defaulted to first-wins.
		IncidentConfig: client.AlertRouteIncidentConfigV3{
			Enabled:            true,
			AutoDeclineEnabled: lo.ToPtr(false),
			Template: &client.AlertRouteIncidentTemplateV3{
				Name:          client.AlertRouteAutoGeneratedTemplateBindingV3{},
				Summary:       &client.AlertRouteAutoGeneratedTemplateBindingV3{},
				IncidentMode:  &client.AlertRouteTemplateBindingV3{},
				IncidentType:  &client.AlertRouteTemplateBindingV3{},
				StartInTriage: &client.AlertRouteTemplateBindingV3{},
				Severity:      &client.AlertRouteSeverityBindingV3{MergeStrategy: "first-wins"},
			},
		},
	}

	// Omitted in config: template must stay null so the applied state matches
	// the plan.
	plan := &AlertRouteResourceModel{
		IncidentConfig: &AlertRouteIncidentConfigModel{Template: nil},
	}
	got := AlertRouteResourceModel{}.FromAPIV3WithPlan(api, plan)
	if got.IncidentConfig.Template != nil {
		t.Errorf("template: expected nil for a plan that omits it, got %+v", got.IncidentConfig.Template)
	}

	// Import (no plan): take whatever the API returns, so the template lands in
	// state and the user can see what to write into their config.
	imported := AlertRouteResourceModel{}.FromAPIV3(api)
	if imported.IncidentConfig.Template == nil {
		t.Error("template: expected non-nil on import, got nil")
	}
}
