package models

import (
	"testing"

	"github.com/incident-io/terraform-provider-incident/internal/client"
)

// TestAlertRouteV2RoundTrip is a light round-trip of the v2 mapping. Its main
// job (beyond confirming v2 fields survive) is to assert that the v3-only
// fields on the shared merged model come back null in v2 mode, so v2 state
// keeps its shape and IsV3Mode stays false.
func TestAlertRouteV2RoundTrip(t *testing.T) {
	api := client.AlertRouteV2{
		Id:        "01ABC",
		Name:      "route",
		Enabled:   true,
		IsPrivate: false,
		Version:   2,
		AlertSources: []client.AlertRouteAlertSourceV2{
			{AlertSourceId: "01SRC", ConditionGroups: []client.ConditionGroupV2{}},
		},
		ChannelConfig:   []client.AlertRouteChannelConfigV2{},
		ConditionGroups: []client.ConditionGroupV2{},
		Expressions:     []client.ExpressionV2{},
		EscalationConfig: client.AlertRouteEscalationConfigV2{
			AutoCancelEscalations: true,
			EscalationTargets:     []client.AlertRouteEscalationTargetV2{},
		},
		IncidentConfig: client.AlertRouteIncidentConfigV2{
			AutoDeclineEnabled:      false,
			AutoRelateGroupedAlerts: true,
			DeferTimeSeconds:        0,
			Enabled:                 true,
			GroupingKeys:            []client.GroupingKeyV2{{Reference: "alert.title"}},
			GroupingWindowSeconds:   300,
		},
		IncidentTemplate: client.AlertRouteIncidentTemplateV2{
			Name: client.AlertRouteAutoGeneratedTemplateBindingV2{Autogenerated: true},
		},
	}

	model := AlertRouteResourceModel{}.FromAPIV2(api)

	// Mode: no grouping_config, so this is a v2-mode model.
	if model.IsV3Mode() {
		t.Error("expected IsV3Mode to be false for a v2 route")
	}

	// v2 fields survive.
	if got := model.Name.ValueString(); got != "route" {
		t.Errorf("name: got %q", got)
	}
	if got := model.IncidentConfig.GroupingWindowSeconds.ValueInt64(); got != 300 {
		t.Errorf("grouping_window_seconds: got %d", got)
	}
	if !model.IncidentConfig.AutoRelateGroupedAlerts.ValueBool() {
		t.Error("auto_relate_grouped_alerts should be true")
	}
	if got := len(model.IncidentConfig.GroupingKeys); got != 1 {
		t.Errorf("grouping_keys: got %d", got)
	}
	if !model.EscalationConfig.AutoCancelEscalations.ValueBool() {
		t.Error("auto_cancel_escalations should be true")
	}
	if model.IncidentTemplate == nil || !model.IncidentTemplate.Name.Autogenerated.ValueBool() {
		t.Error("incident_template.name should be autogenerated")
	}

	// v3-only fields must be null/nil in v2 mode.
	if !model.EscalationConfig.WhenAlertJoinsGroup.IsNull() {
		t.Error("escalation_config.when_alert_joins_group should be null in v2 mode")
	}
	if model.IncidentConfig.Template != nil {
		t.Error("incident_config.template should be nil in v2 mode")
	}
	if model.GroupingConfig != nil {
		t.Error("grouping_config should be nil in v2 mode")
	}
	if model.MessageConfig != nil {
		t.Error("message_config should be nil in v2 mode")
	}

	// Round-trip back to a payload and confirm key v2 fields are carried.
	payload := model.ToCreatePayloadV2()
	if payload.IncidentConfig.GroupingWindowSeconds != 300 {
		t.Errorf("payload grouping_window_seconds: got %d", payload.IncidentConfig.GroupingWindowSeconds)
	}
	if !payload.EscalationConfig.AutoCancelEscalations {
		t.Error("payload auto_cancel_escalations should be true")
	}
}
