package models

import (
	"context"
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/samber/lo"

	"github.com/incident-io/terraform-provider-incident/internal/client"
)

// TestAlertRouteV3RoundTrip exercises the FromAPI -> ToCreatePayload path,
// including the JSON-bridged v3<->v2 engine type conversion, to confirm the
// restructured v3 fields (grouping_config, message_config,
// when_alert_joins_group, incident_config.template) survive a round trip.
func TestAlertRouteV3RoundTrip(t *testing.T) {
	api := client.AlertRouteV3{
		Id:        "01ABC",
		Name:      "route",
		Enabled:   true,
		IsPrivate: false,
		Version:   3,
		AlertSources: []client.AlertRouteAlertSourceV3{
			{
				AlertSourceId: "01SRC",
				ConditionGroups: []client.ConditionGroupV3{
					{
						Conditions: []client.ConditionV3{
							{
								Subject:       client.ConditionSubjectV3{Reference: "alert.title"},
								Operation:     client.ConditionOperationV3{Value: "is_set"},
								ParamBindings: []client.EngineParamBindingV3{},
							},
						},
					},
				},
			},
		},
		ConditionGroups: []client.ConditionGroupV3{},
		Expressions:     []client.ExpressionV3{},
		GroupingConfig: client.AlertGroupingConfigV3{
			Default: client.GroupingSettingsV3{
				Enabled:       true,
				GroupKeys:     &[]client.GroupingKeyV3{{Reference: "alert.title"}},
				WindowSeconds: lo.ToPtr(int32(1800)),
				WindowType:    lo.ToPtr(client.Fixed),
			},
		},
		MessageConfig: client.AlertMessageConfigV3{
			Destinations: []client.AlertMessageDestinationV3{
				{
					ConditionGroups: []client.ConditionGroupV3{},
					SlackTargets: &client.AlertRouteChannelTargetV3{
						ChannelVisibility: "public",
						Binding: client.EngineParamBindingV3{
							Value: &client.EngineParamBindingValueV3{Literal: lo.ToPtr("C123")},
						},
					},
				},
			},
		},
		EscalationConfig: client.AlertRouteEscalationConfigV3{
			AutoCancelEscalations: true,
			EscalationTargets:     []client.AlertRouteEscalationTargetV3{},
			WhenAlertJoinsGroup: &client.AlertRouteAlertJoinsGroupV3{
				Mode:               client.AlertRouteAlertJoinsGroupV3ModeOnPriorityIncrease,
				GracePeriodSeconds: lo.ToPtr(int32(60)),
			},
		},
		IncidentConfig: client.AlertRouteIncidentConfigV3{
			AutoDeclineEnabled: lo.ToPtr(false),
			Enabled:            true,
			ConditionGroups:    &[]client.ConditionGroupV3{},
			Template: &client.AlertRouteIncidentTemplateV3{
				Name: client.AlertRouteAutoGeneratedTemplateBindingV3{
					Autogenerated: true,
					Binding: &client.EngineParamBindingV3{
						Value: &client.EngineParamBindingValueV3{Literal: lo.ToPtr("title")},
					},
				},
				Summary: &client.AlertRouteAutoGeneratedTemplateBindingV3{
					Autogenerated: true,
					Binding: &client.EngineParamBindingV3{
						Value: &client.EngineParamBindingValueV3{Literal: lo.ToPtr("summary")},
					},
				},
				Severity: &client.AlertRouteSeverityBindingV3{
					MergeStrategy: client.AlertRouteSeverityBindingV3MergeStrategyFirstWins,
				},
				CustomFields: &[]client.AlertRouteCustomFieldBindingV3{
					{
						CustomFieldId: "01CF",
						MergeStrategy: client.AlertRouteCustomFieldBindingV3MergeStrategyFirstWins,
						Binding: client.EngineParamBindingV3{
							Value: &client.EngineParamBindingValueV3{Literal: lo.ToPtr("Test incident")},
						},
					},
				},
			},
		},
	}

	model := AlertRouteV3ResourceModel{}.FromAPI(api)

	// Top-level.
	if got := model.Name.ValueString(); got != "route" {
		t.Errorf("name: got %q", got)
	}

	// Grouping config.
	if model.GroupingConfig == nil || model.GroupingConfig.Default == nil {
		t.Fatal("grouping_config.default is nil")
	}
	if !model.GroupingConfig.Default.Enabled.ValueBool() {
		t.Error("grouping enabled should be true")
	}
	if got := model.GroupingConfig.Default.WindowType.ValueString(); got != "fixed" {
		t.Errorf("window_type: got %q", got)
	}
	if got := len(model.GroupingConfig.Default.GroupKeys); got != 1 {
		t.Errorf("group_keys: got %d", got)
	}

	// Message config.
	if model.MessageConfig == nil || len(model.MessageConfig.Destinations) != 1 {
		t.Fatalf("message_config destinations: %+v", model.MessageConfig)
	}
	if model.MessageConfig.Destinations[0].SlackTargets == nil {
		t.Fatal("slack_targets is nil")
	}

	// when_alert_joins_group (modelled as a types.Object).
	if model.EscalationConfig.WhenAlertJoinsGroup.IsNull() {
		t.Fatal("when_alert_joins_group is null")
	}
	var joinsGroup AlertRouteWhenAlertJoinsGroupModel
	model.EscalationConfig.WhenAlertJoinsGroup.As(context.Background(), &joinsGroup, basetypes.ObjectAsOptions{})
	if got := joinsGroup.Mode.ValueString(); got != "on_priority_increase" {
		t.Errorf("mode: got %q", got)
	}
	if got := joinsGroup.GracePeriodSeconds.ValueInt64(); got != 60 {
		t.Errorf("grace_period_seconds: got %d", got)
	}

	// Incident template (nested under incident_config).
	if model.IncidentConfig == nil || model.IncidentConfig.Template == nil {
		t.Fatal("incident_config.template is nil")
	}
	if !model.IncidentConfig.Template.Name.Autogenerated.ValueBool() {
		t.Error("template name should be autogenerated")
	}
	if got := len(model.IncidentConfig.Template.CustomFields); got != 1 {
		t.Errorf("custom_fields: got %d", got)
	}

	// Now convert back to a payload and check the engine-bridged fields survive.
	payload := model.ToCreatePayload()

	if got := payload.GroupingConfig.Default.WindowType; got == nil || *got != client.Fixed {
		t.Errorf("payload window_type: got %v", got)
	}
	if got := len(payload.MessageConfig.Destinations); got != 1 {
		t.Fatalf("payload destinations: got %d", got)
	}
	slack := payload.MessageConfig.Destinations[0].SlackTargets
	if slack == nil || slack.Binding.Value == nil || lo.FromPtr(slack.Binding.Value.Literal) != "C123" {
		t.Errorf("payload slack binding literal mismatch: %+v", slack)
	}
	if payload.EscalationConfig.WhenAlertJoinsGroup == nil {
		t.Fatal("payload when_alert_joins_group is nil")
	}
	if got := lo.FromPtr(payload.EscalationConfig.WhenAlertJoinsGroup.GracePeriodSeconds); got != 60 {
		t.Errorf("payload grace_period_seconds: got %d", got)
	}
	if payload.IncidentConfig.Template == nil {
		t.Fatal("payload incident template is nil")
	}
	if got := len(*payload.IncidentConfig.Template.CustomFields); got != 1 {
		t.Errorf("payload custom_fields: got %d", got)
	}
	cf := (*payload.IncidentConfig.Template.CustomFields)[0]
	if cf.Binding.Value == nil || lo.FromPtr(cf.Binding.Value.Literal) != "Test incident" {
		t.Errorf("payload custom field binding mismatch: %+v", cf.Binding)
	}
}

// TestAlertRouteV3MessageConfigDestinationsNullVsEmpty checks that
// FromAPIWithPlan mirrors the planned null-vs-empty shape of the optional
// message_config.destinations set. The API returns no destinations both when
// the attribute is omitted and when it's set to an explicit empty list, so the
// result must follow the plan to avoid perpetual diffs on refresh.
func TestAlertRouteV3MessageConfigDestinationsNullVsEmpty(t *testing.T) {
	// An apiModel that returns no destinations.
	api := client.AlertRouteV3{
		Id:              "01ABC",
		Name:            "route",
		ConditionGroups: []client.ConditionGroupV3{},
		Expressions:     []client.ExpressionV3{},
		GroupingConfig: client.AlertGroupingConfigV3{
			Default: client.GroupingSettingsV3{},
		},
		MessageConfig: client.AlertMessageConfigV3{
			Destinations: []client.AlertMessageDestinationV3{},
		},
		EscalationConfig: client.AlertRouteEscalationConfigV3{
			EscalationTargets: []client.AlertRouteEscalationTargetV3{},
		},
		IncidentConfig: client.AlertRouteIncidentConfigV3{},
	}

	// Plan with an explicit, non-nil empty destinations slice.
	planEmpty := &AlertRouteV3ResourceModel{
		MessageConfig: &AlertRouteV3MessageConfigModel{
			Destinations: []AlertRouteChannelConfigModel{},
		},
	}

	resultEmpty := AlertRouteV3ResourceModel{}.FromAPIWithPlan(api, planEmpty)
	if resultEmpty.MessageConfig == nil {
		t.Fatal("message_config is nil")
	}
	if resultEmpty.MessageConfig.Destinations == nil {
		t.Error("destinations should be non-nil empty when plan set explicit empty slice")
	}
	if got := len(resultEmpty.MessageConfig.Destinations); got != 0 {
		t.Errorf("destinations: got %d, want 0", got)
	}

	// With no plan, the omitted optional should stay null (nil).
	resultNil := AlertRouteV3ResourceModel{}.FromAPIWithPlan(api, nil)
	if resultNil.MessageConfig == nil {
		t.Fatal("message_config is nil")
	}
	if resultNil.MessageConfig.Destinations != nil {
		t.Errorf("destinations should be nil when plan is nil, got %+v", resultNil.MessageConfig.Destinations)
	}
}

// TestAlertRouteV3ImportLeavesConditionalFieldsNull simulates an import/read of a
// route with grouping and incident creation disabled: the API omits the
// conditional detail fields and there is no prior plan/state. Those fields are
// optional in the schema, so FromAPI must leave them null rather than writing a
// zero value, which would break ImportStateVerify and cause plan churn.
func TestAlertRouteV3ImportLeavesConditionalFieldsNull(t *testing.T) {
	api := client.AlertRouteV3{
		Id:              "01ABC",
		Name:            "route",
		ConditionGroups: []client.ConditionGroupV3{},
		Expressions:     []client.ExpressionV3{},
		GroupingConfig: client.AlertGroupingConfigV3{
			Default: client.GroupingSettingsV3{Enabled: false},
		},
		MessageConfig: client.AlertMessageConfigV3{
			Destinations: []client.AlertMessageDestinationV3{},
		},
		EscalationConfig: client.AlertRouteEscalationConfigV3{
			EscalationTargets: []client.AlertRouteEscalationTargetV3{},
		},
		IncidentConfig: client.AlertRouteIncidentConfigV3{Enabled: false},
	}

	// FromAPI passes a nil plan, exactly as the import path does.
	model := AlertRouteV3ResourceModel{}.FromAPI(api)

	if model.GroupingConfig == nil || model.GroupingConfig.Default == nil {
		t.Fatal("grouping_config.default is nil")
	}
	if !model.GroupingConfig.Default.WindowSeconds.IsNull() {
		t.Errorf("window_seconds: expected null, got %v", model.GroupingConfig.Default.WindowSeconds)
	}
	if !model.GroupingConfig.Default.WindowType.IsNull() {
		t.Errorf("window_type: expected null, got %v", model.GroupingConfig.Default.WindowType)
	}
	if model.GroupingConfig.Default.GroupKeys != nil {
		t.Errorf("group_keys: expected nil, got %+v", model.GroupingConfig.Default.GroupKeys)
	}
	if model.IncidentConfig == nil {
		t.Fatal("incident_config is nil")
	}
	if !model.IncidentConfig.AutoDeclineEnabled.IsNull() {
		t.Errorf("auto_decline_enabled: expected null, got %v", model.IncidentConfig.AutoDeclineEnabled)
	}
}

// TestAlertRouteV3CustomFieldsNullVsEmpty checks that the optional
// incident_config.template.custom_fields set mirrors the planned null-vs-empty
// shape when the API returns no custom fields (which it does both when the
// attribute is omitted and when it's an explicit empty list).
func TestAlertRouteV3CustomFieldsNullVsEmpty(t *testing.T) {
	api := client.AlertRouteV3{
		Id:              "01ABC",
		Name:            "route",
		ConditionGroups: []client.ConditionGroupV3{},
		Expressions:     []client.ExpressionV3{},
		GroupingConfig: client.AlertGroupingConfigV3{
			Default: client.GroupingSettingsV3{Enabled: false},
		},
		MessageConfig: client.AlertMessageConfigV3{
			Destinations: []client.AlertMessageDestinationV3{},
		},
		EscalationConfig: client.AlertRouteEscalationConfigV3{
			EscalationTargets: []client.AlertRouteEscalationTargetV3{},
		},
		IncidentConfig: client.AlertRouteIncidentConfigV3{
			Enabled: true,
			Template: &client.AlertRouteIncidentTemplateV3{
				// The API returns no custom fields.
				Name: client.AlertRouteAutoGeneratedTemplateBindingV3{Autogenerated: true},
			},
		},
	}

	// Omitted in config (nil plan): custom_fields stays null.
	got := AlertRouteV3ResourceModel{}.FromAPI(api)
	if got.IncidentConfig.Template == nil {
		t.Fatal("template is nil")
	}
	if got.IncidentConfig.Template.CustomFields != nil {
		t.Errorf("custom_fields: expected nil, got %+v", got.IncidentConfig.Template.CustomFields)
	}

	// Explicit empty in plan: custom_fields normalised to a non-nil empty slice.
	plan := &AlertRouteV3ResourceModel{
		IncidentConfig: &AlertRouteV3IncidentConfigModel{
			Template: &AlertRouteV3IncidentTemplateModel{
				CustomFields: []AlertRouteCustomFieldModel{},
			},
		},
	}
	gotEmpty := AlertRouteV3ResourceModel{}.FromAPIWithPlan(api, plan)
	if gotEmpty.IncidentConfig.Template == nil {
		t.Fatal("template is nil")
	}
	if gotEmpty.IncidentConfig.Template.CustomFields == nil {
		t.Error("custom_fields: expected non-nil empty slice, got nil")
	}
	if len(gotEmpty.IncidentConfig.Template.CustomFields) != 0 {
		t.Errorf("custom_fields: expected length 0, got %d", len(gotEmpty.IncidentConfig.Template.CustomFields))
	}
}
