package models

import (
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
)

// The checks the schema cannot express, run from each resource's ValidateConfig so they land
// at plan time against a path in the config. Two kinds: attributes that would be Required if
// a Required child didn't make its whole block mandatory, and the exclusive groups
// ConflictsWith cannot describe.
//
// These are only as durable as their tests — a schema Required can't be refactored away by
// accident, a hand-written check can.

// ValidateExpressions checks a resource's expression blocks. Pass nil for bound if the
// resource owns only named ones, in which case boundPath is unused.
//
// ns is only read for the shape of the names it produces, so a caller can pass one built from a
// value Terraform hasn't resolved yet.
func ValidateExpressions(
	ns ExpressionNamespace,
	bound *Expression, boundPath path.Path,
	named []NamedExpression, namedPath path.Path,
	diags *diag.Diagnostics,
) {
	known := map[string]bool{}

	for idx, expression := range named {
		at := namedPath.AtListIndex(idx)
		name := expression.Name.ValueString()

		if ns.reservesName(name) {
			diags.AddAttributeError(
				at.AtName("name"),
				"Reserved name",
				fmt.Sprintf("%q is reserved for an unnamed expression block. Pick another name.", name),
			)
		}

		// Reserved, or a sibling could collide with a generated fallback and the two would
		// fight over the same row.
		if strings.HasSuffix(name, FallbackSuffix) {
			diags.AddAttributeError(
				at.AtName("name"),
				"Reserved name",
				fmt.Sprintf("Names ending in %q are reserved for expressions generated by a fallback if/else_if block. Pick another name.", FallbackSuffix),
			)
		}

		// The server rejects these too; this is just a better message.
		if known[name] {
			diags.AddAttributeError(
				at.AtName("name"),
				"Duplicate name",
				fmt.Sprintf("More than one named_expression is called %q. Names must be unique within a resource.", name),
			)
		}
		known[name] = true
	}

	// Names are collected first, so an expression_ref can point forwards at a sibling
	// written below it.
	for idx, expression := range named {
		validateExpressionBody(
			expression.StartFrom.IsNull(), expression.Operations, expression.Fallback,
			namedPath.AtListIndex(idx), "A named_expression", known, diags)
	}

	if bound != nil {
		validateExpressionBody(
			bound.StartFrom.IsNull(), bound.Operations, bound.Fallback,
			boundPath, "An expression", known, diags)
	}
}

// KnownExpressionNames is the set an expression_ref may name, for resources validating
// bindings of their own outside the expression tree.
func KnownExpressionNames(named []NamedExpression) map[string]bool {
	known := map[string]bool{}
	for _, expression := range named {
		known[expression.Name.ValueString()] = true
	}

	return known
}

func validateExpressionBody(
	startFromMissing bool,
	operations []Operation,
	fallback *Fallback,
	at path.Path,
	// Leads the sentence, so it carries its own article — the two block names don't take
	// the same one.
	blockName string,
	known map[string]bool,
	diags *diag.Diagnostics,
) {
	if startFromMissing {
		diags.AddAttributeError(
			at.AtName("start_from"),
			"Missing start_from",
			fmt.Sprintf("%s block must say where it starts, e.g. start_from = \"payload\".", blockName),
		)
	}

	if len(operations) == 0 {
		diags.AddAttributeError(
			at.AtName("operation"),
			"No operations",
			fmt.Sprintf("%s block needs at least one operation block. An expression that only names where it starts produces nothing.", blockName),
		)
	}

	for idx, operation := range operations {
		validateOperation(operation, at.AtName("operation").AtListIndex(idx), known, diags)
	}

	validateFallback(fallback, operations, at.AtName("fallback"), known, diags)
}

func validateOperation(operation Operation, at path.Path, known map[string]bool, diags *diag.Diagnostics) {
	set := setOperationOptions(operation)

	switch {
	case len(set) == 0:
		diags.AddAttributeError(
			at,
			"Empty operation",
			"An operation block must set exactly one of parse, navigate, filter, cast, concatenate, branches, first, count, sum, min, max or random.",
		)
		return

	case len(set) > 1:
		diags.AddAttributeError(
			at,
			"Ambiguous operation",
			fmt.Sprintf("An operation block sets %s. Set exactly one — the one that is set is what decides the operation.", strings.Join(set, " and ")),
		)
		return
	}

	if operation.Filter != nil {
		validateConditions(operation.Filter.Conditions, operation.Filter.ConditionGroups, at.AtName("filter"), known, diags)
	}

	if operation.Branches != nil {
		validateBranches(operation.Branches, at.AtName("branches"), true, known, diags)
	}
}

// setOperationOptions lists what an operation sets, in schema order so the message reads the
// same way every time.
func setOperationOptions(operation Operation) []string {
	set := []string{}
	for _, candidate := range []struct {
		name  string
		isSet bool
	}{
		{"parse", operation.Parse != nil},
		{"navigate", operation.Navigate != nil},
		{"filter", operation.Filter != nil},
		{"cast", operation.Cast != nil},
		{"concatenate", operation.Concatenate != nil},
		{"branches", operation.Branches != nil},
		{"first", operation.First != nil},
		{"count", operation.Count != nil},
		{"sum", operation.Sum != nil},
		{"min", operation.Min != nil},
		{"max", operation.Max != nil},
		{"random", operation.Random != nil},
	} {
		if candidate.isSet {
			set = append(set, candidate.name)
		}
	}

	return set
}

// validateBranches takes requiresAs false for the fallback shorthand, where the type is
// inferred from the parent rather than written.
func validateBranches(
	branches *Branches,
	at path.Path,
	requiresAs bool,
	known map[string]bool,
	diags *diag.Diagnostics,
) {
	if requiresAs && branches.As.IsNull() {
		diags.AddAttributeError(
			at.AtName("as"),
			"Missing as",
			"A branches block must say what type its branches return, e.g. as = incident_catalog_type.service.attribute_type.",
		)
	}

	if branches.If == nil && len(branches.ElseIf) == 0 {
		diags.AddAttributeError(
			at,
			"No branches",
			"A branches block needs at least an if block. For an unconditional value, use the expression's fallback instead.",
		)
	}

	// First-match-wins over a list whose first entry is missing reads as a typo, not
	// something to silently accept.
	if branches.If == nil && len(branches.ElseIf) > 0 {
		diags.AddAttributeError(
			at.AtName("else_if"),
			"else_if without if",
			"The first branch is written as an if block. Rename the first else_if to if.",
		)
	}

	if branches.If != nil {
		validateBranch(*branches.If, at.AtName("if"), known, diags)
	}
	for idx, branch := range branches.ElseIf {
		validateBranch(branch, at.AtName("else_if").AtListIndex(idx), known, diags)
	}
}

func validateBranch(branch Branch, at path.Path, known map[string]bool, diags *diag.Diagnostics) {
	validateConditions(branch.Conditions, branch.ConditionGroups, at, known, diags)

	if branch.Result == nil {
		diags.AddAttributeError(
			at.AtName("result"),
			"Missing result",
			"A branch must say what value it produces.",
		)
		return
	}

	ValidateBinding(branch.Result, at.AtName("result"), known, diags)
}

func validateConditions(
	conditions []Condition,
	groups []ConditionGroup,
	at path.Path,
	known map[string]bool,
	diags *diag.Diagnostics,
) {
	// The only check: the conditions attributes get reused in positions where no relative
	// schema path could reach their sibling.
	if len(conditions) > 0 && len(groups) > 0 {
		diags.AddAttributeError(
			at.AtName("conditions"),
			"Both conditions and condition_groups set",
			"Set either conditions, which is sugar for a single group, or condition_groups.",
		)
	}

	for idx, condition := range conditions {
		validateCondition(condition, at.AtName("conditions").AtListIndex(idx), known, diags)
	}

	for groupIdx, group := range groups {
		groupAt := at.AtName("condition_groups").AtListIndex(groupIdx).AtName("conditions")
		for idx, condition := range group.Conditions {
			validateCondition(condition, groupAt.AtListIndex(idx), known, diags)
		}
	}
}

func validateCondition(condition Condition, at path.Path, known map[string]bool, diags *diag.Diagnostics) {
	for idx := range condition.Params {
		ValidateBinding(&condition.Params[idx], at.AtName("params").AtListIndex(idx), known, diags)
	}
}

func validateFallback(
	fallback *Fallback,
	parentOperations []Operation,
	at path.Path,
	known map[string]bool,
	diags *diag.Diagnostics,
) {
	if fallback == nil {
		return
	}

	branching := UsesBranchingFallback(fallback)

	// The shorthand is blocks and the other two are attributes, so no schema validator can
	// span the group.
	forms := 0
	for _, isSet := range []bool{fallback.Result != nil, !fallback.ExpressionRef.IsNull(), branching} {
		if isSet {
			forms++
		}
	}
	if forms > 1 {
		diags.AddAttributeError(
			at,
			"Ambiguous fallback",
			"A fallback produces a value one way: result for an unconditional value, expression_ref to defer to a named_expression, or if / else_if / else to branch. Set one.",
		)
	}

	if !fallback.ExpressionRef.IsNull() {
		validateExpressionRef(fallback.ExpressionRef.ValueString(), at.AtName("expression_ref"), known, diags)
	}

	if fallback.Result != nil {
		ValidateBinding(fallback.Result, at.AtName("result"), known, diags)
	}

	switch {
	// Its own message rather than validateBranches', whose "use the fallback instead" would
	// be circular here.
	case fallback.Else != nil && fallback.If == nil && len(fallback.ElseIf) == 0:
		diags.AddAttributeError(
			at.AtName("else"),
			"else without if",
			"An else block is the default for an if / else_if chain, and there isn't one. For an unconditional value, set result directly on the fallback.",
		)

	case branching:
		// The one branches block that writes neither `as` nor `array` — both come from the
		// parent. So a parent that doesn't pin them locally has nothing to give, and the
		// mapping would fail at apply if this were let through.
		if _, _, ok := inferResultType(parentOperations); !ok {
			diags.AddAttributeError(
				at,
				"Fallback needs a knowable result",
				"The branches this shorthand generates have to declare the type and cardinality they return, and they take both from the expression they fall back from — which this one doesn't pin. Either add an operation that states them (parse, or first / concatenate to settle cardinality), or point fallback at a named_expression with expression_ref and state `as` and `array` on its branches.",
			)
		}

		validateBranches(&Branches{If: fallback.If, ElseIf: fallback.ElseIf}, at, false, known, diags)
	}

	if fallback.Else != nil {
		if fallback.Else.Result == nil {
			diags.AddAttributeError(
				at.AtName("else").AtName("result"),
				"Missing result",
				"An else block must say what value it falls back to.",
			)
		} else {
			ValidateBinding(fallback.Else.Result, at.AtName("else").AtName("result"), known, diags)
		}
	}
}

// ValidateBinding is exported because a resource can bind a value outside any expression —
// an alert source's priority.
//
// A nil binding is how absent is expressed, so a present one is always required to hold
// something. Letting `result = {}` through would only defer the failure: the mapping reads
// zero forms as absent, which fails at apply where a value is required and silently drops the
// binding where it is optional, so the next plan adds it again.
func ValidateBinding(binding *Binding, at path.Path, known map[string]bool, diags *diag.Diagnostics) {
	if binding == nil {
		return
	}

	switch forms := SetBindingForms(binding); {
	case forms == 0:
		diags.AddAttributeError(
			at,
			"Missing value",
			"Give this a value: set one of value_literal, value_reference, expression_ref, values, value or array_value.",
		)
		return

	case forms > 1:
		diags.AddAttributeError(
			at,
			"Ambiguous value",
			"Set exactly one of value_literal, value_reference, expression_ref, values, value or array_value.",
		)
	}

	if !binding.ExpressionRef.IsNull() {
		validateExpressionRef(binding.ExpressionRef.ValueString(), at.AtName("expression_ref"), known, diags)
	}

	if binding.Value != nil {
		validateBindingValue(*binding.Value, at.AtName("value"), diags)
	}

	for idx, value := range binding.ArrayValue {
		validateBindingValue(value, at.AtName("array_value").AtListIndex(idx), diags)
	}
}

func validateBindingValue(value BindingValue, at path.Path, diags *diag.Diagnostics) {
	switch {
	case !value.Literal.IsNull() && !value.Reference.IsNull():
		diags.AddAttributeError(at, "Ambiguous value", "Set either literal or reference, not both.")
	case value.Literal.IsNull() && value.Reference.IsNull():
		diags.AddAttributeError(at, "Missing value", "Set either literal or reference.")
	}
}

// validateExpressionRef rejects unknown names: there is no shared expression pool, so the
// server couldn't resolve one either.
func validateExpressionRef(name string, at path.Path, known map[string]bool, diags *diag.Diagnostics) {
	if known[name] {
		return
	}

	diags.AddAttributeError(
		at,
		"Unknown expression_ref",
		fmt.Sprintf("No named_expression in this resource is called %q.", name),
	)
}
