package models

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/incident-io/terraform-provider-incident/v6/internal/client"
)

// This file holds the Terraform model for the incident_incident_template
// resource, plus the mapping to and from the client's IncidentTemplateConfigV1
// types.
//
// The template config is the same nested shape the alert-route v3 incident
// template uses (name/summary autogen bindings, severity + merge_strategy,
// custom_fields, incident_mode/type/start_in_triage), so the mapping below
// reuses the shared binding-conversion helpers from alert_route_v3_model.go
// (paramBindingFromV3, severityFromAPIV3, and friends).
//
// Two fields differ from the alert-route template. This one keeps workspace: a
// standalone incident template can bind the Slack workspace an incident is
// created in. And it drops membership_teams, which the public API doesn't expose
// on a standalone template — that stays an alert-route concern (see ONC-13344).

// IncidentTemplateV1Model is the Terraform plan/state shape for an
// incident_incident_template resource.
type IncidentTemplateV1Model struct {
	ID          types.String                   `tfsdk:"id"`
	Name        types.String                   `tfsdk:"name"`
	Template    *IncidentTemplateConfigV1Model `tfsdk:"template"`
	Expressions IncidentEngineExpressions      `tfsdk:"expressions"`
}

// IncidentTemplateConfigV1Model mirrors client.IncidentTemplateConfigV1. Each
// binding is nil when the user hasn't configured it, matching the v3
// alert-route template pattern (return nil for nested objects with no
// user-configurable data).
type IncidentTemplateConfigV1Model struct {
	CustomFields  []AlertRouteCustomFieldModel         `tfsdk:"custom_fields"`
	IncidentMode  *IncidentEngineParamBinding          `tfsdk:"incident_mode"`
	IncidentType  *IncidentEngineParamBinding          `tfsdk:"incident_type"`
	Name          *AlertRouteAutoGeneratedParamBinding `tfsdk:"name"`
	Severity      types.Object                         `tfsdk:"severity"`
	StartInTriage *IncidentEngineParamBinding          `tfsdk:"start_in_triage"`
	Summary       *AlertRouteAutoGeneratedParamBinding `tfsdk:"summary"`
	Workspace     *IncidentEngineParamBinding          `tfsdk:"workspace"`
}

// createAutoGeneratedBindingV1 builds an IncidentTemplateAutoGeneratedBindingPayloadV1.
// It reuses the v3 auto-generated builder, which produces a structurally
// identical value (autogenerated + a *EngineParamBindingPayloadV3), so we
// convert rather than copy field by field.
func createAutoGeneratedBindingV1(binding *IncidentEngineParamBinding, autogenerated types.Bool) client.IncidentTemplateAutoGeneratedBindingPayloadV1 {
	return client.IncidentTemplateAutoGeneratedBindingPayloadV1(createAutoGeneratedBindingV3(binding, autogenerated))
}

// FromAPI projects an API incident template into Terraform state. plan is
// whatever the plan or prior state held, so bindings can keep the spelling the
// config used, and so an optional attribute the user omitted stays null rather
// than adopting a server-sent shape.
func (IncidentTemplateV1Model) FromAPI(apiModel client.IncidentTemplateV1, plan *IncidentTemplateV1Model) IncidentTemplateV1Model {
	result := IncidentTemplateV1Model{
		ID:   types.StringValue(apiModel.Id),
		Name: types.StringValue(apiModel.Name),
	}

	var planTemplate *IncidentTemplateConfigV1Model
	if plan != nil {
		planTemplate = plan.Template
	}
	result.Template = incidentTemplateConfigFromAPIV1(apiModel.Template, planTemplate)

	result.Expressions = IncidentEngineExpressions{}
	if apiModel.Expressions != nil && len(*apiModel.Expressions) > 0 {
		result.Expressions = expressionsFromV3(*apiModel.Expressions)
	}

	if plan != nil {
		result.Expressions.ReconcileSpelling(plan.Expressions)
	}

	return result
}

func incidentTemplateConfigFromAPIV1(apiTemplate client.IncidentTemplateConfigV1, plan *IncidentTemplateConfigV1Model) *IncidentTemplateConfigV1Model {
	template := &IncidentTemplateConfigV1Model{}

	emptyListType := types.ObjectType{
		AttrTypes: ParamBindingValueAttrTypes(),
	}

	// Name (auto-generatable, plan-aware). Required by the API, so it is always
	// present in the response.
	var planNameBinding *AlertRouteAutoGeneratedParamBinding
	if plan != nil {
		planNameBinding = plan.Name
	}

	nameBinding := AlertRouteAutoGeneratedParamBinding{
		Autogenerated: types.BoolValue(apiTemplate.Name.Autogenerated),
		ArrayValue:    types.ListNull(emptyListType),
	}
	if apiTemplate.Name.Binding != nil {
		paramBinding := paramBindingFromV3(*apiTemplate.Name.Binding)
		nameBinding = AlertRouteAutoGeneratedParamBinding{}.FromParamBindingWithPlan(paramBinding, nameBinding.Autogenerated, planNameBinding)
	} else if planNameBinding != nil {
		nameBinding = AlertRouteAutoGeneratedParamBinding{}.FromParamBindingWithPlan(IncidentEngineParamBinding{}, nameBinding.Autogenerated, planNameBinding)
	}
	template.Name = &nameBinding

	// Summary (auto-generatable, plan-aware, optional).
	var planSummaryBinding *AlertRouteAutoGeneratedParamBinding
	if plan != nil {
		planSummaryBinding = plan.Summary
	}

	summaryBinding := AlertRouteAutoGeneratedParamBinding{
		Autogenerated: types.BoolValue(false),
		ArrayValue:    types.ListNull(emptyListType),
	}
	if apiTemplate.Summary != nil {
		summaryBinding.Autogenerated = types.BoolValue(apiTemplate.Summary.Autogenerated)

		if apiTemplate.Summary.Binding != nil {
			paramBinding := paramBindingFromV3(*apiTemplate.Summary.Binding)
			summaryBinding = AlertRouteAutoGeneratedParamBinding{}.FromParamBindingWithPlan(paramBinding, summaryBinding.Autogenerated, planSummaryBinding)
		} else if planSummaryBinding != nil {
			summaryBinding = AlertRouteAutoGeneratedParamBinding{}.FromParamBindingWithPlan(IncidentEngineParamBinding{}, summaryBinding.Autogenerated, planSummaryBinding)
		}
	} else if planSummaryBinding != nil {
		summaryBinding = AlertRouteAutoGeneratedParamBinding{}.FromParamBindingWithPlan(IncidentEngineParamBinding{}, summaryBinding.Autogenerated, planSummaryBinding)
	}
	// summary is Optional (not Computed), so a create that omits it must stay null
	// in state: only set it when the config had it or the API returned one.
	// Writing a default {autogenerated=false} would be an inconsistent result.
	if apiTemplate.Summary != nil || planSummaryBinding != nil {
		template.Summary = &summaryBinding
	}

	planSeverity := SeverityObjectNull()
	if plan != nil {
		planSeverity = plan.Severity
	}
	template.Severity = severityFromAPIV1(apiTemplate.Severity, planSeverity)

	if apiTemplate.IncidentMode != nil && apiTemplate.IncidentMode.Binding != nil {
		binding := paramBindingFromV3(*apiTemplate.IncidentMode.Binding)
		template.IncidentMode = &binding
	}

	if apiTemplate.IncidentType != nil && apiTemplate.IncidentType.Binding != nil {
		binding := paramBindingFromV3(*apiTemplate.IncidentType.Binding)
		template.IncidentType = &binding
	}

	if apiTemplate.StartInTriage != nil && apiTemplate.StartInTriage.Binding != nil {
		binding := paramBindingFromV3(*apiTemplate.StartInTriage.Binding)
		template.StartInTriage = &binding
	}

	if apiTemplate.Workspace != nil && apiTemplate.Workspace.Binding != nil {
		binding := paramBindingFromV3(*apiTemplate.Workspace.Binding)
		template.Workspace = &binding
	}

	// Custom fields: only populate when the API returns them or the plan has
	// them, otherwise leave nil to preserve null state in Terraform.
	if apiTemplate.CustomFields != nil && len(*apiTemplate.CustomFields) > 0 {
		template.CustomFields = []AlertRouteCustomFieldModel{}
		for _, cf := range *apiTemplate.CustomFields {
			model := AlertRouteCustomFieldModel{
				CustomFieldID: types.StringValue(cf.CustomFieldId),
				MergeStrategy: types.StringValue(string(cf.MergeStrategy)),
			}

			binding := paramBindingFromV3(cf.Binding)
			if binding.Value != nil && binding.Value.Reference.IsNull() {
				binding.Value.Reference = types.StringNull()
			}
			model.Binding = &binding

			template.CustomFields = append(template.CustomFields, model)
		}
	} else if plan != nil && len(plan.CustomFields) > 0 {
		template.CustomFields = []AlertRouteCustomFieldModel{}
		for _, cf := range plan.CustomFields {
			model := AlertRouteCustomFieldModel{
				CustomFieldID: cf.CustomFieldID,
				MergeStrategy: cf.MergeStrategy,
			}
			if cf.Binding != nil {
				bindingCopy := *cf.Binding
				model.Binding = &bindingCopy
			}
			template.CustomFields = append(template.CustomFields, model)
		}
	}

	// Mirror the planned shape of the optional `custom_fields` set: the API
	// returns none both when the attribute is omitted (null) and when it's an
	// explicit empty list ([]). Only normalise to a non-nil empty slice when
	// the plan carried a non-nil (explicit, possibly empty) slice; otherwise
	// leave it nil so an omitted optional stays null and doesn't drift.
	if len(template.CustomFields) == 0 && plan != nil && plan.CustomFields != nil {
		template.CustomFields = []AlertRouteCustomFieldModel{}
	}

	if plan != nil {
		template.IncidentMode = ReconcileBindingSpelling(template.IncidentMode, plan.IncidentMode)
		template.IncidentType = ReconcileBindingSpelling(template.IncidentType, plan.IncidentType)
		template.StartInTriage = ReconcileBindingSpelling(template.StartInTriage, plan.StartInTriage)
		template.Workspace = ReconcileBindingSpelling(template.Workspace, plan.Workspace)
		reconcileCustomFieldSpelling(template.CustomFields, plan.CustomFields)
	}

	return template
}

// severityFromAPIV1 reuses the v2 severity reconciliation logic by converting
// the v1 severity binding (structurally identical) to its v2 form.
func severityFromAPIV1(severity *client.IncidentTemplateSeverityBindingV1, plan types.Object) types.Object {
	if severity == nil {
		return SeverityObjectNull()
	}

	return SeverityFromAPI(convertEngineType[*client.AlertRouteSeverityBindingV2](severity), plan)
}

// severityToPayloadV1 mirrors the v2 severity payload into the v1 shape.
func severityToPayloadV1(ctx context.Context, severityObj types.Object) *client.IncidentTemplateSeverityBindingPayloadV1 {
	v2 := SeverityToPayload(ctx, severityObj)
	if v2 == nil {
		return nil
	}

	return convertEngineType[*client.IncidentTemplateSeverityBindingPayloadV1](v2)
}

// ToConfigPayload builds the IncidentTemplateConfigPayloadV1 for create/update.
func (t IncidentTemplateConfigV1Model) ToConfigPayload(ctx context.Context) client.IncidentTemplateConfigPayloadV1 {
	payload := client.IncidentTemplateConfigPayloadV1{}

	if t.Name != nil {
		nameParamBinding := t.Name.ToParamBinding()
		payload.Name = createAutoGeneratedBindingV1(&nameParamBinding, t.Name.Autogenerated)
	} else {
		payload.Name = createAutoGeneratedBindingV1(nil, types.BoolValue(false))
	}

	if t.Summary != nil {
		summaryParamBinding := t.Summary.ToParamBinding()
		summaryPayload := createAutoGeneratedBindingV1(&summaryParamBinding, t.Summary.Autogenerated)
		payload.Summary = &summaryPayload
	}

	if t.IncidentMode != nil {
		binding := paramBindingToV3Payload(*t.IncidentMode)
		payload.IncidentMode = &client.IncidentTemplateBindingPayloadV1{Binding: &binding}
	}

	if t.IncidentType != nil {
		binding := paramBindingToV3Payload(*t.IncidentType)
		payload.IncidentType = &client.IncidentTemplateBindingPayloadV1{Binding: &binding}
	}

	if t.StartInTriage != nil {
		binding := paramBindingToV3Payload(*t.StartInTriage)
		payload.StartInTriage = &client.IncidentTemplateBindingPayloadV1{Binding: &binding}
	}

	if t.Workspace != nil {
		binding := paramBindingToV3Payload(*t.Workspace)
		payload.Workspace = &client.IncidentTemplateBindingPayloadV1{Binding: &binding}
	}

	payload.Severity = severityToPayloadV1(ctx, t.Severity)

	if t.CustomFields != nil {
		customFields := []client.IncidentTemplateCustomFieldBindingPayloadV1{}
		for _, cf := range t.CustomFields {
			if cf.Binding == nil {
				continue
			}

			customFields = append(customFields, client.IncidentTemplateCustomFieldBindingPayloadV1{
				CustomFieldId: cf.CustomFieldID.ValueString(),
				Binding:       paramBindingToV3Payload(*cf.Binding),
				MergeStrategy: client.IncidentTemplateCustomFieldBindingPayloadV1MergeStrategy(cf.MergeStrategy.ValueString()),
			})
		}
		payload.CustomFields = &customFields
	}

	return payload
}

// ExpressionsPayload converts the model's expressions into the V3 payload the
// incident-template API expects. Returns nil when there are none, so the
// omitempty field is left out.
func (m IncidentTemplateV1Model) ExpressionsPayload() *[]client.ExpressionPayloadV3 {
	if len(m.Expressions) == 0 {
		return nil
	}

	expressions := expressionsToV3Payload(m.Expressions)
	return &expressions
}
