## References a standalone incident_incident_template instead of defining the
## template inline. This is the better option when several routes should share
## one template: edit the template once and every route that references it picks
## up the change.

resource "incident_incident_template" "payments" {
  name        = "Payments incidents"
  expressions = []

  template = {
    name = {
      autogenerated = false
      value = {
        literal = "Payments incident"
      }
    }
    summary = {
      autogenerated = true
    }
    severity = {
      merge_strategy = "max"
    }
  }
}

resource "incident_alert_route" "payments_alerts" {
  name       = "Payments alerts"
  enabled    = true
  is_private = false

  alert_sources = [
    {
      alert_source_id  = incident_alert_source.http.id
      condition_groups = []
    }
  ]

  condition_groups = []
  expressions      = []

  // grouping_config selects the current configuration format for this route.
  grouping_config = {
    default = {
      enabled        = true
      grouping_keys  = []
      window_seconds = 300
      window_type    = "rolling"
    }
  }

  message_config = {
    destinations = [
      {
        condition_groups = []
        slack_targets = {
          binding = {
            array_value = [
              {
                literal = "C01234567"
              }
            ]
          }
          channel_visibility   = "public"
          group_alerts_summary = true
        }
      }
    ]
  }

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets = [
      {
        escalation_paths = {
          array_value = [
            {
              literal = "01JPQNFD3RWAAY2V83QQ80D1ZV"
            }
          ]
        }
      }
    ]
  }

  incident_config = {
    auto_decline_enabled = false
    enabled              = true
    condition_groups     = []

    // Reference a standalone incident template by ID rather than defining one
    // inline under template. The referenced template is applied to incidents
    // this route creates. Only one of incident_template or template may be set.
    incident_template = {
      value = {
        literal = incident_incident_template.payments.id
      }
    }
  }
}
