resource "incident_alert_route" "service_alerts" {
  name       = "Testing Alert Routes"
  enabled    = true
  is_private = false

  alert_sources = [
    {
      alert_source_id  = incident_alert_source.http.id
      condition_groups = []
    }
  ]

  condition_groups = [
    {
      conditions = [
        {
          subject        = "alert.title"
          operation      = "is_set"
          param_bindings = []
        }
      ]
    }
  ]

  expressions = []

  channel_config = []

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets = [
      {
        escalation_paths = {
          array_value = [
            {
              literal = "01JPQNFD3RWAAY2V83QQ80D1ZV"
            }
          ]
        }
        # Users field can be included if needed
      }
    ]
  }

  incident_config = {
    auto_decline_enabled = false
    enabled              = true
    condition_groups     = []
    defer_time_seconds   = 300
    grouping_keys        = []
  }

  incident_template = {
    custom_fields = []
    name = {
      array_value = []
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Title"
                    missing = false
                    name    = "alert.title"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }
    name_autogenerated = false
    summary = {
      array_value = []
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Description"
                    missing = false
                    name    = "alert.description"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }
    summary_autogenerated = false
    start_in_triage = {
      array_value = []
      value = {
        literal = "true"
      }
    }
    severity = {
      merge_strategy = "first-wins"
    }
  }
}