package provider

import (
	"maps"
	"slices"
	"testing"
)

// Acceptance tests run in families, and this file is where the families are defined.
//
// These tests create real resources in one shared organisation, so two of them can collide
// in ways a unit test never does: by wanting the same resource name, by upserting the same
// external ID, by competing for a rank or a shortform, or by writing the same
// organisation-wide config. Tests in the same family therefore run one at a time, and it is
// the families that run alongside each other.
//
// That is also why they are subtests rather than top-level tests. `go test -parallel` counts
// tests that are running, and a test waiting on a lock is still running, so serialising a
// family with a mutex would spend the budget on tests that are only blocked. Making the
// family the unit of parallelism spends it on families instead.
//
// To run a single test, match it as a subtest of whichever family it lives in:
//
//     make testacc TESTARGS=-run=/IncidentEscalationPathResource
//
// A new acceptance test belongs to the family that owns the resource it exercises. Name it
// accXxx rather than TestAccXxx, and add it below — a top-level TestAccXxx would escape its
// family and run against everything else at once.
//
// The families are declared longest-running first. Go starts top-level tests in source
// order, so this keeps the slowest families from being picked up last and left running alone
// at the end. It is a scheduling hint only, and nothing breaks if it drifts out of date.

// runFamily runs a family's tests one at a time, while letting other families run alongside.
// The order is fixed rather than a map's, so a run is reproducible.
func runFamily(t *testing.T, tests map[string]func(*testing.T)) {
	t.Parallel()

	for _, name := range slices.Sorted(maps.Keys(tests)) {
		t.Run(name, tests[name])
	}
}

// Alert sources, routes and attributes all write the same organisation-wide alert config,
// and concurrent writes to it contend on a single version.
func TestAcceptanceAlerts(t *testing.T) {
	runFamily(t, map[string]func(*testing.T){
		"AlertAttributeResource":                                   accAlertAttributeResource,
		"AlertAttributeResourceWithRequired":                       accAlertAttributeResourceWithRequired,
		"AlertSourceAttributeBeta":                                 accAlertSourceAttributeBeta,
		"AlertSourceBeta":                                          accAlertSourceBeta,
		"AlertSourceResource":                                      accAlertSourceResource,
		"AlertSourceResourceOwningTeamIDs":                         accAlertSourceResourceOwningTeamIDs,
		"AlertSourceResource_DynamicAttributes":                    accAlertSourceResourceDynamicAttributes,
		"AlertSourceResource_Email":                                accAlertSourceResourceEmail,
		"AlertSourceResource_HTTPCustomOptions":                    accAlertSourceResourceHTTPCustomOptions,
		"AlertSourceResource_HTTPCustomOptionsComputed":            accAlertSourceResourceHTTPCustomOptionsComputed,
		"AlertSourceResource_Heartbeat":                            accAlertSourceResourceHeartbeat,
		"AlertSourceResource_Issue342_SpuriousMergeStrategy":       accAlertSourceResourceIssue342SpuriousMergeStrategy,
		"AlertSourceResource_Jira":                                 accAlertSourceResourceJira,
		"AlertSourceResource_Private":                              accAlertSourceResourcePrivate,
		"AlertSourceResource_ValidationErrors":                     accAlertSourceResourceValidationErrors,
		"IncidentAlertAttributeDataSource":                         accIncidentAlertAttributeDataSource,
		"IncidentAlertRouteChannelConfig":                          accIncidentAlertRouteChannelConfig,
		"IncidentAlertRouteOperationAlias":                         accIncidentAlertRouteOperationAlias,
		"IncidentAlertRouteResource":                               accIncidentAlertRouteResource,
		"IncidentAlertRouteResourceAutoGeneratedFields":            accIncidentAlertRouteResourceAutoGeneratedFields,
		"IncidentAlertRouteResourceAutoRelateGroupedAlertsOmitted": accIncidentAlertRouteResourceAutoRelateGroupedAlertsOmitted,
		"IncidentAlertRouteResourceAutoRelateGroupedAlertsTrue":    accIncidentAlertRouteResourceAutoRelateGroupedAlertsTrue,
		"IncidentAlertRouteResourceBranchesValidation":             accIncidentAlertRouteResourceBranchesValidation,
		"IncidentAlertRouteResourceCastExpression":                 accIncidentAlertRouteResourceCastExpression,
		"IncidentAlertRouteResourceComprehensive":                  accIncidentAlertRouteResourceComprehensive,
		"IncidentAlertRouteResourceConditionalConfig":              accIncidentAlertRouteResourceConditionalConfig,
		"IncidentAlertRouteResourceEscapedJSONLiteral":             accIncidentAlertRouteResourceEscapedJSONLiteral,
		"IncidentAlertRouteResourceOwningTeamIDs":                  accIncidentAlertRouteResourceOwningTeamIDs,
		"IncidentAlertRouteResourceRawJSONLiteral":                 accIncidentAlertRouteResourceRawJSONLiteral,
		"IncidentAlertRouteV2ToV3Migration":                        accIncidentAlertRouteV2ToV3Migration,
		"IncidentAlertRouteV3Resource":                             accIncidentAlertRouteV3Resource,
		"IncidentAlertRouteV3ResourceBranchesValidation":           accIncidentAlertRouteV3ResourceBranchesValidation,
		"IncidentAlertRouteV3ResourceComprehensive":                accIncidentAlertRouteV3ResourceComprehensive,
		"IncidentAlertRouteV3ResourceGroupingValidation":           accIncidentAlertRouteV3ResourceGroupingValidation,
		"IncidentAlertRouteV3ResourceIncidentTemplateValidation":   accIncidentAlertRouteV3ResourceIncidentTemplateValidation,
		"IncidentAlertSourceDataSource":                            accIncidentAlertSourceDataSource,
		"IncidentAlertSourcesDataSource":                           accIncidentAlertSourcesDataSource,
		"IncidentCustomFieldsAlphabeticalOrder":                    accIncidentCustomFieldsAlphabeticalOrder,
	})
}

// Catalog entries are upserted by external ID, so two tests naming the same one adopt each
// other's entry rather than creating their own.
func TestAcceptanceCatalogEntries(t *testing.T) {
	runFamily(t, map[string]func(*testing.T){
		"IncidentCatalogEntriesDataSource":                       accIncidentCatalogEntriesDataSource,
		"IncidentCatalogEntriesDataSource_Empty":                 accIncidentCatalogEntriesDataSourceEmpty,
		"IncidentCatalogEntriesDataSource_WithAliases":           accIncidentCatalogEntriesDataSourceWithAliases,
		"IncidentCatalogEntriesResource":                         accIncidentCatalogEntriesResource,
		"IncidentCatalogEntriesResourceWithManagedAttributes":    accIncidentCatalogEntriesResourceWithManagedAttributes,
		"IncidentCatalogEntryDataSource":                         accIncidentCatalogEntryDataSource,
		"IncidentCatalogEntryResource":                           accIncidentCatalogEntryResource,
		"IncidentCatalogEntryResourceManagedAttributesDestroy":   accIncidentCatalogEntryResourceManagedAttributesDestroy,
		"IncidentCatalogEntryResourceWithAlias":                  accIncidentCatalogEntryResourceWithAlias,
		"IncidentCatalogEntryResourceWithEmptyManagedAttributes": accIncidentCatalogEntryResourceWithEmptyManagedAttributes,
		"IncidentCatalogEntryResourceWithManagedAttributes":      accIncidentCatalogEntryResourceWithManagedAttributes,
	})
}

func TestAcceptanceWorkflows(t *testing.T) {
	runFamily(t, map[string]func(*testing.T){
		"IncidentWorkflowDataSource":                      accIncidentWorkflowDataSource,
		"IncidentWorkflowResource":                        accIncidentWorkflowResource,
		"IncidentWorkflowResourceConditionGroupsExample":  accIncidentWorkflowResourceConditionGroupsExample,
		"IncidentWorkflowResourceFormFieldIDsFollowKeys":  accIncidentWorkflowResourceFormFieldIDsFollowKeys,
		"IncidentWorkflowResourceFormFields":              accIncidentWorkflowResourceFormFields,
		"IncidentWorkflowResourceFormFieldsInStepExample": accIncidentWorkflowResourceFormFieldsInStepExample,
		"IncidentWorkflowResourceInviteUserExample":       accIncidentWorkflowResourceInviteUserExample,
		"IncidentWorkflowResourceOwningTeamFromCatalog":   accIncidentWorkflowResourceOwningTeamFromCatalog,
		"IncidentWorkflowResourceOwningTeamIDs":           accIncidentWorkflowResourceOwningTeamIDs,
		"IncidentWorkflowResourcePrivateIncidentScope":    accIncidentWorkflowResourcePrivateIncidentScope,
		"IncidentWorkflowResourcePrivateScopeConflict":    accIncidentWorkflowResourcePrivateScopeConflict,
		"IncidentWorkflowResourceSlackPostMessageExample": accIncidentWorkflowResourceSlackPostMessageExample,
		"IncidentWorkflowResourceStatusChangedExample":    accIncidentWorkflowResourceStatusChangedExample,
	})
}

func TestAcceptanceEscalationPaths(t *testing.T) {
	runFamily(t, map[string]func(*testing.T){
		"IncidentEscalationPathDataSource":               accIncidentEscalationPathDataSource,
		"IncidentEscalationPathExceedsMaxDepth":          accIncidentEscalationPathExceedsMaxDepth,
		"IncidentEscalationPathMaxDepth":                 accIncidentEscalationPathMaxDepth,
		"IncidentEscalationPathReassignment":             accIncidentEscalationPathReassignment,
		"IncidentEscalationPathResource":                 accIncidentEscalationPathResource,
		"IncidentEscalationPathRetryConfig":              accIncidentEscalationPathRetryConfig,
		"IncidentEscalationPathSelectedRotaID":           accIncidentEscalationPathSelectedRotaID,
		"IncidentEscalationPathSelectedRotaIDValidation": accIncidentEscalationPathSelectedRotaIDValidation,
		"IncidentEscalationPathTargetValidation":         accIncidentEscalationPathTargetValidation,
		"IncidentEscalationPathTeamIDs":                  accIncidentEscalationPathTeamIDs,
		"IncidentEscalationPathUnknownValues":            accIncidentEscalationPathUnknownValues,
	})
}

func TestAcceptanceCustomFields(t *testing.T) {
	runFamily(t, map[string]func(*testing.T){
		"IncidentCustomFieldDataSource":             accIncidentCustomFieldDataSource,
		"IncidentCustomFieldOptionDataSource":       accIncidentCustomFieldOptionDataSource,
		"IncidentCustomFieldOptionResource":         accIncidentCustomFieldOptionResource,
		"IncidentCustomFieldResource":               accIncidentCustomFieldResource,
		"IncidentCustomFieldResource_BothFilters":   accIncidentCustomFieldResourceBothFilters,
		"IncidentCustomFieldResource_CatalogBacked": accIncidentCustomFieldResourceCatalogBacked,
		"IncidentCustomFieldResource_FieldTypes":    accIncidentCustomFieldResourceFieldTypes,
	})
}

func TestAcceptanceCatalogTypes(t *testing.T) {
	runFamily(t, map[string]func(*testing.T){
		"IncidentCatalogTypeAttributeDataSource":                     accIncidentCatalogTypeAttributeDataSource,
		"IncidentCatalogTypeAttributeResource":                       accIncidentCatalogTypeAttributeResource,
		"IncidentCatalogTypeAttributeResourceImportMissingAttribute": accIncidentCatalogTypeAttributeResourceImportMissingAttribute,
		"IncidentCatalogTypeDataSource":                              accIncidentCatalogTypeDataSource,
		"IncidentCatalogTypeResource":                                accIncidentCatalogTypeResource,
		"IncidentCatalogTypeResourceOwningTeams":                     accIncidentCatalogTypeResourceOwningTeams,
	})
}

func TestAcceptanceSchedules(t *testing.T) {
	runFamily(t, map[string]func(*testing.T){
		"IncidentScheduleDataSource":                        accIncidentScheduleDataSource,
		"IncidentScheduleResource":                          accIncidentScheduleResource,
		"IncidentScheduleResourceDuplicateRotationID":       accIncidentScheduleResourceDuplicateRotationID,
		"IncidentScheduleResourceHolidayConfig":             accIncidentScheduleResourceHolidayConfig,
		"IncidentScheduleResourceInvalidTimestamp":          accIncidentScheduleResourceInvalidTimestamp,
		"IncidentScheduleResourceNonCanonicalTimestamps":    accIncidentScheduleResourceNonCanonicalTimestamps,
		"IncidentScheduleResourceRotationUpdates":           accIncidentScheduleResourceRotationUpdates,
		"IncidentScheduleResourceTimezoneUpdate":            accIncidentScheduleResourceTimezoneUpdate,
		"IncidentScheduleSyncRuleResource":                  accIncidentScheduleSyncRuleResource,
		"IncidentScheduleSyncRuleResource_InvalidImportID":  accIncidentScheduleSyncRuleResourceInvalidImportID,
		"IncidentScheduleSyncRuleResource_PermanentMembers": accIncidentScheduleSyncRuleResourcePermanentMembers,
		"IncidentScheduleSyncRuleResource_Rotation":         accIncidentScheduleSyncRuleResourceRotation,
		"IncidentScheduleSyncTargetResource":                accIncidentScheduleSyncTargetResource,
	})
}

func TestAcceptancePolicies(t *testing.T) {
	runFamily(t, map[string]func(*testing.T){
		"IncidentPolicyDataSource":         accIncidentPolicyDataSource,
		"IncidentPolicyOnCallReadiness":    accIncidentPolicyOnCallReadiness,
		"IncidentPolicyPostMortem":         accIncidentPolicyPostMortem,
		"IncidentPolicyTypeChangeReplaces": accIncidentPolicyTypeChangeReplaces,
	})
}

func TestAcceptanceMaintenanceWindows(t *testing.T) {
	runFamily(t, map[string]func(*testing.T){
		"IncidentMaintenanceWindowResource":                   accIncidentMaintenanceWindowResource,
		"IncidentMaintenanceWindowResourceInvalidTimestamp":   accIncidentMaintenanceWindowResourceInvalidTimestamp,
		"IncidentMaintenanceWindowResourceWithOptionalFields": accIncidentMaintenanceWindowResourceWithOptionalFields,
	})
}

// Roles are unique by shortform, which is a second way for two of them to collide.
func TestAcceptanceRoles(t *testing.T) {
	runFamily(t, map[string]func(*testing.T){
		"IncidentRoleDataSource":                accIncidentRoleDataSource,
		"IncidentRoleDataSourceAmbiguousLookup": accIncidentRoleDataSourceAmbiguousLookup,
		"IncidentRoleResource":                  accIncidentRoleResource,
	})
}

func TestAcceptanceStatuses(t *testing.T) {
	runFamily(t, map[string]func(*testing.T){
		"IncidentStatusDataSource":                accIncidentStatusDataSource,
		"IncidentStatusDataSourceAmbiguousLookup": accIncidentStatusDataSourceAmbiguousLookup,
		"IncidentStatusResource":                  accIncidentStatusResource,
	})
}

func TestAcceptanceIncidentTemplates(t *testing.T) {
	runFamily(t, map[string]func(*testing.T){
		"IncidentIncidentTemplateDataSource":                accIncidentIncidentTemplateDataSource,
		"IncidentIncidentTemplateDataSourceAmbiguousLookup": accIncidentIncidentTemplateDataSourceAmbiguousLookup,
		"IncidentTemplateResource":                          accIncidentTemplateResource,
	})
}

// Severities are ordered by rank, which is organisation-wide rather than per-test.
func TestAcceptanceSeverities(t *testing.T) {
	runFamily(t, map[string]func(*testing.T){
		"IncidentSeverityResource":            accIncidentSeverityResource,
		"IncidentSeverityResourceWithoutRank": accIncidentSeverityResourceWithoutRank,
	})
}

func TestAcceptanceTimestamps(t *testing.T) {
	runFamily(t, map[string]func(*testing.T){
		"IncidentTimestampDataSource":                accIncidentTimestampDataSource,
		"IncidentTimestampDataSourceAmbiguousLookup": accIncidentTimestampDataSourceAmbiguousLookup,
	})
}

func TestAcceptanceIncidentTypes(t *testing.T) {
	runFamily(t, map[string]func(*testing.T){
		"IncidentIncidentTypesDataSource": accIncidentIncidentTypesDataSource,
	})
}
