package provider

import (
	"fmt"
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
)

func TestAccIncidentAlertRouteV3Resource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: testAccIncidentAlertRouteV3ResourceConfig("test-route-v3"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestMatchResourceAttr("incident_alert_route_v3.test", "id", regexp.MustCompile("^[a-zA-Z0-9]+$")),
					resource.TestCheckResourceAttr("incident_alert_route_v3.test", "name", "test-route-v3"),
					resource.TestCheckResourceAttr("incident_alert_route_v3.test", "enabled", "true"),
					resource.TestCheckResourceAttr("incident_alert_route_v3.test", "is_private", "false"),
					// Grouping config lives at the top level in v3.
					resource.TestCheckResourceAttr("incident_alert_route_v3.test", "grouping_config.default.enabled", "false"),
					resource.TestCheckResourceAttr("incident_alert_route_v3.test", "grouping_config.default.window_type", "rolling"),
				),
			},
			// Refresh and ensure there's no perpetual diff.
			{
				RefreshState: true,
				PlanOnly:     true,
				RefreshPlanChecks: resource.RefreshPlanChecks{
					PostRefresh: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
			},
			// ImportState testing
			{
				ResourceName:      "incident_alert_route_v3.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
			// Update testing
			{
				Config: testAccIncidentAlertRouteV3ResourceConfig("test-route-v3-updated"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("incident_alert_route_v3.test", "name", "test-route-v3-updated"),
				),
			},
		},
	})
}

func TestAccIncidentAlertRouteV3ResourceComprehensive(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccIncidentAlertRouteV3ResourceConfigComprehensive("comprehensive-test-route-v3"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestMatchResourceAttr("incident_alert_route_v3.comprehensive", "id", regexp.MustCompile("^[a-zA-Z0-9]+$")),
					resource.TestCheckResourceAttr("incident_alert_route_v3.comprehensive", "name", "comprehensive-test-route-v3"),

					// Alert sources.
					resource.TestCheckResourceAttrSet("incident_alert_route_v3.comprehensive", "alert_sources.0.alert_source_id"),

					// Grouping config.
					resource.TestCheckResourceAttr("incident_alert_route_v3.comprehensive", "grouping_config.default.enabled", "true"),
					resource.TestCheckResourceAttr("incident_alert_route_v3.comprehensive", "grouping_config.default.window_seconds", "1800"),
					resource.TestCheckResourceAttr("incident_alert_route_v3.comprehensive", "grouping_config.default.window_type", "fixed"),

					// Message config (destinations).
					resource.TestCheckResourceAttr("incident_alert_route_v3.comprehensive", "message_config.destinations.#", "1"),
					resource.TestCheckResourceAttr("incident_alert_route_v3.comprehensive", "message_config.destinations.0.slack_targets.channel_visibility", "public"),

					// Escalation config with when_alert_joins_group.
					resource.TestCheckResourceAttr("incident_alert_route_v3.comprehensive", "escalation_config.when_alert_joins_group.mode", "on_priority_increase"),
					resource.TestCheckResourceAttr("incident_alert_route_v3.comprehensive", "escalation_config.when_alert_joins_group.grace_period_seconds", "60"),

					// Incident config and nested template.
					resource.TestCheckResourceAttr("incident_alert_route_v3.comprehensive", "incident_config.auto_decline_enabled", "false"),
					resource.TestCheckResourceAttr("incident_alert_route_v3.comprehensive", "incident_config.enabled", "true"),
					resource.TestCheckResourceAttr("incident_alert_route_v3.comprehensive", "incident_config.template.name.autogenerated", "true"),
					resource.TestCheckResourceAttrSet("incident_alert_route_v3.comprehensive", "incident_config.template.name.value.literal"),
					resource.TestCheckResourceAttr("incident_alert_route_v3.comprehensive", "incident_config.template.severity.merge_strategy", "first-wins"),
					resource.TestCheckResourceAttr("incident_alert_route_v3.comprehensive", "incident_config.template.custom_fields.0.merge_strategy", "first-wins"),
					resource.TestCheckResourceAttr("incident_alert_route_v3.comprehensive", "incident_config.template.custom_fields.0.binding.value.literal", "Test incident"),
				),
			},
			// Refresh and ensure there's no perpetual diff on the full config.
			{
				RefreshState: true,
				PlanOnly:     true,
				RefreshPlanChecks: resource.RefreshPlanChecks{
					PostRefresh: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
			},
			// ImportState testing.
			{
				ResourceName:      "incident_alert_route_v3.comprehensive",
				ImportState:       true,
				ImportStateVerify: true,
			},
			// Update testing.
			{
				Config: testAccIncidentAlertRouteV3ResourceConfigComprehensive("comprehensive-test-route-v3-updated"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("incident_alert_route_v3.comprehensive", "name", "comprehensive-test-route-v3-updated"),
				),
			},
		},
	})
}

// TestAccIncidentAlertRouteV3ResourceBranchesValidation tests that expressions
// using branches operations with a non-"." root_reference are rejected at plan
// time, mirroring the v2 behaviour.
func TestAccIncidentAlertRouteV3ResourceBranchesValidation(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config:      testAccIncidentAlertRouteV3ResourceConfigInvalidBranches(),
				PlanOnly:    true,
				ExpectError: regexp.MustCompile(`Invalid root_reference for branches operation`),
			},
		},
	})
}

// alertRouteV3IncidentTemplateBlock is a minimal, valid v3 incident template
// using non-autogenerated name and summary literals.
const alertRouteV3IncidentTemplateBlock = `
    template = {
      custom_fields = []
      name = {
        autogenerated = false
        value = {
          literal = jsonencode({
            content = [
              {
                content = [
                  {
                    attrs = {
                      label   = "Alert → Title"
                      missing = false
                      name    = "alert.title"
                    }
                    type = "varSpec"
                  }
                ]
                type = "paragraph"
              }
            ]
            type = "doc"
          })
        }
      }
      summary = {
        autogenerated = false
        value = {
          literal = jsonencode({
            content = [
              {
                content = [
                  {
                    attrs = {
                      label   = "Alert → Description"
                      missing = false
                      name    = "alert.description"
                    }
                    type = "varSpec"
                  }
                ]
                type = "paragraph"
              }
            ]
            type = "doc"
          })
        }
      }
      severity = {
        merge_strategy = "first-wins"
      }
    }`

func testAccIncidentAlertRouteV3ResourceConfig(name string) string {
	return fmt.Sprintf(`
resource "incident_alert_route_v3" "test" {
  name       = %[1]q
  enabled    = true
  is_private = false

  alert_sources    = []
  condition_groups = []
  expressions      = []

  grouping_config = {
    default = {
      enabled        = false
      group_keys     = []
      window_seconds = 0
      window_type    = "rolling"
    }
  }

  message_config = {
    destinations = []
  }

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets      = []
  }

  incident_config = {
    auto_decline_enabled = true
    enabled              = true
    condition_groups     = []
%[2]s
  }
}
`, name, alertRouteV3IncidentTemplateBlock)
}

func testAccIncidentAlertRouteV3ResourceConfigComprehensive(name string) string {
	return fmt.Sprintf(`
resource "incident_custom_field" "type_field" {
  name        = "Test Type Field V3 %[1]s"
  description = "The type of the incident."
  field_type  = "text"
}

resource "incident_alert_source" "http_test" {
  name        = "HTTP Test Alert Source V3 %[1]s"
  source_type = "http"
  template = {
    title = {
      literal = jsonencode({
        content = [
          {
            content = [
              {
                attrs = {
                  label   = "Payload → Title"
                  missing = false
                  name    = "title"
                }
                type = "varSpec"
              },
            ]
            type = "paragraph"
          },
        ]
        type = "doc"
      })
    }
    description = {
      literal = jsonencode({
        content = [
          {
            content = [
              {
                attrs = {
                  label   = "Payload → Description"
                  missing = false
                  name    = "description"
                }
                type = "varSpec"
              },
            ]
            type = "paragraph"
          },
        ]
        type = "doc"
      })
    }
    attributes  = []
    expressions = []
  }
}

resource "incident_alert_route_v3" "comprehensive" {
  name       = %[1]q
  enabled    = true
  is_private = false

  alert_sources = [
    {
      alert_source_id  = incident_alert_source.http_test.id
      condition_groups = []
    }
  ]

  condition_groups = [
    {
      conditions = [
        {
          subject        = "alert.title"
          operation      = "is_set"
          param_bindings = []
        }
      ]
    }
  ]

  expressions = []

  grouping_config = {
    default = {
      enabled        = true
      group_keys     = []
      window_seconds = 1800
      window_type    = "fixed"
    }
  }

  message_config = {
    destinations = [
      {
        condition_groups = []
        slack_targets = {
          channel_visibility = "public"
          binding = {
            value = {
              literal = %[2]q
            }
          }
        }
      }
    ]
  }

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets      = []
    when_alert_joins_group = {
      mode                 = "on_priority_increase"
      grace_period_seconds = 60
    }
  }

  incident_config = {
    auto_decline_enabled = false
    enabled              = true
    condition_groups     = []
    template = {
      custom_fields = [
        {
          custom_field_id = incident_custom_field.type_field.id
          merge_strategy  = "first-wins"
          binding = {
            value = {
              literal = "Test incident"
            }
          }
        }
      ]
      name = {
        autogenerated = true
        value = {
          literal = jsonencode({
            content = [
              {
                content = [
                  {
                    attrs = {
                      label   = "Alert → Title"
                      missing = false
                      name    = "alert.title"
                    }
                    type = "varSpec"
                  }
                ]
                type = "paragraph"
              }
            ]
            type = "doc"
          })
        }
      }
      summary = {
        autogenerated = true
        value = {
          literal = jsonencode({
            content = [
              {
                content = [
                  {
                    attrs = {
                      label   = "Alert → Description"
                      missing = false
                      name    = "alert.description"
                    }
                    type = "varSpec"
                  }
                ]
                type = "paragraph"
              }
            ]
            type = "doc"
          })
        }
      }
      start_in_triage = {
        value = {
          literal = "true"
        }
      }
      severity = {
        merge_strategy = "first-wins"
      }
    }
  }
}
`, name, channelID(true))
}

func testAccIncidentAlertRouteV3ResourceConfigInvalidBranches() string {
	return fmt.Sprintf(`
resource "incident_alert_route_v3" "invalid_branches" {
  name       = "invalid-branches-test-v3"
  enabled    = true
  is_private = false

  alert_sources    = []
  condition_groups = []

  # Invalid: a branches operation requires root_reference to be ".".
  expressions = [
    {
      label          = "Test Expression"
      reference      = "test-expr"
      root_reference = "alert.attributes.some-attribute-id"
      operations = [
        {
          operation_type = "branches"
          branches = {
            returns = {
              type  = "IncidentSeverity"
              array = false
            }
            branches = [
              {
                condition_groups = [
                  {
                    conditions = [
                      {
                        subject        = "alert.title"
                        operation      = "is_set"
                        param_bindings = []
                      }
                    ]
                  }
                ]
                result = {
                  value = {
                    literal = "01ABC123"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  ]

  grouping_config = {
    default = {
      enabled        = false
      group_keys     = []
      window_seconds = 0
      window_type    = "rolling"
    }
  }

  message_config = {
    destinations = []
  }

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets      = []
  }

  incident_config = {
    auto_decline_enabled = true
    enabled              = true
    condition_groups     = []
%[1]s
  }
}
`, alertRouteV3IncidentTemplateBlock)
}
