package provider

import (
	"context"
	"fmt"
	"net/http"
	"net/http/httptest"
	"regexp"
	"strings"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/samber/lo"
	"github.com/stretchr/testify/require"

	"github.com/incident-io/terraform-provider-incident/v6/internal/client"
	"github.com/incident-io/terraform-provider-incident/v6/internal/provider/models"
)

func incidentTemplateFixtures() []client.IncidentTemplateV1 {
	return []client.IncidentTemplateV1{
		incidentTemplateFixture("01PAYMENTS", "Payments incidents"),
		incidentTemplateFixture("01SUPPORT", "Support escalations"),
		incidentTemplateFixture("01DEFAULT", "Default"),
	}
}

func incidentTemplateFixture(id, name string) client.IncidentTemplateV1 {
	now := time.Date(2021, 8, 17, 13, 28, 57, 0, time.UTC)
	return client.IncidentTemplateV1{
		Id:        id,
		Name:      name,
		CreatedAt: now,
		UpdatedAt: now,
		Template: client.IncidentTemplateConfigV1{
			Name: client.IncidentTemplateAutoGeneratedBindingV1{
				Autogenerated: false,
				Binding: &client.EngineParamBindingV3{
					Value: &client.EngineParamBindingValueV3{Literal: lo.ToPtr(name)},
				},
			},
			Summary: &client.IncidentTemplateAutoGeneratedBindingV1{
				Autogenerated: true,
			},
			StartInTriage: &client.IncidentTemplateBindingV1{
				Binding: &client.EngineParamBindingV3{
					Value: &client.EngineParamBindingValueV3{Literal: lo.ToPtr("true")},
				},
			},
			Severity: &client.IncidentTemplateSeverityBindingV1{
				MergeStrategy: "max",
			},
			CustomFields: &[]client.IncidentTemplateCustomFieldBindingV1{
				{
					CustomFieldId: "01AFFECTED",
					MergeStrategy: "first-wins",
					Binding: client.EngineParamBindingV3{
						Value: &client.EngineParamBindingValueV3{Literal: lo.ToPtr("Payments")},
					},
				},
			},
		},
	}
}

// TestIncidentIncidentTemplateDataSourceSchemaMatchesModel guards the seam between
// the data source schema and IncidentTemplateV1Model. Read reuses FromAPI, so an
// attribute the schema forgets (or types differently) fails State.Set for every
// template read rather than only for templates using it.
func TestIncidentIncidentTemplateDataSourceSchemaMatchesModel(t *testing.T) {
	ctx := t.Context()

	resp := &datasource.SchemaResponse{}
	(&IncidentIncidentTemplateDataSource{}).Schema(ctx, datasource.SchemaRequest{}, resp)
	require.False(t, resp.Diagnostics.HasError(), "schema: %s", resp.Diagnostics)

	state := tfsdk.State{
		Schema: resp.Schema,
		Raw:    tftypes.NewValue(resp.Schema.Type().TerraformType(ctx), nil),
	}
	model := models.IncidentTemplateV1Model{}.FromAPI(incidentTemplateFixture("01PAYMENTS", "Payments incidents"), nil)
	diags := state.Set(ctx, &model)
	require.False(t, diags.HasError(), "state: %s", diags)
}

func TestIncidentIncidentTemplateDataSourceRead(t *testing.T) {
	api, requests := startFakeIncidentTemplatesAPI(t, incidentTemplateFixtures(), 50)

	t.Run("by id", func(t *testing.T) {
		model, resp := readIncidentTemplate(t, api, "01SUPPORT", "")
		if resp.Diagnostics.HasError() {
			t.Fatalf("unexpected diagnostics: %v", resp.Diagnostics.Errors())
		}
		if got, want := model.Name.ValueString(), "Support escalations"; got != want {
			t.Errorf("got name %q, want %q", got, want)
		}
		if model.Template == nil || model.Template.Name == nil {
			t.Fatal("expected template.name to be set")
		}
		if got := model.Template.Name.Value.Literal.ValueString(); got != "Support escalations" {
			t.Errorf("got template.name.value.literal %q, want Support escalations", got)
		}
	})

	t.Run("by name", func(t *testing.T) {
		model, resp := readIncidentTemplate(t, api, "", "Default")
		if resp.Diagnostics.HasError() {
			t.Fatalf("unexpected diagnostics: %v", resp.Diagnostics.Errors())
		}
		if got, want := model.ID.ValueString(), "01DEFAULT"; got != want {
			t.Errorf("got id %q, want %q", got, want)
		}
	})

	t.Run("a name that matches nothing says so", func(t *testing.T) {
		_, resp := readIncidentTemplate(t, api, "", "Never going to match")
		assertIncidentTemplateError(t, resp, `no incident template found with name "Never going to match"`)
	})

	t.Run("an id that doesn't exist surfaces the API's error", func(t *testing.T) {
		_, resp := readIncidentTemplate(t, api, "01NONSENSE", "")
		assertIncidentTemplateError(t, resp, "not_found")
	})

	t.Run("a lookup by id makes no list call", func(t *testing.T) {
		before := requests.listCalls
		if _, resp := readIncidentTemplate(t, api, "01PAYMENTS", ""); resp.Diagnostics.HasError() {
			t.Fatalf("unexpected diagnostics: %v", resp.Diagnostics.Errors())
		}
		if requests.listCalls != before {
			t.Errorf("want no list calls, got %d", requests.listCalls-before)
		}
	})
}

func TestIncidentIncidentTemplateDataSourceReadPagesToFindAName(t *testing.T) {
	api, requests := startFakeIncidentTemplatesAPI(t, incidentTemplateFixtures(), 1)

	model, resp := readIncidentTemplate(t, api, "", "Default")
	if resp.Diagnostics.HasError() {
		t.Fatalf("unexpected diagnostics: %v", resp.Diagnostics.Errors())
	}
	if got, want := model.ID.ValueString(), "01DEFAULT"; got != want {
		t.Errorf("got id %q, want %q", got, want)
	}
	if requests.listCalls != 3 {
		t.Errorf("want 3 list calls to reach the third page, got %d", requests.listCalls)
	}
}

func TestIncidentIncidentTemplateDataSourceReadStopsAtTheLastPage(t *testing.T) {
	api, requests := startFakeIncidentTemplatesAPI(t, incidentTemplateFixtures(), 1)

	_, resp := readIncidentTemplate(t, api, "", "Never going to match")
	assertIncidentTemplateError(t, resp, "no incident template found")

	if requests.listCalls != 3 {
		t.Errorf("want exactly 3 list calls for 3 pages, got %d", requests.listCalls)
	}
}

// Nothing stops two templates sharing a name, and returning whichever the API
// ordered first would silently bind the config to the wrong one. Finding the
// second match means the walk also has to continue past the first.
func TestIncidentIncidentTemplateDataSourceReadRejectsDuplicateNames(t *testing.T) {
	templates := []client.IncidentTemplateV1{
		incidentTemplateFixture("01FIRST", "Payments incidents"),
		incidentTemplateFixture("01OTHER", "Support escalations"),
		incidentTemplateFixture("01SECOND", "Payments incidents"),
	}
	api, requests := startFakeIncidentTemplatesAPI(t, templates, 1)

	_, resp := readIncidentTemplate(t, api, "", "Payments incidents")
	assertIncidentTemplateError(t, resp, `found 2 incident templates named "Payments incidents"`)

	if requests.listCalls != 3 {
		t.Errorf("want 3 list calls, so a match on the first page doesn't end the walk, got %d", requests.listCalls)
	}
}

func TestIncidentIncidentTemplateDataSourceValidateConfig(t *testing.T) {
	for _, tc := range []struct {
		name    string
		id      string
		lookup  string
		wantErr string
	}{
		{name: "id only", id: "01PAYMENTS"},
		{name: "name only", lookup: "Payments incidents"},
		{name: "both", id: "01PAYMENTS", lookup: "Payments incidents", wantErr: "Ambiguous lookup"},
		{name: "neither", wantErr: "Missing lookup"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			ctx := t.Context()
			d := &IncidentIncidentTemplateDataSource{}
			schemaResp := incidentTemplateDataSourceSchema(t, d)

			resp := &datasource.ValidateConfigResponse{}
			d.ValidateConfig(ctx, datasource.ValidateConfigRequest{
				Config: tfsdk.Config{
					Schema: schemaResp.Schema,
					Raw:    incidentTemplateDataSourceConfig(t, ctx, schemaResp, tc.id, tc.lookup),
				},
			}, resp)

			if tc.wantErr == "" {
				if resp.Diagnostics.HasError() {
					t.Fatalf("unexpected diagnostics: %v", resp.Diagnostics.Errors())
				}
				return
			}

			if !resp.Diagnostics.HasError() {
				t.Fatal("expected an error diagnostic")
			}
			if summary := resp.Diagnostics.Errors()[0].Summary(); summary != tc.wantErr {
				t.Errorf("got summary %q, want %q", summary, tc.wantErr)
			}
		})
	}
}

type incidentTemplateAPIRequests struct {
	listCalls int
}

func startFakeIncidentTemplatesAPI(t *testing.T, templates []client.IncidentTemplateV1, pageSize int) (*client.ClientWithResponses, *incidentTemplateAPIRequests) {
	t.Helper()

	requests := &incidentTemplateAPIRequests{}

	mux := http.NewServeMux()
	mux.HandleFunc("/v1/incident_templates", func(w http.ResponseWriter, r *http.Request) {
		requests.listCalls++

		start := 0
		if after := r.URL.Query().Get("after"); after != "" {
			for idx, template := range templates {
				if template.Id == after {
					start = idx + 1
					break
				}
			}
		}

		end := min(start+pageSize, len(templates))
		page := templates[start:end]

		meta := &client.PaginationMetaResultV1{PageSize: int64(pageSize)}
		if end < len(templates) && len(page) > 0 {
			meta.After = lo.ToPtr(page[len(page)-1].Id)
		}

		writeJSON(t, w, client.IncidentTemplatesListResultV1{IncidentTemplates: page, PaginationMeta: meta})
	})
	mux.HandleFunc("/v1/incident_templates/", func(w http.ResponseWriter, r *http.Request) {
		id := strings.TrimPrefix(r.URL.Path, "/v1/incident_templates/")
		for _, template := range templates {
			if template.Id == id {
				writeJSON(t, w, client.IncidentTemplatesShowResultV1{IncidentTemplate: template})
				return
			}
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		_, _ = w.Write([]byte(`{"type":"not_found","status":404,"detail":"incident template not found"}`))
	})

	server := httptest.NewServer(mux)
	t.Cleanup(server.Close)

	api, err := client.New(t.Context(), "test-key", server.URL, "test")
	if err != nil {
		t.Fatalf("building client: %v", err)
	}

	return api, requests
}

func readIncidentTemplate(t *testing.T, api *client.ClientWithResponses, id, name string) (models.IncidentTemplateV1Model, *datasource.ReadResponse) {
	t.Helper()

	ctx := t.Context()
	d := &IncidentIncidentTemplateDataSource{dataSourceConfigurer: withClientDataSource(api)}

	schemaResp := incidentTemplateDataSourceSchema(t, d)
	resp := &datasource.ReadResponse{
		State: tfsdk.State{
			Schema: schemaResp.Schema,
			Raw:    tftypes.NewValue(schemaResp.Schema.Type().TerraformType(ctx), nil),
		},
	}
	d.Read(ctx, datasource.ReadRequest{
		Config: tfsdk.Config{
			Schema: schemaResp.Schema,
			Raw:    incidentTemplateDataSourceConfig(t, ctx, schemaResp, id, name),
		},
	}, resp)

	var model models.IncidentTemplateV1Model
	if !resp.Diagnostics.HasError() {
		resp.Diagnostics.Append(resp.State.Get(ctx, &model)...)
	}

	return model, resp
}

func incidentTemplateDataSourceSchema(t *testing.T, d *IncidentIncidentTemplateDataSource) datasource.SchemaResponse {
	t.Helper()

	var schemaResp datasource.SchemaResponse
	d.Schema(t.Context(), datasource.SchemaRequest{}, &schemaResp)
	if schemaResp.Diagnostics.HasError() {
		t.Fatalf("building the schema: %v", schemaResp.Diagnostics.Errors())
	}

	return schemaResp
}

func incidentTemplateDataSourceConfig(t *testing.T, ctx context.Context, schemaResp datasource.SchemaResponse, id, name string) tftypes.Value {
	t.Helper()

	tfType, ok := schemaResp.Schema.Type().TerraformType(ctx).(tftypes.Object)
	require.True(t, ok, "the schema's Terraform type is not an object")
	attrs := tfType.AttributeTypes

	attribute := func(value string) tftypes.Value {
		if value == "" {
			return tftypes.NewValue(tftypes.String, nil)
		}

		return tftypes.NewValue(tftypes.String, value)
	}

	return tftypes.NewValue(tfType, map[string]tftypes.Value{
		"id":          attribute(id),
		"name":        attribute(name),
		"expressions": tftypes.NewValue(attrs["expressions"], nil),
		"template":    tftypes.NewValue(attrs["template"], nil),
	})
}

func assertIncidentTemplateError(t *testing.T, resp *datasource.ReadResponse, want string) {
	t.Helper()

	if !resp.Diagnostics.HasError() {
		t.Fatal("expected an error diagnostic")
	}

	err := resp.Diagnostics.Errors()[0]
	joined := fmt.Sprintf("%s | %s", err.Summary(), err.Detail())
	if !strings.Contains(joined, want) {
		t.Errorf("diagnostic %q does not mention %q", joined, want)
	}
}

func accIncidentIncidentTemplateDataSource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccIncidentTemplateResourceConfig("ds-template", "true") + `
data "incident_incident_template" "by_id" {
  id = incident_incident_template.test.id
}

data "incident_incident_template" "by_name" {
  name = incident_incident_template.test.name
}
`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrPair(
						"data.incident_incident_template.by_id", "name",
						"incident_incident_template.test", "name"),
					resource.TestCheckResourceAttrPair(
						"data.incident_incident_template.by_name", "id",
						"incident_incident_template.test", "id"),
					resource.TestCheckResourceAttr(
						"data.incident_incident_template.by_id", "template.name.autogenerated", "false"),
					resource.TestCheckResourceAttr(
						"data.incident_incident_template.by_id", "template.summary.autogenerated", "true"),
					resource.TestCheckResourceAttr(
						"data.incident_incident_template.by_id", "template.start_in_triage.value.literal", "true"),
					resource.TestCheckResourceAttrPair(
						"data.incident_incident_template.by_name", "template.name.value.literal",
						"data.incident_incident_template.by_id", "template.name.value.literal"),
				),
			},
		},
	})
}

func accIncidentIncidentTemplateDataSourceAmbiguousLookup(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: `
data "incident_incident_template" "both" {
  id   = "01FCNDV6P870EA6S7TK1DSYD5H"
  name = "Payments incidents"
}
`,
				ExpectError: regexp.MustCompile("Ambiguous lookup"),
			},
		},
	})
}
