package provider

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/incident-io/terraform-provider-incident/v6/internal/apischema"
	"github.com/incident-io/terraform-provider-incident/v6/internal/client"
	"github.com/incident-io/terraform-provider-incident/v6/internal/provider/models"
)

var (
	_ resource.Resource                = &IncidentIncidentTemplateResource{}
	_ resource.ResourceWithConfigure   = &IncidentIncidentTemplateResource{}
	_ resource.ResourceWithImportState = &IncidentIncidentTemplateResource{}
	_ resource.ResourceWithModifyPlan  = &IncidentIncidentTemplateResource{}
)

type IncidentIncidentTemplateResource struct {
	resourceConfigurer
}

func NewIncidentIncidentTemplateResource() resource.Resource {
	return &IncidentIncidentTemplateResource{}
}

func (r *IncidentIncidentTemplateResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_incident_template"
}

func (r *IncidentIncidentTemplateResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: apischema.TagDocstring("Incident Templates V1"),
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: apischema.Docstring("IncidentTemplateV1", "id"),
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: apischema.Docstring("IncidentTemplateV1", "name"),
			},
			"expressions": models.ExpressionsAttribute(),
			"template": schema.SingleNestedAttribute{
				Required:            true,
				MarkdownDescription: apischema.Docstring("IncidentTemplateV1", "template"),
				Attributes:          incidentTemplateConfigAttributes(),
			},
		},
	}
}

// incidentTemplateConfigAttributes is the attribute set for the incident
// template config. It mirrors the alert-route incident template but adds the
// workspace binding, which a standalone incident template supports.
func incidentTemplateConfigAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"custom_fields": schema.SetNestedAttribute{
			Optional:            true,
			MarkdownDescription: apischema.Docstring("IncidentTemplateConfigV1", "custom_fields"),
			NestedObject: schema.NestedAttributeObject{
				Attributes: map[string]schema.Attribute{
					"custom_field_id": schema.StringAttribute{
						Required:            true,
						MarkdownDescription: apischema.Docstring("IncidentTemplateCustomFieldBindingV1", "custom_field_id"),
					},
					"binding": schema.SingleNestedAttribute{
						Required:            true,
						MarkdownDescription: apischema.Docstring("IncidentTemplateCustomFieldBindingV1", "binding"),
						Attributes:          models.ParamBindingAttributes(),
					},
					"merge_strategy": schema.StringAttribute{
						Required:            true,
						MarkdownDescription: EnumValuesDescription("IncidentTemplateCustomFieldBindingV1", "merge_strategy"),
					},
				},
			},
		},
		"incident_mode": schema.SingleNestedAttribute{
			Optional:            true,
			MarkdownDescription: apischema.Docstring("IncidentTemplateConfigV1", "incident_mode"),
			Attributes:          models.ParamBindingAttributes(),
		},
		"incident_type": schema.SingleNestedAttribute{
			Optional:            true,
			MarkdownDescription: apischema.Docstring("IncidentTemplateConfigV1", "incident_type"),
			Attributes:          models.ParamBindingAttributes(),
		},
		"name": schema.SingleNestedAttribute{
			Required:            true,
			MarkdownDescription: apischema.Docstring("IncidentTemplateConfigV1", "name"),
			Attributes:          models.AutoGeneratedParamBindingAttributes(),
		},
		"severity": schema.SingleNestedAttribute{
			Optional:            true,
			Computed:            true,
			MarkdownDescription: apischema.Docstring("IncidentTemplateConfigV1", "severity"),
			PlanModifiers: []planmodifier.Object{
				objectplanmodifier.UseStateForUnknown(),
			},
			Attributes: map[string]schema.Attribute{
				"binding": schema.SingleNestedAttribute{
					Optional:            true,
					MarkdownDescription: apischema.Docstring("IncidentTemplateSeverityBindingV1", "binding"),
					Attributes:          models.ParamBindingAttributes(),
				},
				"merge_strategy": schema.StringAttribute{
					Required:            true,
					MarkdownDescription: EnumValuesDescription("IncidentTemplateSeverityBindingV1", "merge_strategy"),
				},
			},
		},
		"start_in_triage": schema.SingleNestedAttribute{
			Optional:            true,
			MarkdownDescription: apischema.Docstring("IncidentTemplateConfigV1", "start_in_triage"),
			Attributes:          models.ParamBindingAttributes(),
		},
		"summary": schema.SingleNestedAttribute{
			Optional:            true,
			MarkdownDescription: apischema.Docstring("IncidentTemplateConfigV1", "summary"),
			Attributes:          models.AutoGeneratedParamBindingAttributes(),
		},
		"workspace": schema.SingleNestedAttribute{
			Optional:            true,
			MarkdownDescription: apischema.Docstring("IncidentTemplateConfigV1", "workspace"),
			Attributes:          models.ParamBindingAttributes(),
		},
	}
}

// incidentTemplateValidateTimeout bounds the plan-time template check. Long
// enough that a slow-but-working API still answers, short enough that an
// unhealthy one costs a plan seconds rather than minutes. A var so tests don't
// have to wait it out.
var incidentTemplateValidateTimeout = 10 * time.Second

// ModifyPlan asks the API whether the planned template would be accepted, so a
// broken expression or binding shows up in the plan instead of part way through
// an apply.
//
// It can't live in a ValidateConfig, which is also called by `terraform
// validate` — that runs the provider without configuring it, so there's no
// client to ask with.
func (r *IncidentIncidentTemplateResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	// A destroy plans no template, and an unconfigured provider has no client.
	if r.client == nil || req.Plan.Raw.IsNull() {
		return
	}

	// A template the plan doesn't change isn't going to be applied, so there is
	// nothing to warn about — and checking it on every plan is a request each.
	if req.Plan.Raw.Equal(req.State.Raw) {
		return
	}

	// A binding pointing at, say, a custom field this same apply creates is
	// unknown until it exists. Validating around the gaps would report errors
	// the apply won't hit, so leave those configs alone.
	if !incidentTemplateSettled(req.Plan.Raw) {
		return
	}

	var data models.IncidentTemplateV1Model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The schema makes template required, so this shouldn't happen — but a
	// panic in a plan modifier takes the whole provider down over a check that
	// is only advisory.
	if data.Template == nil {
		return
	}

	// The shared client retries a 5xx ten times with exponential backoff, which
	// is right for a read an apply depends on and far too patient for an
	// advisory check: it would stall a plan for minutes. Give up quickly and
	// warn instead.
	ctx, cancel := context.WithTimeout(ctx, incidentTemplateValidateTimeout)
	defer cancel()

	_, err := r.client.IncidentTemplatesV1ValidateWithResponse(ctx, client.IncidentTemplatesV1ValidateJSONRequestBody{
		Name:        data.Name.ValueString(),
		Template:    data.Template.ToConfigPayload(ctx),
		Expressions: data.ExpressionsPayload(),
	})
	if err == nil {
		return
	}

	// 422 is the API telling us this template is wrong, which is the whole
	// point.
	var httpErr client.HTTPError
	if errors.As(err, &httpErr) && httpErr.StatusCode == http.StatusUnprocessableEntity {
		resp.Diagnostics.AddAttributeError(path.Root("template"),
			"Invalid incident template", httpErr.Error())
		return
	}

	// Anything else means the check didn't run, not that the config is bad: the
	// endpoint isn't deployed yet, the API is down, the request timed out. Warn,
	// because failing here would break plans over a config that may be perfectly
	// good.
	resp.Diagnostics.AddAttributeWarning(path.Root("template"),
		"Could not validate the incident template",
		fmt.Sprintf("The template was not checked, and may still be rejected when you apply: %s", err))
}

// incidentTemplateComputedLeaves are attributes that can sit unknown in the plan
// without meaning we should skip validation: autogenerated (a bool that
// defaults) and severity (Optional+Computed — omitting it leaves the whole block
// unknown, and the API fills it). The payload we send leaves them out too, so
// validation still describes what an apply would do.
//
// merge_strategy is deliberately excluded: it's Required on severity and
// custom_fields, so an unknown value (e.g. from a variable) must leave the
// template unsettled — validating around it would send an empty merge_strategy
// the API rejects with a 422.
var incidentTemplateComputedLeaves = map[string]bool{
	"autogenerated": true,
	"severity":      true,
}

// incidentTemplateSettled reports whether the values validation reads are
// known. A binding pointing at a custom field this same apply creates is
// unknown until it exists, and checking around that reports errors the apply
// won't hit.
func incidentTemplateSettled(plan tftypes.Value) bool {
	var attributes map[string]tftypes.Value
	if err := plan.As(&attributes); err != nil {
		return false
	}

	if !attributes["name"].IsKnown() {
		return false
	}

	settled := true
	for _, root := range []string{"template", "expressions"} {
		err := tftypes.Walk(attributes[root], func(steps *tftypes.AttributePath, value tftypes.Value) (bool, error) {
			if value.IsKnown() {
				return true, nil
			}

			if name, ok := lastAttributeName(steps); ok && incidentTemplateComputedLeaves[name] {
				return false, nil
			}

			settled = false

			return false, nil
		})
		if err != nil {
			return false
		}
	}

	return settled
}

func (r *IncidentIncidentTemplateResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data models.IncidentTemplateV1Model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if data.Template == nil {
		resp.Diagnostics.AddError("Client Error", "template is required")
		return
	}

	result, err := r.client.IncidentTemplatesV1CreateWithResponse(ctx, client.IncidentTemplatesV1CreateJSONRequestBody{
		Name:        data.Name.ValueString(),
		Template:    data.Template.ToConfigPayload(ctx),
		Expressions: data.ExpressionsPayload(),
	})
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create incident template, got error: %s", err))
		return
	}
	if result.JSON201 == nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create incident template, got status: %s", result.Status()))
		return
	}

	claimResource(ctx, r.client, result.JSON201.IncidentTemplate.Id, &resp.Diagnostics, client.ManagedResourcesCreateManagedResourcePayloadV2ResourceTypeIncidentTemplate, r.terraformVersion)

	tflog.Trace(ctx, fmt.Sprintf("created an incident template with id=%s", result.JSON201.IncidentTemplate.Id))

	data = models.IncidentTemplateV1Model{}.FromAPI(result.JSON201.IncidentTemplate, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IncidentIncidentTemplateResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data models.IncidentTemplateV1Model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	result, err := r.client.IncidentTemplatesV1ShowWithResponse(ctx, data.ID.ValueString())
	if err != nil {
		httpErr := client.HTTPError{}
		if errors.As(err, &httpErr) && httpErr.StatusCode == http.StatusNotFound {
			tflog.Warn(ctx, fmt.Sprintf("Incident template with ID %s not found: removing from state.", data.ID.ValueString()))
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read incident template, got error: %s", err))
		return
	}
	if result.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read incident template, got status: %s", result.Status()))
		return
	}

	data = models.IncidentTemplateV1Model{}.FromAPI(result.JSON200.IncidentTemplate, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IncidentIncidentTemplateResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data models.IncidentTemplateV1Model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if data.Template == nil {
		resp.Diagnostics.AddError("Client Error", "template is required")
		return
	}

	result, err := r.client.IncidentTemplatesV1UpdateWithResponse(ctx, data.ID.ValueString(), client.IncidentTemplatesV1UpdateJSONRequestBody{
		Name:        data.Name.ValueString(),
		Template:    data.Template.ToConfigPayload(ctx),
		Expressions: data.ExpressionsPayload(),
	})
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update incident template, got error: %s", err))
		return
	}
	if result.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update incident template, got status: %s", result.Status()))
		return
	}

	claimResource(ctx, r.client, result.JSON200.IncidentTemplate.Id, &resp.Diagnostics, client.ManagedResourcesCreateManagedResourcePayloadV2ResourceTypeIncidentTemplate, r.terraformVersion)

	data = models.IncidentTemplateV1Model{}.FromAPI(result.JSON200.IncidentTemplate, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IncidentIncidentTemplateResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data models.IncidentTemplateV1Model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := r.client.IncidentTemplatesV1DestroyWithResponse(ctx, data.ID.ValueString())
	if err != nil {
		httpErr := client.HTTPError{}
		if errors.As(err, &httpErr) && httpErr.StatusCode == http.StatusNotFound {
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete incident template, got error: %s", err))
		return
	}
}

func (r *IncidentIncidentTemplateResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	claimResourceOnImport(ctx, r.client, req.ID, &resp.Diagnostics, client.ManagedResourcesCreateManagedResourcePayloadV2ResourceTypeIncidentTemplate, r.terraformVersion, r.markImportedAsManaged)
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
