package provider

import (
	"fmt"
	"os"
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
	"github.com/samber/lo"
)

func accIncidentAlertRouteResource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: testAccIncidentAlertRouteResourceConfig("test-route"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestMatchResourceAttr("incident_alert_route.test", "id", regexp.MustCompile("^[a-zA-Z0-9]+$")),
					resource.TestCheckResourceAttr("incident_alert_route.test", "name", StableSuffix("test-route")),
					resource.TestCheckResourceAttr("incident_alert_route.test", "enabled", "true"),
					resource.TestCheckResourceAttr("incident_alert_route.test", "is_private", "false"),
				),
			},
			{
				RefreshState: true,
				PlanOnly:     true,
				RefreshPlanChecks: resource.RefreshPlanChecks{
					PostRefresh: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},

				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("incident_alert_route.test", "name", StableSuffix("test-route")),
					resource.TestCheckResourceAttr("incident_alert_route.test", "enabled", "true"),
					resource.TestCheckResourceAttr("incident_alert_route.test", "is_private", "false"),
				),
			},
			// Update testing
			{
				Config: testAccIncidentAlertRouteResourceConfig("test-route-updated"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("incident_alert_route.test", "name", StableSuffix("test-route-updated")),
				),
			},
		},
	})
}

func accIncidentAlertRouteResourceComprehensive(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing with comprehensive configuration
			{
				Config: testAccIncidentAlertRouteResourceConfigComprehensive("comprehensive-test-route"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestMatchResourceAttr("incident_alert_route.comprehensive", "id", regexp.MustCompile("^[a-zA-Z0-9]+$")),
					resource.TestCheckResourceAttr("incident_alert_route.comprehensive", "name", StableSuffix("comprehensive-test-route")),
					resource.TestCheckResourceAttr("incident_alert_route.comprehensive", "enabled", "true"),
					resource.TestCheckResourceAttr("incident_alert_route.comprehensive", "is_private", "false"),

					// Check alert sources
					resource.TestCheckResourceAttrSet("incident_alert_route.comprehensive", "alert_sources.0.alert_source_id"),

					// Check condition groups
					resource.TestCheckResourceAttr("incident_alert_route.comprehensive", "condition_groups.0.conditions.0.subject", "alert.title"),
					resource.TestCheckResourceAttr("incident_alert_route.comprehensive", "condition_groups.0.conditions.0.operation", "is_set"),

					// Check incident config
					resource.TestCheckResourceAttr("incident_alert_route.comprehensive", "incident_config.auto_decline_enabled", "false"),
					resource.TestCheckResourceAttr("incident_alert_route.comprehensive", "incident_config.auto_relate_grouped_alerts", "false"),
					resource.TestCheckResourceAttr("incident_alert_route.comprehensive", "incident_config.enabled", "true"),
					resource.TestCheckResourceAttr("incident_alert_route.comprehensive", "incident_config.defer_time_seconds", "300"),
					resource.TestCheckResourceAttr("incident_alert_route.comprehensive", "incident_config.grouping_window_seconds", "1800"),

					// Check incident template
					resource.TestCheckResourceAttr("incident_alert_route.comprehensive", "incident_template.name.autogenerated", "true"),
					resource.TestCheckResourceAttrSet("incident_alert_route.comprehensive", "incident_template.name.value.literal"),
					resource.TestCheckResourceAttr("incident_alert_route.comprehensive", "incident_template.summary.autogenerated", "true"),
					resource.TestCheckResourceAttrSet("incident_alert_route.comprehensive", "incident_template.summary.value.literal"),
					resource.TestCheckResourceAttr("incident_alert_route.comprehensive", "incident_template.start_in_triage.value.literal", "true"),
					resource.TestCheckResourceAttr("incident_alert_route.comprehensive", "incident_template.severity.merge_strategy", "first-wins"),

					// Verify custom field was created and has the correct merge strategy
					resource.TestCheckResourceAttrSet("incident_custom_field.type_field", "id"),
					resource.TestCheckResourceAttr("incident_alert_route.comprehensive", "incident_template.custom_fields.0.merge_strategy", "first-wins"),
					resource.TestCheckResourceAttr("incident_alert_route.comprehensive", "incident_template.custom_fields.0.binding.value.literal", "Test incident"),
				),
			},
			// Update testing
			{
				Config: testAccIncidentAlertRouteResourceConfigComprehensive("comprehensive-test-route-updated"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("incident_alert_route.comprehensive", "name", StableSuffix("comprehensive-test-route-updated")),
				),
			},
		},
	})
}

func accIncidentAlertRouteResourceAutoGeneratedFields(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccIncidentAlertRouteResourceConfigAutoGenerated("auto-gen-test", true),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestMatchResourceAttr("incident_alert_route.auto_gen", "id", regexp.MustCompile("^[a-zA-Z0-9]+$")),
					resource.TestCheckResourceAttr("incident_alert_route.auto_gen", "name", StableSuffix("auto-gen-test")),

					resource.TestCheckResourceAttr("incident_alert_route.auto_gen", "incident_template.name.autogenerated", "true"),
					resource.TestCheckResourceAttr("incident_alert_route.auto_gen", "incident_template.summary.autogenerated", "true"),
				),
			},
			{
				Config: testAccIncidentAlertRouteResourceConfigAutoGenerated("auto-gen-test", false),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("incident_alert_route.auto_gen", "incident_template.name.autogenerated", "false"),
					resource.TestCheckResourceAttr("incident_alert_route.auto_gen", "incident_template.summary.autogenerated", "false"),
				),
			},
		},
	})
}

func channelID(withTeam bool) string {
	if os.Getenv("CI") == "true" {
		// This is a channel that exists in our integration test workspace
		return lo.If(withTeam, "T04TJRY5UMB/C04U0DJSG0Z").Else("C04U0DJSG0Z")
	}
	// If you're running against a different Slack workspace, override the channel ID with this env var.
	if envChannelID := os.Getenv("TF_ACC_CHANNEL_ID"); envChannelID != "" {
		return envChannelID
	}

	// This channel exists in the default workspace used by incident.io engineers for testing, so is a helpful default.
	return lo.If(withTeam, "T02A1FSLE8J/C0392FG9C20").Else("C0392FG9C20")
}

func accIncidentAlertRouteChannelConfig(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing with channel_config
			{
				Config: testAccIncidentAlertRouteResourceConfigWithChannelConfig("channel-config-test"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestMatchResourceAttr("incident_alert_route.channel_config_test", "id", regexp.MustCompile("^[a-zA-Z0-9]+$")),
					resource.TestCheckResourceAttr("incident_alert_route.channel_config_test", "name", StableSuffix("channel-config-test")),

					// Verify channel config exists and has the expected content
					resource.TestCheckResourceAttr("incident_alert_route.channel_config_test", "channel_config.#", "1"),
					resource.TestCheckResourceAttr("incident_alert_route.channel_config_test", "channel_config.0.slack_targets.channel_visibility", "public"),
					resource.TestCheckResourceAttr("incident_alert_route.channel_config_test", "channel_config.0.slack_targets.binding.value.literal", channelID(true)),
				),
			},
			// Test empty channel_config to ensure it's handled correctly
			{
				Config: testAccIncidentAlertRouteResourceConfigWithEmptyChannelConfig("channel-config-test"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("incident_alert_route.channel_config_test", "channel_config.#", "0"),
				),
			},
		},
	})
}

func accIncidentAlertRouteResourceConditionalConfig(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: testAccIncidentAlertRouteResourceConfigWithVars("test-route"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestMatchResourceAttr("incident_alert_route.test", "id", regexp.MustCompile("^[a-zA-Z0-9]+$")),
				),
			},
		},
	})
}

func accIncidentCustomFieldsAlphabeticalOrder(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// First step - create alert route with custom fields in reverse alphabetical order
			{
				Config: testAccIncidentAlertRouteWithAlphabeticalCustomFields("custom-fields-alpha-test"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestMatchResourceAttr("incident_alert_route.custom_fields_alpha_test", "id", regexp.MustCompile("^[a-zA-Z0-9]+$")),

					// Verify both custom fields exist
					resource.TestCheckResourceAttrSet("incident_custom_field.alpha_field1", "id"),
					resource.TestCheckResourceAttrSet("incident_custom_field.alpha_field2", "id"),

					// Check that we have exactly 2 custom fields
					resource.TestCheckResourceAttr("incident_alert_route.custom_fields_alpha_test", "incident_template.custom_fields.#", "2"),
				),
			},
			// Second step - refresh state and verify no diff
			{
				RefreshState: true,
				PlanOnly:     true,
				RefreshPlanChecks: resource.RefreshPlanChecks{
					PostRefresh: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				Check: resource.ComposeAggregateTestCheckFunc(
					// Only check custom fields, not other attributes
					resource.TestCheckResourceAttr("incident_alert_route.custom_fields_alpha_test", "incident_template.custom_fields.#", "2"),
				),
			},
		},
	})
}

func testAccIncidentAlertRouteWithAlphabeticalCustomFields(name string) string {
	name = StableSuffix(name)

	return fmt.Sprintf(`
  resource "incident_custom_field" "alpha_field1" {
    name        = "af1-%s"
    description = "First alphabetical custom field"
    field_type  = "text"
  }

  resource "incident_custom_field" "alpha_field2" {
    name        = "af2-%s"
    description = "Second alphabetical custom field"
    field_type  = "text"
    depends_on = [incident_custom_field.alpha_field1]

  }

  resource "incident_alert_source" "alpha_test" {
    name        = "asrc-%s"
    source_type = "http"
    template = {
      title = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Payload → Title"
                    missing = false
                    name    = "title"
                  }
                  type = "varSpec"
                },
              ]
              type = "paragraph"
            },
          ]
          type = "doc"
        })
      }
      description = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Payload → Description"
                    missing = false
                    name    = "description"
                  }
                  type = "varSpec"
                },
              ]
              type = "paragraph"
            },
          ]
          type = "doc"
        })
      }
      attributes  = []
      expressions = []
    }
  }

  resource "incident_alert_route" "custom_fields_alpha_test" {
    name       = "%s"
    enabled    = true
    is_private = false

    alert_sources = [
      {
        alert_source_id = incident_alert_source.alpha_test.id
        condition_groups = []
      }
    ]

    # Minimal configuration, focusing only on custom fields
    condition_groups = []
    expressions = []
    channel_config = []

    escalation_config = {
      auto_cancel_escalations = true
      escalation_targets = []
    }

    incident_config = {
      auto_decline_enabled       = false
      auto_relate_grouped_alerts = false
      enabled                    = true
      condition_groups           = []
      defer_time_seconds         = 300
      grouping_keys              = []
      grouping_window_seconds    = 1800
    }

    incident_template = {
      # Focus on custom fields in reverse lexicographical order
      custom_fields = [
       {
          custom_field_id = incident_custom_field.alpha_field2.id
          merge_strategy = "first-wins"
          binding = {
            value = {
              literal = "First alphabetical custom field value"
            }
          }
        },
        {
          custom_field_id = incident_custom_field.alpha_field1.id
          merge_strategy = "first-wins"
          binding = {
            value = {
              literal = "Second alphabetical custom field value"
            }
          }
        }
      ]

      # Minimal required configuration for name and summary
      name = {
        autogenerated = false
        value = {
          literal = jsonencode({
            content = [
              {
                content = [
                  {
                    text = "Test Incident"
                    type = "text"
                  }
                ]
                type = "paragraph"
              }
            ]
            type = "doc"
          })
        }
      }
      summary = {
        autogenerated = false
        value = {
          literal = jsonencode({
            content = [
              {
                content = [
                  {
                    text = "Test Incident Summary"
                    type = "text"
                  }
                ]
                type = "paragraph"
              }
            ]
            type = "doc"
          })
        }
      }
      severity = {
        merge_strategy = "first-wins"
      }
    }
  }
  `, testRunID[:8], testRunID[:8], testRunID[:8], name)
}

func testAccIncidentAlertRouteResourceConfig(name string) string {
	name = StableSuffix(name)

	return fmt.Sprintf(`
resource "incident_alert_route" "test" {
  name = %[1]q
  enabled = true
  is_private = false

  alert_sources = []
  channel_config = []
  condition_groups = []
  expressions = []

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets = []
  }

  incident_config = {
    auto_decline_enabled       = true
    auto_relate_grouped_alerts = false
    condition_groups           = []
    defer_time_seconds         = 0
    grouping_keys              = []
    grouping_window_seconds    = 0
    enabled                    = true
  }

  incident_template = {
    name = {
      autogenerated = false
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Title"
                    missing = false
                    name    = "alert.title"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }

	summary = {
		autogenerated = false
		value = {
			literal = jsonencode({
				content = [
					{
						content = [
							{
								attrs = {
									label   = "Alert → Description"
									missing = false
									name    = "alert.description"
								}
								type = "varSpec"
							}
						]
						type = "paragraph"
					}
				]
				type = "doc"
			})
		}
	}

	custom_fields = []

	severity = {
      merge_strategy = "first-wins"
	}
  }
}
`, name)
}

func testAccIncidentAlertRouteResourceConfigAutoGenerated(name string, autogenerated bool) string {
	name = StableSuffix(name)

	return fmt.Sprintf(`
resource "incident_alert_source" "auto_gen_test" {
  name        = "agsrc-%[1]s"
  source_type = "http"
  template = {
    title = {
      literal = jsonencode({
        content = [
          {
            content = [
              {
                attrs = {
                  label   = "Payload → Title"
                  missing = false
                  name    = "title"
                }
                type = "varSpec"
              },
            ]
            type = "paragraph"
          },
        ]
        type = "doc"
      })
    }
    description = {
      literal = jsonencode({
        content = [
          {
            content = [
              {
                attrs = {
                  label   = "Payload → Description"
                  missing = false
                  name    = "description"
                }
                type = "varSpec"
              },
            ]
            type = "paragraph"
          },
        ]
        type = "doc"
      })
    }
    attributes  = []
    expressions = []
  }
}

resource "incident_alert_route" "auto_gen" {
  name       = %[1]q
  enabled    = true
  is_private = false

  alert_sources = [
    {
      alert_source_id = incident_alert_source.auto_gen_test.id
      condition_groups = []
    }
  ]

  condition_groups = []
  expressions = []
  channel_config = []

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets = []
  }

  incident_config = {
    auto_decline_enabled       = false
    auto_relate_grouped_alerts = false
    enabled                    = true
    condition_groups           = []
    defer_time_seconds         = 300
    grouping_keys              = []
    grouping_window_seconds    = 1800
  }

  incident_template = {
    custom_fields = []
    name = {
      autogenerated = %[2]t
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Title"
                    missing = false
                    name    = "alert.title"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }
    summary = {
      autogenerated = %[2]t
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Description"
                    missing = false
                    name    = "alert.description"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }
    severity = {
      merge_strategy = "first-wins"
    }
  }
}
`, name, autogenerated)
}

func testAccIncidentAlertRouteResourceConfigComprehensive(name string) string {
	name = StableSuffix(name)

	return fmt.Sprintf(`
resource "incident_custom_field" "type_field" {
  name        = "ttf-%[1]s"
  description = "The type of the incident."
  field_type  = "text"
}

resource "incident_alert_source" "http_test" {
  name        = "hsrc-%[1]s"
  source_type = "http"
  template = {
    title = {
      literal = jsonencode({
        content = [
          {
            content = [
              {
                attrs = {
                  label   = "Payload → Title"
                  missing = false
                  name    = "title"
                }
                type = "varSpec"
              },
            ]
            type = "paragraph"
          },
        ]
        type = "doc"
      })
    }
    description = {
      literal = jsonencode({
        content = [
          {
            content = [
              {
                attrs = {
                  label   = "Payload → Description"
                  missing = false
                  name    = "description"
                }
                type = "varSpec"
              },
            ]
            type = "paragraph"
          },
        ]
        type = "doc"
      })
    }
    attributes  = []
    expressions = []
  }
}

resource "incident_alert_route" "comprehensive" {
  name       = %[1]q
  enabled    = true
  is_private = false

  alert_sources = [
    {
      alert_source_id = incident_alert_source.http_test.id
      condition_groups = []
    }
  ]

  condition_groups = [
    {
      conditions = [
        {
          subject   = "alert.title"
          operation = "is_set"
          param_bindings = []
        }
      ]
    }
  ]

  expressions = []

  channel_config = []

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets = []
  }

  incident_config = {
    auto_decline_enabled       = false
    auto_relate_grouped_alerts = false
    enabled                    = true
    condition_groups           = []
    defer_time_seconds         = 300
    grouping_keys              = []
    grouping_window_seconds    = 1800
  }

  incident_template = {
    custom_fields = [
      {
        custom_field_id = incident_custom_field.type_field.id
        merge_strategy = "first-wins"
        binding = {
          value = {
            literal = "Test incident"
          }
        }
      }
    ]
    name = {
      autogenerated = true
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Title"
                    missing = false
                    name    = "alert.title"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }
    summary = {
      autogenerated = true
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Description"
                    missing = false
                    name    = "alert.description"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }
    start_in_triage = {
      value = {
        literal = "true"
      }
    }
    severity = {
      merge_strategy = "first-wins"
    }
  }
}
`, name)
}

func testAccIncidentAlertRouteResourceConfigWithChannelConfig(name string) string {
	name = StableSuffix(name)

	return testRunTemplate("incident_alert_route.channel_config", `
resource "incident_alert_source" "channel_test" {
  name        = "chsrc-{{ .Name }}"
  source_type = "http"
  template = {
    title = {
      literal = jsonencode({
        content = [
          {
            content = [
              {
                attrs = {
                  label   = "Payload → Title"
                  missing = false
                  name    = "title"
                }
                type = "varSpec"
              },
            ]
            type = "paragraph"
          },
        ]
        type = "doc"
      })
    }
    description = {
      literal = jsonencode({
        content = [
          {
            content = [
              {
                attrs = {
                  label   = "Payload → Description"
                  missing = false
                  name    = "description"
                }
                type = "varSpec"
              },
            ]
            type = "paragraph"
          },
        ]
        type = "doc"
      })
    }
    attributes  = []
    expressions = []
  }
}

resource "incident_alert_route" "channel_config_test" {
  name       = {{ quote .Name }}
  enabled    = true
  is_private = false

  alert_sources = [
    {
      alert_source_id = incident_alert_source.channel_test.id
      condition_groups = []
    }
  ]

  condition_groups = []
  expressions = []

  channel_config = [
    {
      condition_groups = []
      slack_targets = {
        channel_visibility = "public"
        binding = {
          value = {
            literal = {{ quote .ChannelID }}
          }
        }
      }
    }
  ]

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets = []
  }

  incident_config = {
    auto_decline_enabled       = false
    auto_relate_grouped_alerts = false
    enabled                    = true
    condition_groups           = []
    defer_time_seconds         = 300
    grouping_keys              = []
    grouping_window_seconds    = 1800
  }

  incident_template = {
    custom_fields = []
    name = {
      autogenerated = false
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Title"
                    missing = false
                    name    = "alert.title"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }
    summary = {
      autogenerated = false
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Description"
                    missing = false
                    name    = "alert.description"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }
    severity = {
      merge_strategy = "first-wins"
    }
  }
}
`, struct{ Name, ChannelID string }{
		Name:      name,
		ChannelID: channelID(true),
	})
}

func testAccIncidentAlertRouteResourceConfigWithEmptyChannelConfig(name string) string {
	name = StableSuffix(name)

	return fmt.Sprintf(`
resource "incident_alert_source" "channel_test" {
  name        = "chsrc-%[1]s"
  source_type = "http"
  template = {
    title = {
      literal = jsonencode({
        content = [
          {
            content = [
              {
                attrs = {
                  label   = "Payload → Title"
                  missing = false
                  name    = "title"
                }
                type = "varSpec"
              },
            ]
            type = "paragraph"
          },
        ]
        type = "doc"
      })
    }
    description = {
      literal = jsonencode({
        content = [
          {
            content = [
              {
                attrs = {
                  label   = "Payload → Description"
                  missing = false
                  name    = "description"
                }
                type = "varSpec"
              },
            ]
            type = "paragraph"
          },
        ]
        type = "doc"
      })
    }
    attributes  = []
    expressions = []
  }
}

resource "incident_alert_route" "channel_config_test" {
  name       = %[1]q
  enabled    = true
  is_private = false

  alert_sources = [
    {
      alert_source_id = incident_alert_source.channel_test.id
      condition_groups = []
    }
  ]

  condition_groups = []
  expressions = []

  # Empty channel_config to test removal behavior
  channel_config = []

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets = []
  }

  incident_config = {
    auto_decline_enabled       = false
    auto_relate_grouped_alerts = false
    enabled                    = true
    condition_groups           = []
    defer_time_seconds         = 300
    grouping_keys              = []
    grouping_window_seconds    = 1800
  }

  incident_template = {
    custom_fields = []
    name = {
      autogenerated = false
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Title"
                    missing = false
                    name    = "alert.title"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }
    summary = {
      autogenerated = false
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Description"
                    missing = false
                    name    = "alert.description"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }
    severity = {
      merge_strategy = "first-wins"
    }
  }
}`, name)
}

// accIncidentAlertRouteResourceBranchesValidation tests that expressions using branches
// operations with a non-"." root_reference are rejected at plan time.
func accIncidentAlertRouteResourceBranchesValidation(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config:      testAccIncidentAlertRouteResourceConfigInvalidBranches(),
				PlanOnly:    true,
				ExpectError: regexp.MustCompile(`Invalid root_reference for branches operation`),
			},
		},
	})
}

func testAccIncidentAlertRouteResourceConfigInvalidBranches() string {
	return `
resource "incident_alert_route" "invalid_branches" {
  name       = "invalid-branches-test"
  enabled    = true
  is_private = false

  alert_sources = []
  channel_config = []
  condition_groups = []

  # This is the invalid pattern: using root_reference with a nested path
  # combined with a branches operation. Branches operations require
  # root_reference to be "." with conditions using absolute paths.
  expressions = [
    {
      label          = "Test Expression"
      reference      = "test-expr"
      root_reference = "alert.attributes.some-attribute-id"  # Invalid: should be "."
      operations = [
        {
          operation_type = "branches"
          branches = {
            returns = {
              type  = "IncidentSeverity"
              array = false
            }
            branches = [
              {
                condition_groups = [
                  {
                    conditions = [
                      {
                        subject   = "alert.title"
                        operation = "is_set"
                        param_bindings = []
                      }
                    ]
                  }
                ]
                result = {
                  value = {
                    literal = "01ABC123"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  ]

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets = []
  }

  incident_config = {
    auto_decline_enabled    = true
    condition_groups        = []
    defer_time_seconds      = 0
    grouping_keys           = []
    grouping_window_seconds = 0
    enabled                 = true
  }

  incident_template = {
    name = {
      autogenerated = false
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Title"
                    missing = false
                    name    = "alert.title"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }
    summary = {
      autogenerated = false
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Description"
                    missing = false
                    name    = "alert.description"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }
    custom_fields = []
    severity = {
      merge_strategy = "first-wins"
    }
  }
}
`
}

func testAccIncidentAlertRouteResourceConfigWithVars(name string) string {
	name = StableSuffix(name)

	return fmt.Sprintf(`
locals {
  with_conds = false
}

resource "incident_alert_route" "test" {
  name = %[1]q
  enabled = true
  is_private = false

  alert_sources = []
  channel_config = []
  condition_groups = local.with_conds ? [
    {
      conditions = [
        {
          subject   = "alert.title"
          operation = "is_set"
          param_bindings = []
        },
      ],
    },
  ] : []
  expressions = []

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets = []
  }

  incident_config = {
    auto_decline_enabled       = true
    auto_relate_grouped_alerts = false
    condition_groups           = []
    defer_time_seconds         = 0
    grouping_keys              = []
    grouping_window_seconds    = 1800
    enabled                    = true
  }

  incident_template = {
    name = {
      autogenerated = false
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    # Note that this uses '->' not '→' to test escaping if you dislike the fancy character
                    label   = "Alert -> Title"
                    missing = false
                    name    = "alert.title"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }

	summary = {
		autogenerated = false
		value = {
			literal = jsonencode({
				content = [
					{
						content = [
							{
								attrs = {
                  # Note that this uses '→' not '->' to test if you use a fancy character
									label   = "Alert → Description"
									missing = false
									name    = "alert.description"
								}
								type = "varSpec"
							}
						]
						type = "paragraph"
					}
				]
				type = "doc"
			})
		}
	}

	custom_fields = []

	severity = {
      merge_strategy = "first-wins"
	}
  }
}
`, name)
}

// accIncidentAlertRouteResourceAutoRelateGroupedAlertsOmitted tests that when
// auto_relate_grouped_alerts is omitted from the config, it defaults to false.
func accIncidentAlertRouteResourceAutoRelateGroupedAlertsOmitted(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccIncidentAlertRouteResourceConfigAutoRelateGroupedAlertsOmitted("auto-relate-omitted-test"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("incident_alert_route.test", "name", StableSuffix("auto-relate-omitted-test")),
					// Verify field defaults to false when omitted
					resource.TestCheckResourceAttr("incident_alert_route.test", "incident_config.auto_relate_grouped_alerts", "false"),
					resource.TestCheckResourceAttr("incident_alert_route.test", "incident_config.auto_decline_enabled", "true"),
					resource.TestCheckResourceAttr("incident_alert_route.test", "incident_config.enabled", "true"),
				),
			},
		},
	})
}

// accIncidentAlertRouteResourceAutoRelateGroupedAlertsTrue tests that when
// auto_relate_grouped_alerts is explicitly set to true, it is correctly stored and retrieved.
func accIncidentAlertRouteResourceAutoRelateGroupedAlertsTrue(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccIncidentAlertRouteResourceConfigAutoRelateGroupedAlertsTrue("auto-relate-true-test"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("incident_alert_route.test", "name", StableSuffix("auto-relate-true-test")),
					// Verify field is set to true
					resource.TestCheckResourceAttr("incident_alert_route.test", "incident_config.auto_relate_grouped_alerts", "true"),
					resource.TestCheckResourceAttr("incident_alert_route.test", "incident_config.auto_decline_enabled", "false"),
					resource.TestCheckResourceAttr("incident_alert_route.test", "incident_config.enabled", "true"),
				),
			},
		},
	})
}

func testAccIncidentAlertRouteResourceConfigAutoRelateGroupedAlertsOmitted(name string) string {
	name = StableSuffix(name)

	return fmt.Sprintf(`
resource "incident_alert_route" "test" {
  name = %[1]q
  enabled = true
  is_private = false

  alert_sources = []
  channel_config = []
  condition_groups = []
  expressions = []

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets = []
  }

  incident_config = {
    auto_decline_enabled    = true
    # auto_relate_grouped_alerts is intentionally omitted to test default behavior
    condition_groups        = []
    defer_time_seconds      = 0
    grouping_keys           = []
    grouping_window_seconds = 0
    enabled                 = true
  }

  incident_template = {
    name = {
      autogenerated = false
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Title"
                    missing = false
                    name    = "alert.title"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }

	summary = {
		autogenerated = false
		value = {
			literal = jsonencode({
				content = [
					{
						content = [
							{
								attrs = {
									label   = "Alert → Description"
									missing = false
									name    = "alert.description"
								}
								type = "varSpec"
							}
						]
						type = "paragraph"
					}
				]
				type = "doc"
			})
		}
	}

	custom_fields = []

	severity = {
      merge_strategy = "first-wins"
	}
  }
}
`, name)
}

func testAccIncidentAlertRouteResourceConfigAutoRelateGroupedAlertsTrue(name string) string {
	name = StableSuffix(name)

	return fmt.Sprintf(`
resource "incident_alert_route" "test" {
  name = %[1]q
  enabled = true
  is_private = false

  alert_sources = []
  channel_config = []
  condition_groups = []
  expressions = []

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets = []
  }

  incident_config = {
    auto_decline_enabled       = false
    auto_relate_grouped_alerts = true  # Explicitly set to true
    condition_groups           = []
    defer_time_seconds         = 0
    grouping_keys              = []
    grouping_window_seconds    = 1800 # Required to be non-zero when auto_relate_grouped_alerts is true
    enabled                    = true
  }

  incident_template = {
    name = {
      autogenerated = false
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Title"
                    missing = false
                    name    = "alert.title"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }

	summary = {
		autogenerated = false
		value = {
			literal = jsonencode({
				content = [
					{
						content = [
							{
								attrs = {
									label   = "Alert → Description"
									missing = false
									name    = "alert.description"
								}
								type = "varSpec"
							}
						]
						type = "paragraph"
					}
				]
				type = "doc"
			})
		}
	}

	custom_fields = []

	severity = {
      merge_strategy = "first-wins"
	}
  }
}
`, name)
}

// accIncidentAlertRouteResourceOwningTeamIDs checks that owning_team_ids work correctly for alert routes.
func accIncidentAlertRouteResourceOwningTeamIDs(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create alert route with owning_team_ids
			{
				Config: testAccIncidentAlertRouteResourceConfigWithOwningTeamIDs("test-route-with-teams"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("incident_alert_route.test", "name", StableSuffix("test-route-with-teams")),
					resource.TestCheckResourceAttr("incident_alert_route.test", "owning_team_ids.#", "1"),
					resource.TestCheckResourceAttrPair("incident_alert_route.test", "owning_team_ids.0", "incident_catalog_entry.owner_team", "id"),
				),
			},
			// Update to add another team
			{
				Config: testAccIncidentAlertRouteResourceConfigWithMultipleOwningTeamIDs("test-route-with-multiple-teams"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("incident_alert_route.test", "name", StableSuffix("test-route-with-multiple-teams")),
					resource.TestCheckResourceAttr("incident_alert_route.test", "owning_team_ids.#", "2"),
				),
			},
		},
	})
}

func testAccIncidentAlertRouteResourceConfigWithOwningTeamIDs(name string) string {
	name = StableSuffix(name)

	return fmt.Sprintf(`
# Look up the Team catalog type
data "incident_catalog_type" "team" {
  name = %[2]q
}

# Create a team catalog entry for this test
resource "incident_catalog_entry" "owner_team" {
  catalog_type_id = data.incident_catalog_type.team.id
  external_id     = %[3]q
  name            = "tma-%[1]s"
  attribute_values = []
}

resource "incident_alert_source" "test" {
  name        = "fsrc-%[1]s"
  source_type = "http"
  template = {
    title = {
      literal = jsonencode({
        content = [
          {
            content = [
              {
                attrs = {
                  label   = "Payload → Title"
                  missing = false
                  name    = "title"
                }
                type = "varSpec"
              },
            ]
            type = "paragraph"
          },
        ]
        type = "doc"
      })
    }
    description = {
      literal = jsonencode({
        content = [
          {
            content = [
              {
                attrs = {
                  label   = "Payload → Description"
                  missing = false
                  name    = "description"
                }
                type = "varSpec"
              },
            ]
            type = "paragraph"
          },
        ]
        type = "doc"
      })
    }
    attributes  = []
    expressions = []
  }
}

resource "incident_alert_route" "test" {
  name       = %[1]q
  enabled    = true
  is_private = false

  alert_sources = [
    {
      alert_source_id = incident_alert_source.test.id
      condition_groups = []
    }
  ]

  condition_groups = []
  expressions = []
  channel_config = []

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets = []
  }

  incident_config = {
    auto_decline_enabled       = false
    auto_relate_grouped_alerts = false
    enabled                    = true
    condition_groups           = []
    defer_time_seconds         = 300
    grouping_keys              = []
    grouping_window_seconds    = 1800
  }

  incident_template = {
    custom_fields = []
    name = {
      autogenerated = true
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Title"
                    missing = false
                    name    = "alert.title"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }
    summary = {
      autogenerated = true
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Description"
                    missing = false
                    name    = "alert.description"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }
    severity = {
      merge_strategy = "first-wins"
    }
  }

  owning_team_ids = [incident_catalog_entry.owner_team.id]
}
`, name, teamTypeName(), StableSuffix("tf-alert-route-owning-team-test"))
}

func testAccIncidentAlertRouteResourceConfigWithMultipleOwningTeamIDs(name string) string {
	name = StableSuffix(name)

	return fmt.Sprintf(`
# Look up the Team catalog type
data "incident_catalog_type" "team" {
  name = %[2]q
}

# Create team catalog entries for this test
resource "incident_catalog_entry" "owner_team" {
  catalog_type_id = data.incident_catalog_type.team.id
  external_id     = %[3]q
  name            = "tma-%[1]s"
  attribute_values = []
}

resource "incident_catalog_entry" "owner_team_2" {
  catalog_type_id = data.incident_catalog_type.team.id
  external_id     = %[4]q
  name            = "tmb-%[1]s"
  attribute_values = []
}

resource "incident_alert_source" "test" {
  name        = "fsrc-%[1]s"
  source_type = "http"
  template = {
    title = {
      literal = jsonencode({
        content = [
          {
            content = [
              {
                attrs = {
                  label   = "Payload → Title"
                  missing = false
                  name    = "title"
                }
                type = "varSpec"
              },
            ]
            type = "paragraph"
          },
        ]
        type = "doc"
      })
    }
    description = {
      literal = jsonencode({
        content = [
          {
            content = [
              {
                attrs = {
                  label   = "Payload → Description"
                  missing = false
                  name    = "description"
                }
                type = "varSpec"
              },
            ]
            type = "paragraph"
          },
        ]
        type = "doc"
      })
    }
    attributes  = []
    expressions = []
  }
}

resource "incident_alert_route" "test" {
  name       = %[1]q
  enabled    = true
  is_private = false

  alert_sources = [
    {
      alert_source_id = incident_alert_source.test.id
      condition_groups = []
    }
  ]

  condition_groups = []
  expressions = []
  channel_config = []

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets = []
  }

  incident_config = {
    auto_decline_enabled       = false
    auto_relate_grouped_alerts = false
    enabled                    = true
    condition_groups           = []
    defer_time_seconds         = 300
    grouping_keys              = []
    grouping_window_seconds    = 1800
  }

  incident_template = {
    custom_fields = []
    name = {
      autogenerated = true
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Title"
                    missing = false
                    name    = "alert.title"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }
    summary = {
      autogenerated = true
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert → Description"
                    missing = false
                    name    = "alert.description"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }
    severity = {
      merge_strategy = "first-wins"
    }
  }

  owning_team_ids = [
    incident_catalog_entry.owner_team.id,
    incident_catalog_entry.owner_team_2.id
  ]
}
`, name, teamTypeName(), StableSuffix("tf-alert-route-owning-team-test"),
		StableSuffix("tf-alert-route-owning-team-test-2"))
}

// accIncidentAlertRouteResourceRawJSONLiteral reproduces ONC-11943: a
// template literal containing raw HTML characters ('>') supplied WITHOUT
// HTML-escaping (as CDKTF JSON.stringify, file() or a heredoc would produce)
// must apply cleanly and show an empty plan on refresh. Before the
// jsontypes.NormalizedJSONOrString semantic-equality fix this raised "Provider
// produced inconsistent result after apply", because the provider re-encoded
// the literal and HTML-escaped '>' to '&gt;' on the way back into state while
// the planned value kept the raw '>'.
func accIncidentAlertRouteResourceRawJSONLiteral(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Apply with a raw (non-HTML-escaped) literal containing '>'.
			{
				Config: testAccIncidentAlertRouteResourceConfigRawJSONLiteral("raw-json-literal-test"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestMatchResourceAttr("incident_alert_route.test", "id", regexp.MustCompile("^[a-zA-Z0-9]+$")),
					resource.TestCheckResourceAttr("incident_alert_route.test", "name", StableSuffix("raw-json-literal-test")),
				),
			},
			// Re-plan: must be empty (no perpetual diff from escaping/key order).
			{
				RefreshState: true,
				PlanOnly:     true,
				RefreshPlanChecks: resource.RefreshPlanChecks{
					PostRefresh: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
			},
			// Re-apply the identical config: the plan must be empty (no-op).
			{
				Config: testAccIncidentAlertRouteResourceConfigRawJSONLiteral("raw-json-literal-test"),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
			},
		},
	})
}

// accIncidentAlertRouteResourceEscapedJSONLiteral proves the HCL jsonencode
// user population (which HTML-escapes '>' to '>') continues to work. The
// '→' / '->' template labels exercise both the raw-arrow and fancy-arrow cases.
func accIncidentAlertRouteResourceEscapedJSONLiteral(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccIncidentAlertRouteResourceConfigWithVars("escaped-json-literal-test"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestMatchResourceAttr("incident_alert_route.test", "id", regexp.MustCompile("^[a-zA-Z0-9]+$")),
				),
			},
			{
				RefreshState: true,
				PlanOnly:     true,
				RefreshPlanChecks: resource.RefreshPlanChecks{
					PostRefresh: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
			},
		},
	})
}

// testAccIncidentAlertRouteResourceConfigRawJSONLiteral builds an alert route
// whose name template literal is a raw JSON heredoc containing an unescaped '>'
// in the "Alert -> Title" label. Heredocs do not HTML-escape, unlike HCL's
// jsonencode, which is exactly the encoder asymmetry that triggered the bug.
func testAccIncidentAlertRouteResourceConfigRawJSONLiteral(name string) string {
	name = StableSuffix(name)

	return fmt.Sprintf(`
resource "incident_alert_route" "test" {
  name       = %[1]q
  enabled    = true
  is_private = false

  alert_sources    = []
  channel_config   = []
  condition_groups = []
  expressions      = []

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets      = []
  }

  incident_config = {
    auto_decline_enabled    = true
    condition_groups        = []
    defer_time_seconds      = 0
    grouping_keys           = []
    grouping_window_seconds = 0
    enabled                 = true
  }

  incident_template = {
    name = {
      autogenerated = false
      value = {
        # Raw JSON, NOT via jsonencode: the '>' stays literal and is never
        # HTML-escaped, reproducing the CDKTF / file() / heredoc scenario.
        literal = <<-JSON
          {"type":"doc","content":[{"type":"paragraph","content":[{"type":"varSpec","attrs":{"name":"alert.title","label":"Alert -> Title","missing":false}}]}]}
        JSON
      }
    }
    summary = {
      autogenerated = false
      value = {
        literal = <<-JSON
          {"type":"doc","content":[{"type":"paragraph","content":[{"type":"varSpec","attrs":{"name":"alert.description","label":"Alert -> Description","missing":false}}]}]}
        JSON
      }
    }
    custom_fields = []
    severity = {
      merge_strategy = "first-wins"
    }
  }
}
`, name)
}

// accIncidentAlertRouteResourceCastExpression covers the `cast` operation on
// expressions. A route exported from the dashboard with a cast could not be applied:
// the provider had no `cast` attribute, so it sent the operation with no options and
// the API rejected the write with
// "expressions.0.operations.0.cast: Must be provided".
//
// The read path is worth exercising too. The API doesn't echo cast options back — it
// reports the cast target as the operation's own returns — so we rebuild the block
// from those, and a mistake there shows up as a diff on refresh.
func accIncidentAlertRouteResourceCastExpression(t *testing.T) {
	castTypeRegexp := regexp.MustCompile(`^CatalogEntry\["[a-zA-Z0-9]+"\]$`)

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create: this is the write that used to fail with a 422.
			{
				Config: testAccIncidentAlertRouteResourceConfigCastExpression("cast-route"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("incident_alert_route.cast", "expressions.0.reference", "service_from_title"),
					resource.TestCheckResourceAttr("incident_alert_route.cast", "expressions.0.root_reference", "alert.title"),
					resource.TestCheckResourceAttr("incident_alert_route.cast", "expressions.0.operations.0.operation_type", "cast"),
					resource.TestMatchResourceAttr("incident_alert_route.cast", "expressions.0.operations.0.cast.returns.type", castTypeRegexp),
					resource.TestCheckResourceAttr("incident_alert_route.cast", "expressions.0.operations.0.cast.returns.array", "false"),
				),
			},
			// Refresh: the cast has to survive a read, or every plan shows a diff.
			{
				RefreshState: true,
				PlanOnly:     true,
				RefreshPlanChecks: resource.RefreshPlanChecks{
					PostRefresh: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("incident_alert_route.cast", "expressions.0.operations.0.operation_type", "cast"),
					resource.TestMatchResourceAttr("incident_alert_route.cast", "expressions.0.operations.0.cast.returns.type", castTypeRegexp),
				),
			},
			// Update: the report was an update to a route that already existed, which
			// rebuilds the same expression payload from state.
			{
				Config: testAccIncidentAlertRouteResourceConfigCastExpression("cast-route-updated"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("incident_alert_route.cast", "name", StableSuffix("cast-route-updated")),
					resource.TestCheckResourceAttr("incident_alert_route.cast", "expressions.0.operations.0.operation_type", "cast"),
					resource.TestMatchResourceAttr("incident_alert_route.cast", "expressions.0.operations.0.cast.returns.type", castTypeRegexp),
				),
			},
		},
	})
}

// testAccIncidentAlertRouteResourceConfigCastExpression builds a route carrying a single
// cast expression. The catalog type is created alongside it so the cast has a real target
// to name: casting a string into a catalog entry is what the operation is normally for.
func testAccIncidentAlertRouteResourceConfigCastExpression(name string) string {
	name = StableSuffix(name)
	catalogTypeName := StableSuffix("Cast Target")

	return fmt.Sprintf(`
resource "incident_catalog_type" "cast_target" {
  name        = %[2]q
  description = "Target type for an alert route cast expression"

  source_repo_url = "https://github.com/incident-io/terraform-demo"
}

resource "incident_alert_route" "cast" {
  name = %[1]q
  enabled = true
  is_private = false

  alert_sources = []
  channel_config = []
  condition_groups = []

  expressions = [
    {
      label          = "Service from title"
      reference      = "service_from_title"
      root_reference = "alert.title"
      operations = [
        {
          operation_type = "cast"
          cast = {
            returns = {
              type  = "CatalogEntry[\"${incident_catalog_type.cast_target.id}\"]"
              array = false
            }
          }
        }
      ]
    }
  ]

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets = []
  }

  incident_config = {
    auto_decline_enabled       = true
    auto_relate_grouped_alerts = false
    condition_groups           = []
    defer_time_seconds         = 0
    grouping_keys              = []
    grouping_window_seconds    = 0
    enabled                    = true
  }

  incident_template = {
    name = {
      autogenerated = false
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert \u2192 Title"
                    missing = false
                    name    = "alert.title"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }

    summary = {
      autogenerated = false
      value = {
        literal = jsonencode({
          content = [
            {
              content = [
                {
                  attrs = {
                    label   = "Alert \u2192 Description"
                    missing = false
                    name    = "alert.description"
                  }
                  type = "varSpec"
                }
              ]
              type = "paragraph"
            }
          ]
          type = "doc"
        })
      }
    }

    custom_fields = []

    severity = {
      merge_strategy = "first-wins"
    }
  }
}
`, name, catalogTypeName)
}
