package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func accIncidentTemplateResource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: testAccIncidentTemplateResourceConfig("payments-template", "true"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("incident_incident_template.test", "name", StableSuffix("payments-template")),
					resource.TestCheckResourceAttrSet("incident_incident_template.test", "id"),
					resource.TestCheckResourceAttr("incident_incident_template.test", "template.name.autogenerated", "false"),
					resource.TestCheckResourceAttr("incident_incident_template.test", "template.summary.autogenerated", "true"),
					resource.TestCheckResourceAttr("incident_incident_template.test", "template.start_in_triage.value.literal", "true"),
					resource.TestCheckResourceAttr("incident_incident_template.test", "template.severity.merge_strategy", "max"),
					resource.TestCheckResourceAttr("incident_incident_template.test", "template.custom_fields.#", "1"),
				),
			},
			// ImportState testing
			{
				ResourceName:      "incident_incident_template.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
			// Update testing
			{
				Config: testAccIncidentTemplateResourceConfig("payments-template-updated", "false"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("incident_incident_template.test", "name", StableSuffix("payments-template-updated")),
					resource.TestCheckResourceAttr("incident_incident_template.test", "template.start_in_triage.value.literal", "false"),
				),
			},
		},
	})
}

// testAccIncidentTemplateResourceConfig mirrors the shapes the documented
// examples show — a literal name, an AI summary, a severity merge strategy, and
// a custom field bound to a literal — so the acceptance test exercises more than
// a bare template. The custom field name is independent of the template name so
// it isn't replaced between the create and update steps.
func testAccIncidentTemplateResourceConfig(name, startInTriage string) string {
	return testRunTemplate("incident_incident_template", `
resource "incident_custom_field" "affected" {
  name        = {{ quote .CustomFieldName }}
  description = "The team affected by the incident."
  field_type  = "text"
}

resource "incident_incident_template" "test" {
  name = {{ quote .Name }}

  expressions = []

  template = {
    name = {
      autogenerated = false
      value = {
        literal = "Payments incident"
      }
    }
    summary = {
      autogenerated = true
    }
    severity = {
      merge_strategy = "max"
    }
    start_in_triage = {
      value = {
        literal = {{ quote .StartInTriage }}
      }
    }
    custom_fields = [
      {
        custom_field_id = incident_custom_field.affected.id
        merge_strategy  = "first-wins"
        binding = {
          value = {
            literal = "Payments"
          }
        }
      },
    ]
  }
}
`, struct {
		Name            string
		StartInTriage   string
		CustomFieldName string
	}{
		Name:            StableSuffix(name),
		StartInTriage:   startInTriage,
		CustomFieldName: StableSuffix("aff-team"),
	})
}
